(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/FleschKincaidScorer.js":
/*!***********************************************!*\
  !*** ./src/components/FleschKincaidScorer.js ***!
  \***********************************************/
/*! exports provided: MAX_FLESC_KINCAID, MIN_FLESC_KINCAID, FleschKincaidScorer */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MAX_FLESC_KINCAID", function() { return MAX_FLESC_KINCAID; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MIN_FLESC_KINCAID", function() { return MIN_FLESC_KINCAID; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FleschKincaidScorer", function() { return FleschKincaidScorer; });
/* harmony import */ var _helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../helpers/writtenLanguageHelpers */ "./src/helpers/writtenLanguageHelpers.js");


const MAX_FLESC_KINCAID = 120;
const MIN_FLESC_KINCAID = 0;

class FleschKincaidScorer {
  static calculate(text) {
    if (!text) {
      return MAX_FLESC_KINCAID;
    }

    const words = Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countWords"])(text);
    const asl = words / Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countSentences"])(text);
    const asw = Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countSyllables"])(text) / words;
    let score = 206.835 - (1.015 * asl) - (84.6 * asw);

    if (score > MAX_FLESC_KINCAID) {
      score = MAX_FLESC_KINCAID;
    } else if(score < MIN_FLESC_KINCAID) {
      score = MIN_FLESC_KINCAID;
    }

    return score;
  }
}


/***/ }),

/***/ "./src/components/FormGroup.svelte":
/*!*****************************************!*\
  !*** ./src/components/FormGroup.svelte ***!
  \*****************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/FormGroup.svelte generated by Svelte v3.7.1 */


const file = "src/components/FormGroup.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1qjh3vx-style';
	style.textContent = ".form-group.svelte-1qjh3vx{display:flex;flex-direction:column}.form-input.svelte-1qjh3vx{padding:0.5em;width:100% !important;min-height:8em}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRm9ybUdyb3VwLnN2ZWx0ZSIsInNvdXJjZXMiOlsiRm9ybUdyb3VwLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3R5bGUgbGFuZz1cInNjc3NcIj4uZm9ybS1ncm91cCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IH1cblxuLmZvcm0taW5wdXQge1xuICBwYWRkaW5nOiAwLjVlbTtcbiAgd2lkdGg6IDEwMCUgIWltcG9ydGFudDtcbiAgbWluLWhlaWdodDogOGVtOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPUZvcm1Hcm91cC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgdmFsdWUgPSBcIlwiXG4gIGV4cG9ydCBsZXQgc2VsZWN0ZWQgPSBcIlwiO1xuICBleHBvcnQgbGV0IGxhYmVsVGV4dCA9IFwiXCI7XG4gIGV4cG9ydCBsZXQgaWQgPSBcIlwiO1xuICBleHBvcnQgbGV0IHBsYWNlaG9sZGVyID0gXCJcIjtcbjwvc2NyaXB0PlxuXG48ZGl2IGNsYXNzPVwiZm9ybS1ncm91cFwiPlxuICA8dGV4dGFyZWFcbiAgICBpZD17aWR9XG4gICAgY2xhc3M9XCJmb3JtLWlucHV0XCJcbiAgICB0eXBlPVwidGV4dFwiXG4gICAgYmluZDp2YWx1ZT17dmFsdWV9XG4gICAgcGxhY2Vob2xkZXI9e3BsYWNlaG9sZGVyfVxuICAgIGFyaWEtcGxhY2Vob2xkZXI9e3BsYWNlaG9sZGVyfVxuICAvPlxuPC9kaXY+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQW1CLFdBQVcsZUFBQyxDQUFDLEFBQzlCLE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBRTNCLFdBQVcsZUFBQyxDQUFDLEFBQ1gsT0FBTyxDQUFFLEtBQUssQ0FDZCxLQUFLLENBQUUsSUFBSSxDQUFDLFVBQVUsQ0FDdEIsVUFBVSxDQUFFLEdBQUcsQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var div, textarea, dispose;

	return {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			textarea = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("textarea");
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			textarea = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "TEXTAREA", { id: true, class: true, type: true, placeholder: true, "aria-placeholder": true }, false);
			var textarea_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(textarea);

			textarea_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "id", ctx.id);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "class", "form-input svelte-1qjh3vx");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "type", "text");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "placeholder", ctx.placeholder);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "aria-placeholder", ctx.placeholder);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(textarea, file, 20, 2, 398);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", "form-group svelte-1qjh3vx");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 19, 0, 371);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(textarea, "input", ctx.textarea_input_handler);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, textarea);

			textarea.value = ctx.value;
		},

		p: function update(changed, ctx) {
			if (changed.value) textarea.value = ctx.value;

			if (changed.id) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "id", ctx.id);
			}

			if (changed.placeholder) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "placeholder", ctx.placeholder);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "aria-placeholder", ctx.placeholder);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
			}

			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { value = "", selected = "", labelText = "", id = "", placeholder = "" } = $$props;

	const writable_props = ['value', 'selected', 'labelText', 'id', 'placeholder'];
	Object.keys($$props).forEach(key => {
		if (!writable_props.includes(key) && !key.startsWith('$$')) console.warn(`<FormGroup> was created with unknown prop '${key}'`);
	});

	function textarea_input_handler() {
		value = this.value;
		$$invalidate('value', value);
	}

	$$self.$set = $$props => {
		if ('value' in $$props) $$invalidate('value', value = $$props.value);
		if ('selected' in $$props) $$invalidate('selected', selected = $$props.selected);
		if ('labelText' in $$props) $$invalidate('labelText', labelText = $$props.labelText);
		if ('id' in $$props) $$invalidate('id', id = $$props.id);
		if ('placeholder' in $$props) $$invalidate('placeholder', placeholder = $$props.placeholder);
	};

	return {
		value,
		selected,
		labelText,
		id,
		placeholder,
		textarea_input_handler
	};
}

class FormGroup extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1qjh3vx-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], ["value", "selected", "labelText", "id", "placeholder"]);
	}

	get value() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set value(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get selected() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set selected(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get labelText() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set labelText(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get id() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set id(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get placeholder() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set placeholder(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (FormGroup);

/***/ }),

/***/ "./src/components/GunningFlogScorer.js":
/*!*********************************************!*\
  !*** ./src/components/GunningFlogScorer.js ***!
  \*********************************************/
/*! exports provided: MIN_GUNNING_FLOG, MAX_GUNNING_FLOG, GunningFlogScorer */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MIN_GUNNING_FLOG", function() { return MIN_GUNNING_FLOG; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MAX_GUNNING_FLOG", function() { return MAX_GUNNING_FLOG; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "GunningFlogScorer", function() { return GunningFlogScorer; });
/* harmony import */ var _helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../helpers/writtenLanguageHelpers */ "./src/helpers/writtenLanguageHelpers.js");


const MIN_GUNNING_FLOG = 0;
const MAX_GUNNING_FLOG = 30;

const scoreToLevelMap = {
  20:	"Post-graduate Plus",
  19:	"Post-graduate",
  18:	"Post-graduate",
  17:	"College graduate",
  16:	"College senior",
  15:	"College junior",
  14:	"College sophomore",
  13:	"College freshman",
  12:	"High school senior",
  11:	"High school junior",
  10:	"High school sophomore",
  9:	"High school freshman",
  8:	"Eighth grade",
  7:	"Seventh grade",
  6:	"Sixth grade",
}

class GunningFlogScorer {
  static calculate(text) {
    if (!text) {
      return MIN_GUNNING_FLOG;
    }

    const words = Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countWords"])(text);
    const asl = words / Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countSentences"])(text);
    const phw = 100 * (Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countHardWords"])(text) / words);
    let score = 0.4 * (asl + phw)

    if (score > MAX_GUNNING_FLOG) {
      score = MAX_GUNNING_FLOG;
    } else if(score < MIN_GUNNING_FLOG) {
      score = MIN_GUNNING_FLOG;
    }

    return score;
  }
  static scoringLevel(score) {
    const integerScore = parseInt(score);
    const scores = Object.keys(scoreToLevelMap);
    const minScore = scores[0];
    const maxScore = scores[scores.length - 1];

    if (integerScore < minScore) {
      return "";
    };

    if (score > maxScore) {
      return scoreToLevelMap[maxScore]
    } else if (score < minScore) {
      return scoreToLevelMap[minScore]
    }

    return scoreToLevelMap[integerScore]
  }
}


/***/ }),

/***/ "./src/components/ScoreContainer.svelte":
/*!**********************************************!*\
  !*** ./src/components/ScoreContainer.svelte ***!
  \**********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_ValueRange_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/ValueRange.svelte */ "./src/components/ValueRange.svelte");
/* src/components/ScoreContainer.svelte generated by Svelte v3.7.1 */



const file = "src/components/ScoreContainer.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-jjchhl-style';
	style.textContent = ".container.svelte-jjchhl{margin:1em 0}.label.svelte-jjchhl{margin:0;color:#34495e}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2NvcmVDb250YWluZXIuc3ZlbHRlIiwic291cmNlcyI6WyJTY29yZUNvbnRhaW5lci5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN0eWxlIGxhbmc9XCJzY3NzXCI+LmNvbnRhaW5lciB7XG4gIG1hcmdpbjogMWVtIDA7IH1cblxuLmxhYmVsIHtcbiAgbWFyZ2luOiAwO1xuICBjb2xvcjogIzM0NDk1ZTsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1TY29yZUNvbnRhaW5lci5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzY3JpcHQ+XG4gIGltcG9ydCBWYWx1ZVJhbmdlIGZyb20gXCIuLi9jb21wb25lbnRzL1ZhbHVlUmFuZ2Uuc3ZlbHRlXCI7XG5cbiAgZXhwb3J0IGxldCB0aXRsZTtcbiAgZXhwb3J0IGxldCBzdWJ0aXRsZSA9IFwiXCI7XG4gIGV4cG9ydCBsZXQgdmFsdWU7XG4gIGV4cG9ydCBsZXQgbGVmdFZhbHVlO1xuICBleHBvcnQgbGV0IHJpZ2h0VmFsdWU7XG4gIGV4cG9ydCBsZXQgcmV2ZXJzZSA9IHVuZGVmaW5lZDtcblxuICAkOiB2YWx1ZVJhbmdlUHJvcHMgPSB7XG4gICAgdmFsdWUsXG4gICAgbGVmdFZhbHVlLFxuICAgIHJpZ2h0VmFsdWUsXG4gICAgcmV2ZXJzZSxcbiAgfTtcbjwvc2NyaXB0PlxuXG48ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gIDxwIGNsYXNzPVwibGFiZWxcIj5cbiAgICA8c21hbGw+e3RpdGxlfTo8L3NtYWxsPlxuICAgIHt2YWx1ZSAmJiB2YWx1ZS50b0ZpeGVkKDIpfVxuXG4gICAgeyNpZiBzdWJ0aXRsZX1cbiAgICAgIDxici8+XG4gICAgICA8c21hbGwgY2xhc3M9XCJsYWJlbFwiPntzdWJ0aXRsZX08L3NtYWxsPlxuICAgIHsvaWZ9XG4gIDwvcD5cbiAgPFZhbHVlUmFuZ2Ugey4uLnZhbHVlUmFuZ2VQcm9wc30gLz5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFtQixVQUFVLGNBQUMsQ0FBQyxBQUM3QixNQUFNLENBQUUsR0FBRyxDQUFDLENBQUMsQUFBRSxDQUFDLEFBRWxCLE1BQU0sY0FBQyxDQUFDLEFBQ04sTUFBTSxDQUFFLENBQUMsQ0FDVCxLQUFLLENBQUUsT0FBTyxBQUFFLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

// (33:4) {#if subtitle}
function create_if_block(ctx) {
	var br, t0, small, t1;

	return {
		c: function create() {
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			small = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.subtitle);
			this.h()
		},

		l: function claim(nodes) {
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "BR", {}, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n      ");

			small = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SMALL", { class: true }, false);
			var small_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small_nodes, ctx.subtitle);
			small_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 33, 6, 606);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small, "class", "label svelte-jjchhl");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small, file, 34, 6, 618);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, br, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, small, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(small, t1);
		},

		p: function update(changed, ctx) {
			if (changed.subtitle) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, ctx.subtitle);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(br);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(small);
			}
		}
	};
}

function create_fragment(ctx) {
	var div, p, small, t0, t1, t2, t3_value = ctx.value && ctx.value.toFixed(2), t3, t4, t5, current;

	var if_block = (ctx.subtitle) && create_if_block(ctx);

	var valuerange_spread_levels = [
		ctx.valueRangeProps
	];

	let valuerange_props = {};
	for (var i = 0; i < valuerange_spread_levels.length; i += 1) {
		valuerange_props = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["assign"])(valuerange_props, valuerange_spread_levels[i]);
	}
	var valuerange = new _components_ValueRange_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ props: valuerange_props, $$inline: true });

	return {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			small = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.title);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block) if_block.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			valuerange.$$.fragment.c();
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			small = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "SMALL", {}, false);
			var small_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small_nodes, ctx.title);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small_nodes, ":");
			small_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, "\n    ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, "\n\n    ");
			if (if_block) if_block.l(p_nodes);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n  ");
			valuerange.$$.fragment.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small, file, 29, 4, 524);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p, "class", "label svelte-jjchhl");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 28, 2, 502);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", "container svelte-jjchhl");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 27, 0, 476);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, small);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(small, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(small, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, t4);
			if (if_block) if_block.m(p, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(valuerange, div, null);
			current = true;
		},

		p: function update(changed, ctx) {
			if (!current || changed.title) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, ctx.title);
			}

			if ((!current || changed.value) && t3_value !== (t3_value = ctx.value && ctx.value.toFixed(2))) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t3, t3_value);
			}

			if (ctx.subtitle) {
				if (if_block) {
					if_block.p(changed, ctx);
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					if_block.m(p, null);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}

			var valuerange_changes = changed.valueRangeProps ? Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["get_spread_update"])(valuerange_spread_levels, [
				ctx.valueRangeProps
			]) : {};
			valuerange.$set(valuerange_changes);
		},

		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(valuerange.$$.fragment, local);

			current = true;
		},

		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(valuerange.$$.fragment, local);
			current = false;
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
			}

			if (if_block) if_block.d();

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(valuerange);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { title, subtitle = "", value, leftValue, rightValue, reverse = undefined } = $$props;

	const writable_props = ['title', 'subtitle', 'value', 'leftValue', 'rightValue', 'reverse'];
	Object.keys($$props).forEach(key => {
		if (!writable_props.includes(key) && !key.startsWith('$$')) console.warn(`<ScoreContainer> was created with unknown prop '${key}'`);
	});

	$$self.$set = $$props => {
		if ('title' in $$props) $$invalidate('title', title = $$props.title);
		if ('subtitle' in $$props) $$invalidate('subtitle', subtitle = $$props.subtitle);
		if ('value' in $$props) $$invalidate('value', value = $$props.value);
		if ('leftValue' in $$props) $$invalidate('leftValue', leftValue = $$props.leftValue);
		if ('rightValue' in $$props) $$invalidate('rightValue', rightValue = $$props.rightValue);
		if ('reverse' in $$props) $$invalidate('reverse', reverse = $$props.reverse);
	};

	let valueRangeProps;

	$$self.$$.update = ($$dirty = { value: 1, leftValue: 1, rightValue: 1, reverse: 1 }) => {
		if ($$dirty.value || $$dirty.leftValue || $$dirty.rightValue || $$dirty.reverse) { $$invalidate('valueRangeProps', valueRangeProps = {
        value,
        leftValue,
        rightValue,
        reverse,
      }); }
	};

	return {
		title,
		subtitle,
		value,
		leftValue,
		rightValue,
		reverse,
		valueRangeProps
	};
}

class ScoreContainer extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-jjchhl-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], ["title", "subtitle", "value", "leftValue", "rightValue", "reverse"]);

		const { ctx } = this.$$;
		const props = options.props || {};
		if (ctx.title === undefined && !('title' in props)) {
			console.warn("<ScoreContainer> was created without expected prop 'title'");
		}
		if (ctx.value === undefined && !('value' in props)) {
			console.warn("<ScoreContainer> was created without expected prop 'value'");
		}
		if (ctx.leftValue === undefined && !('leftValue' in props)) {
			console.warn("<ScoreContainer> was created without expected prop 'leftValue'");
		}
		if (ctx.rightValue === undefined && !('rightValue' in props)) {
			console.warn("<ScoreContainer> was created without expected prop 'rightValue'");
		}
	}

	get title() {
		throw new Error("<ScoreContainer>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set title(value) {
		throw new Error("<ScoreContainer>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get subtitle() {
		throw new Error("<ScoreContainer>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set subtitle(value) {
		throw new Error("<ScoreContainer>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get value() {
		throw new Error("<ScoreContainer>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set value(value) {
		throw new Error("<ScoreContainer>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get leftValue() {
		throw new Error("<ScoreContainer>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set leftValue(value) {
		throw new Error("<ScoreContainer>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get rightValue() {
		throw new Error("<ScoreContainer>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set rightValue(value) {
		throw new Error("<ScoreContainer>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get reverse() {
		throw new Error("<ScoreContainer>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set reverse(value) {
		throw new Error("<ScoreContainer>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (ScoreContainer);

/***/ }),

/***/ "./src/components/ValueRange.svelte":
/*!******************************************!*\
  !*** ./src/components/ValueRange.svelte ***!
  \******************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var svelte_motion__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte/motion */ "./node_modules/svelte/motion/index.mjs");
/* harmony import */ var svelte_easing__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! svelte/easing */ "./node_modules/svelte/easing/index.mjs");
/* harmony import */ var _helpers_createRGBValue__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../helpers/createRGBValue */ "./src/helpers/createRGBValue.js");
/* src/components/ValueRange.svelte generated by Svelte v3.7.1 */

const { document: document_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];





const file = "src/components/ValueRange.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1iazmd3-style';
	style.textContent = ".container.svelte-1iazmd3{text-align:center;width:100%}.valueContainer.svelte-1iazmd3{position:relative;width:50%;margin:0 auto;display:flex;align-items:center;height:1.5em}@media(max-width: 768px){.valueContainer.svelte-1iazmd3{width:100%}}.range.svelte-1iazmd3{height:2px;left:0;right:0;top:50%;transform:translateY(-50%);background-color:#ecf0f1;flex:1}.minValue.svelte-1iazmd3{left:0;transform:translate(-100%, -50%);position:absolute;top:50%;width:1px;height:1.5em;background-color:#34495e;border-radius:100px}.maxValue.svelte-1iazmd3{right:0;transform:translate(100%, -50%);position:absolute;top:50%;width:1px;height:1.5em;background-color:#34495e;border-radius:100px}.currentValue.svelte-1iazmd3{position:absolute;background-color:#34495e;width:3vw;height:3vw;max-width:1em;max-height:1em;border-radius:1000px;left:43%;top:50%;transform:translateY(-50%)}.limitLabel.svelte-1iazmd3{bottom:-100%;position:absolute;left:50%;transform:translateX(-50%)}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVmFsdWVSYW5nZS5zdmVsdGUiLCJzb3VyY2VzIjpbIlZhbHVlUmFuZ2Uuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzdHlsZSBsYW5nPVwic2Nzc1wiPi5jb250YWluZXIge1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIHdpZHRoOiAxMDAlOyB9XG5cbi52YWx1ZUNvbnRhaW5lciB7XG4gIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgd2lkdGg6IDUwJTtcbiAgbWFyZ2luOiAwIGF1dG87XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGhlaWdodDogMS41ZW07IH1cbiAgQG1lZGlhIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gICAgLnZhbHVlQ29udGFpbmVyIHtcbiAgICAgIHdpZHRoOiAxMDAlOyB9IH1cblxuLnJhbmdlIHtcbiAgaGVpZ2h0OiAycHg7XG4gIGxlZnQ6IDA7XG4gIHJpZ2h0OiAwO1xuICB0b3A6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC01MCUpO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZWNmMGYxO1xuICBmbGV4OiAxOyB9XG5cbi5taW5WYWx1ZSB7XG4gIGxlZnQ6IDA7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlKC0xMDAlLCAtNTAlKTtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICB0b3A6IDUwJTtcbiAgd2lkdGg6IDFweDtcbiAgaGVpZ2h0OiAxLjVlbTtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzM0NDk1ZTtcbiAgYm9yZGVyLXJhZGl1czogMTAwcHg7IH1cblxuLm1heFZhbHVlIHtcbiAgcmlnaHQ6IDA7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlKDEwMCUsIC01MCUpO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHRvcDogNTAlO1xuICB3aWR0aDogMXB4O1xuICBoZWlnaHQ6IDEuNWVtO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMzQ0OTVlO1xuICBib3JkZXItcmFkaXVzOiAxMDBweDsgfVxuXG4uY3VycmVudFZhbHVlIHtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMzQ0OTVlO1xuICB3aWR0aDogM3Z3O1xuICBoZWlnaHQ6IDN2dztcbiAgbWF4LXdpZHRoOiAxZW07XG4gIG1heC1oZWlnaHQ6IDFlbTtcbiAgYm9yZGVyLXJhZGl1czogMTAwMHB4O1xuICBsZWZ0OiA0MyU7XG4gIHRvcDogNTAlO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7IH1cblxuLmxpbWl0TGFiZWwge1xuICBib3R0b206IC0xMDAlO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIGxlZnQ6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC01MCUpOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPVZhbHVlUmFuZ2Uuc3ZlbHRlLmNzcy5tYXAgKi88L3N0eWxlPlxuXG48c2NyaXB0PlxuICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJztcbiAgaW1wb3J0IHsgdHdlZW5lZCB9IGZyb20gJ3N2ZWx0ZS9tb3Rpb24nO1xuICBpbXBvcnQgeyBjdWJpY091dCB9IGZyb20gJ3N2ZWx0ZS9lYXNpbmcnO1xuICBpbXBvcnQgeyBjcmVhdGVSR0JWYWx1ZSB9IGZyb20gXCIuLi9oZWxwZXJzL2NyZWF0ZVJHQlZhbHVlXCI7XG5cbiAgZXhwb3J0IGxldCBsZWZ0VmFsdWU7XG4gIGV4cG9ydCBsZXQgcmlnaHRWYWx1ZTtcbiAgZXhwb3J0IGxldCB2YWx1ZTtcbiAgZXhwb3J0IGxldCByZXZlcnNlID0gZmFsc2U7XG5cbiAgbGV0IGN1cnJlbnRFbGVtZW50V2lkdGggPSAwO1xuICBjb25zdCBjb2xvcnMgPSBbXG4gICAgeyByZWQ6IDQ2LCBncmVlbjogMjA0LCBibHVlOiAxMTMsIH0sXG4gICAgeyByZWQ6IDI0MywgZ3JlZW46IDE1NiwgYmx1ZTogMTgsIH0sXG4gICAgeyByZWQ6IDIzMSwgZ3JlZW46IDc2LCBibHVlOiA2MCwgfSxcbiAgXTtcbiAgY29uc3QgcHJvZ3Jlc3MgPSB0d2VlbmVkKDAsIHsgZHVyYXRpb246IDMwMCwgZWFzaW5nOiBjdWJpY091dCB9KTtcbiAgY29uc3Qgc2V0Q3VycmVudEVsZW1lbnRXaWR0aCA9ICgpID0+IHtcbiAgICBjdXJyZW50RWxlbWVudFdpZHRoID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIi5jdXJyZW50VmFsdWVcIikuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCkud2lkdGg7XG4gIH07XG5cbiAgJDogcHJvZ3Jlc3Muc2V0KHZhbHVlIC8gTWF0aC5tYXgocmlnaHRWYWx1ZSwgbGVmdFZhbHVlKSk7XG4gICQ6IGN1cnJlbnRWYWx1ZUVsZW1lbnRXaWR0aEhhc1RvQmVTdWJ0cmFjdGVkID0gKHJldmVyc2UgPyAkcHJvZ3Jlc3MgPCAwLjUgOiAkcHJvZ3Jlc3MgPiAwLjUpO1xuICAkOiBzdWJ0cmFjdFZhbHVlVG9QcmV2ZW50T3ZlcmZsb3cgPSBgJHtjdXJyZW50VmFsdWVFbGVtZW50V2lkdGhIYXNUb0JlU3VidHJhY3RlZCA/IGN1cnJlbnRFbGVtZW50V2lkdGggOiAwfXB4YDtcbiAgJDogY29sb3IgPSBjcmVhdGVSR0JWYWx1ZShyZXZlcnNlID8gMSAtICRwcm9ncmVzcyA6ICRwcm9ncmVzcywgY29sb3JzKTtcbiAgJDogcmdiID0gYHJnYigke2NvbG9yLnJlZH0sICR7Y29sb3IuZ3JlZW59LCAke2NvbG9yLmJsdWV9KWA7XG4gICQ6IGN1cnJlbnRWYWx1ZVN0eWxlID0gYGJhY2tncm91bmQtY29sb3I6ICR7cmdifTsgbGVmdDogY2FsYygke3JldmVyc2UgPyBcIjEwMCUgLSBcIiA6IFwiXCJ9JHskcHJvZ3Jlc3MgKiAxMDB9JSAtICR7c3VidHJhY3RWYWx1ZVRvUHJldmVudE92ZXJmbG93fSk7YDtcblxuICBvbk1vdW50KHNldEN1cnJlbnRFbGVtZW50V2lkdGgpO1xuPC9zY3JpcHQ+XG5cbjxzdmVsdGU6d2luZG93IG9uOnJlc2l6ZT17c2V0Q3VycmVudEVsZW1lbnRXaWR0aH0gLz5cblxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICA8ZGl2IGNsYXNzPVwidmFsdWVDb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwicmFuZ2VcIiAvPlxuICAgIDxkaXYgY2xhc3M9XCJtaW5WYWx1ZVwiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJsaW1pdExhYmVsXCI+e2xlZnRWYWx1ZX08L3NwYW4+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cIm1heFZhbHVlXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cImxpbWl0TGFiZWxcIj57cmlnaHRWYWx1ZX08L3NwYW4+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cImN1cnJlbnRWYWx1ZVwiIHN0eWxlPXtjdXJyZW50VmFsdWVTdHlsZX0gLz5cbiAgPC9kaXY+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBbUIsVUFBVSxlQUFDLENBQUMsQUFDN0IsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsS0FBSyxDQUFFLElBQUksQUFBRSxDQUFDLEFBRWhCLGVBQWUsZUFBQyxDQUFDLEFBQ2YsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsS0FBSyxDQUFFLEdBQUcsQ0FDVixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQ0FDZCxPQUFPLENBQUUsSUFBSSxDQUNiLFdBQVcsQ0FBRSxNQUFNLENBQ25CLE1BQU0sQ0FBRSxLQUFLLEFBQUUsQ0FBQyxBQUNoQixNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLGVBQWUsZUFBQyxDQUFDLEFBQ2YsS0FBSyxDQUFFLElBQUksQUFBRSxDQUFDLEFBQUMsQ0FBQyxBQUV0QixNQUFNLGVBQUMsQ0FBQyxBQUNOLE1BQU0sQ0FBRSxHQUFHLENBQ1gsSUFBSSxDQUFFLENBQUMsQ0FDUCxLQUFLLENBQUUsQ0FBQyxDQUNSLEdBQUcsQ0FBRSxHQUFHLENBQ1IsU0FBUyxDQUFFLFdBQVcsSUFBSSxDQUFDLENBQzNCLGdCQUFnQixDQUFFLE9BQU8sQ0FDekIsSUFBSSxDQUFFLENBQUMsQUFBRSxDQUFDLEFBRVosU0FBUyxlQUFDLENBQUMsQUFDVCxJQUFJLENBQUUsQ0FBQyxDQUNQLFNBQVMsQ0FBRSxVQUFVLEtBQUssQ0FBQyxDQUFDLElBQUksQ0FBQyxDQUNqQyxRQUFRLENBQUUsUUFBUSxDQUNsQixHQUFHLENBQUUsR0FBRyxDQUNSLEtBQUssQ0FBRSxHQUFHLENBQ1YsTUFBTSxDQUFFLEtBQUssQ0FDYixnQkFBZ0IsQ0FBRSxPQUFPLENBQ3pCLGFBQWEsQ0FBRSxLQUFLLEFBQUUsQ0FBQyxBQUV6QixTQUFTLGVBQUMsQ0FBQyxBQUNULEtBQUssQ0FBRSxDQUFDLENBQ1IsU0FBUyxDQUFFLFVBQVUsSUFBSSxDQUFDLENBQUMsSUFBSSxDQUFDLENBQ2hDLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLEdBQUcsQ0FBRSxHQUFHLENBQ1IsS0FBSyxDQUFFLEdBQUcsQ0FDVixNQUFNLENBQUUsS0FBSyxDQUNiLGdCQUFnQixDQUFFLE9BQU8sQ0FDekIsYUFBYSxDQUFFLEtBQUssQUFBRSxDQUFDLEFBRXpCLGFBQWEsZUFBQyxDQUFDLEFBQ2IsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsZ0JBQWdCLENBQUUsT0FBTyxDQUN6QixLQUFLLENBQUUsR0FBRyxDQUNWLE1BQU0sQ0FBRSxHQUFHLENBQ1gsU0FBUyxDQUFFLEdBQUcsQ0FDZCxVQUFVLENBQUUsR0FBRyxDQUNmLGFBQWEsQ0FBRSxNQUFNLENBQ3JCLElBQUksQ0FBRSxHQUFHLENBQ1QsR0FBRyxDQUFFLEdBQUcsQ0FDUixTQUFTLENBQUUsV0FBVyxJQUFJLENBQUMsQUFBRSxDQUFDLEFBRWhDLFdBQVcsZUFBQyxDQUFDLEFBQ1gsTUFBTSxDQUFFLEtBQUssQ0FDYixRQUFRLENBQUUsUUFBUSxDQUNsQixJQUFJLENBQUUsR0FBRyxDQUNULFNBQVMsQ0FBRSxXQUFXLElBQUksQ0FBQyxBQUFFLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document_1.head, style);
}

function create_fragment(ctx) {
	var div5, div4, div0, t0, div1, span0, t1, t2, div2, span1, t3, t4, div3, dispose;

	return {
		c: function create() {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.leftValue);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.rightValue);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			this.h()
		},

		l: function claim(nodes) {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ctx.leftValue);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, ctx.rightValue);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true, style: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "range svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 100, 4, 2551);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "limitLabel svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 102, 6, 2606);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div1, "class", "minValue svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 101, 4, 2577);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "limitLabel svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 105, 6, 2694);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div2, "class", "maxValue svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 104, 4, 2665);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "class", "currentValue svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "style", ctx.currentValueStyle);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 107, 4, 2754);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div4, "class", "valueContainer svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 99, 2, 2518);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div5, "class", "container svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 98, 0, 2492);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(window, "resize", ctx.setCurrentElementWidth);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div5, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div3);
		},

		p: function update(changed, ctx) {
			if (changed.leftValue) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, ctx.leftValue);
			}

			if (changed.rightValue) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t3, ctx.rightValue);
			}

			if (changed.currentValueStyle) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "style", ctx.currentValueStyle);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div5);
			}

			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $progress;

	

  let { leftValue, rightValue, value, reverse = false } = $$props;

  let currentElementWidth = 0;
  const colors = [
    { red: 46, green: 204, blue: 113, },
    { red: 243, green: 156, blue: 18, },
    { red: 231, green: 76, blue: 60, },
  ];
  const progress = Object(svelte_motion__WEBPACK_IMPORTED_MODULE_2__["tweened"])(0, { duration: 300, easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["cubicOut"] }); Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(progress, 'progress'); Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, progress, $$value => { $progress = $$value; $$invalidate('$progress', $progress) });
  const setCurrentElementWidth = () => {
    $$invalidate('currentElementWidth', currentElementWidth = document.querySelector(".currentValue").getBoundingClientRect().width);
  };

  Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(setCurrentElementWidth);

	const writable_props = ['leftValue', 'rightValue', 'value', 'reverse'];
	Object.keys($$props).forEach(key => {
		if (!writable_props.includes(key) && !key.startsWith('$$')) console.warn(`<ValueRange> was created with unknown prop '${key}'`);
	});

	$$self.$set = $$props => {
		if ('leftValue' in $$props) $$invalidate('leftValue', leftValue = $$props.leftValue);
		if ('rightValue' in $$props) $$invalidate('rightValue', rightValue = $$props.rightValue);
		if ('value' in $$props) $$invalidate('value', value = $$props.value);
		if ('reverse' in $$props) $$invalidate('reverse', reverse = $$props.reverse);
	};

	let currentValueElementWidthHasToBeSubtracted, subtractValueToPreventOverflow, color, rgb, currentValueStyle;

	$$self.$$.update = ($$dirty = { value: 1, rightValue: 1, leftValue: 1, reverse: 1, $progress: 1, currentValueElementWidthHasToBeSubtracted: 1, currentElementWidth: 1, color: 1, rgb: 1, subtractValueToPreventOverflow: 1 }) => {
		if ($$dirty.value || $$dirty.rightValue || $$dirty.leftValue) { progress.set(value / Math.max(rightValue, leftValue)); }
		if ($$dirty.reverse || $$dirty.$progress) { $$invalidate('currentValueElementWidthHasToBeSubtracted', currentValueElementWidthHasToBeSubtracted = (reverse ? $progress < 0.5 : $progress > 0.5)); }
		if ($$dirty.currentValueElementWidthHasToBeSubtracted || $$dirty.currentElementWidth) { $$invalidate('subtractValueToPreventOverflow', subtractValueToPreventOverflow = `${currentValueElementWidthHasToBeSubtracted ? currentElementWidth : 0}px`); }
		if ($$dirty.reverse || $$dirty.$progress) { $$invalidate('color', color = Object(_helpers_createRGBValue__WEBPACK_IMPORTED_MODULE_4__["createRGBValue"])(reverse ? 1 - $progress : $progress, colors)); }
		if ($$dirty.color) { $$invalidate('rgb', rgb = `rgb(${color.red}, ${color.green}, ${color.blue})`); }
		if ($$dirty.rgb || $$dirty.reverse || $$dirty.$progress || $$dirty.subtractValueToPreventOverflow) { $$invalidate('currentValueStyle', currentValueStyle = `background-color: ${rgb}; left: calc(${reverse ? "100% - " : ""}${$progress * 100}% - ${subtractValueToPreventOverflow});`); }
	};

	return {
		leftValue,
		rightValue,
		value,
		reverse,
		progress,
		setCurrentElementWidth,
		currentValueStyle
	};
}

class ValueRange extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document_1.getElementById("svelte-1iazmd3-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], ["leftValue", "rightValue", "value", "reverse"]);

		const { ctx } = this.$$;
		const props = options.props || {};
		if (ctx.leftValue === undefined && !('leftValue' in props)) {
			console.warn("<ValueRange> was created without expected prop 'leftValue'");
		}
		if (ctx.rightValue === undefined && !('rightValue' in props)) {
			console.warn("<ValueRange> was created without expected prop 'rightValue'");
		}
		if (ctx.value === undefined && !('value' in props)) {
			console.warn("<ValueRange> was created without expected prop 'value'");
		}
	}

	get leftValue() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set leftValue(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get rightValue() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set rightValue(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get value() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set value(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get reverse() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set reverse(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (ValueRange);

/***/ }),

/***/ "./src/helpers/createRGBValue.js":
/*!***************************************!*\
  !*** ./src/helpers/createRGBValue.js ***!
  \***************************************/
/*! exports provided: createRGBValue */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "createRGBValue", function() { return createRGBValue; });
function interpolate(value, min, max) {
  var delta = max - min;
  var stepValue = delta / 100;
  return min + stepValue * Math.floor(value * 100);
}

/**
 * Create an RGB value located between 3 colors
 *
 * @param {number} value - Value between 0 and 1
 * @param {{ red: number; green: number; blue: number; }[]} colors - Array of rgb colors
 */
function createRGBValue(value, colors) {
  let red;
  let green;
  let blue;

  const [
    startColor,
    midColor,
    endColor,
  ] = colors;

  if (value > 0.5) {
    red = interpolate((value - 0.5) / 0.5, midColor.red, endColor.red);
  } else {
    red = interpolate(value / 0.5, startColor.red, midColor.red);
  }

  if (value > 0.5) {
    green = interpolate((value - 0.5) / 0.5, midColor.green, endColor.green);
  } else {
    green = interpolate(value / 0.5, startColor.green, midColor.green);
  }

  if (value > 0.5) {
    blue = interpolate((value - 0.5) / 0.5, midColor.blue, endColor.blue);
  } else {
    blue = interpolate(value / 0.5, startColor.blue, midColor.blue);
  }

  return {
    red,
    green,
    blue,
  };
}


/***/ }),

/***/ "./src/helpers/writtenLanguageHelpers.js":
/*!***********************************************!*\
  !*** ./src/helpers/writtenLanguageHelpers.js ***!
  \***********************************************/
/*! exports provided: countWords, findWords, countSentences, countHardWords, countSyllables */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countWords", function() { return countWords; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "findWords", function() { return findWords; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countSentences", function() { return countSentences; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countHardWords", function() { return countHardWords; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countSyllables", function() { return countSyllables; });
/* harmony import */ var syllable__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! syllable */ "./node_modules/syllable/index.js");
/* harmony import */ var syllable__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(syllable__WEBPACK_IMPORTED_MODULE_0__);


function countWords(text) {
  return findWords(text).length || 1;
}

function findWords(text) {
  return text.match(/([^\u0000-\u007F]|\w)+/g) || [];
}

function countSentences(text) {
  const match = text.match(/[\w]\)?[.?!](\s|$)/g) || [];
  return match.length || 1;
}

function countHardWords(text) {
  const textLower = text.toLowerCase();
  let count = 0;

  findWords(textLower).forEach(word => {
    if (countWordSyllables(word) >= 3) {
      count += 1;
    }
  })

  return count;
}

function countSyllables(text) {
  const textLower = text.toLowerCase();
  let count = 0;

  findWords(textLower).forEach(word=> {
    count += countWordSyllables(word);
  })

  return count

}

function countWordSyllables(originalWord) {
  return syllable__WEBPACK_IMPORTED_MODULE_0___default()(originalWord)
}


/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_FormGroup_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/FormGroup.svelte */ "./src/components/FormGroup.svelte");
/* harmony import */ var _components_ValueRange_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/ValueRange.svelte */ "./src/components/ValueRange.svelte");
/* harmony import */ var _components_ScoreContainer_svelte__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/ScoreContainer.svelte */ "./src/components/ScoreContainer.svelte");
/* harmony import */ var _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../components/FleschKincaidScorer.js */ "./src/components/FleschKincaidScorer.js");
/* harmony import */ var _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../components/GunningFlogScorer.js */ "./src/components/GunningFlogScorer.js");
/* src/routes/index.svelte generated by Svelte v3.7.1 */







const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-9ooowb-style';
	style.textContent = ".svelte-9ooowb{font-family:\"Montserrat\", sans-serif}input,textarea{box-shadow:0 0 0.5em rgba(0, 0, 0, 0.1);-webkit-appearance:none;border:0;font-family:inherit;font-size:inherit}.container.svelte-9ooowb{display:flex;flex-direction:column;text-align:center}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN0eWxlIGxhbmc9XCJzY3NzXCI+KiB7XG4gIGZvbnQtZmFtaWx5OiBcIk1vbnRzZXJyYXRcIiwgc2Fucy1zZXJpZjsgfVxuXG46Z2xvYmFsKGlucHV0KSxcbjpnbG9iYWwodGV4dGFyZWEpIHtcbiAgYm94LXNoYWRvdzogMCAwIDAuNWVtIHJnYmEoMCwgMCwgMCwgMC4xKTtcbiAgLXdlYmtpdC1hcHBlYXJhbmNlOiBub25lO1xuICBib3JkZXI6IDA7XG4gIGZvbnQtZmFtaWx5OiBpbmhlcml0O1xuICBmb250LXNpemU6IGluaGVyaXQ7IH1cblxuLmNvbnRhaW5lciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gIHRleHQtYWxpZ246IGNlbnRlcjsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzY3JpcHQ+XG4gIGltcG9ydCBGb3JtR3JvdXAgZnJvbSBcIi4uL2NvbXBvbmVudHMvRm9ybUdyb3VwLnN2ZWx0ZVwiO1xuICBpbXBvcnQgVmFsdWVSYW5nZSBmcm9tIFwiLi4vY29tcG9uZW50cy9WYWx1ZVJhbmdlLnN2ZWx0ZVwiO1xuICBpbXBvcnQgU2NvcmVDb250YWluZXIgZnJvbSBcIi4uL2NvbXBvbmVudHMvU2NvcmVDb250YWluZXIuc3ZlbHRlXCI7XG5cbiAgaW1wb3J0IHtcbiAgICBGbGVzY2hLaW5jYWlkU2NvcmVyLFxuICAgIE1BWF9GTEVTQ19LSU5DQUlELFxuICAgIE1JTl9GTEVTQ19LSU5DQUlELFxuICB9IGZyb20gXCIuLi9jb21wb25lbnRzL0ZsZXNjaEtpbmNhaWRTY29yZXIuanNcIjtcbiAgaW1wb3J0IHtcbiAgICBHdW5uaW5nRmxvZ1Njb3JlcixcbiAgICBNQVhfR1VOTklOR19GTE9HLFxuICAgIE1JTl9HVU5OSU5HX0ZMT0csXG4gIH0gZnJvbSBcIi4uL2NvbXBvbmVudHMvR3VubmluZ0Zsb2dTY29yZXIuanNcIjtcblxuICBsZXQgc3ViamVjdFRleHQgPSBcIlwiO1xuICAkOiBmbGVzY2hLaW5jYWlkU2NvcmUgPSBGbGVzY2hLaW5jYWlkU2NvcmVyLmNhbGN1bGF0ZShzdWJqZWN0VGV4dCk7XG4gICQ6IGd1bm5pbmdGbG9nU2NvcmUgPSBHdW5uaW5nRmxvZ1Njb3Jlci5jYWxjdWxhdGUoc3ViamVjdFRleHQpO1xuPC9zY3JpcHQ+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlRleHQgU2NvcmU8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICA8aDE+SG93IHJlYWRhYmxlIGlzIHlvdXIgdGV4dD88L2gxPlxuICA8c21hbGw+PC9zbWFsbD5cbiAgPGhyLz5cbiAgPEZvcm1Hcm91cFxuICAgIGlkPXtcInN1YmplY3RUZXh0XCJ9XG4gICAgYmluZDp2YWx1ZT17c3ViamVjdFRleHR9XG4gICAgcGxhY2Vob2xkZXI9XCJXcml0ZSB5b3VyIHRleHQgaGVyZSBhbmQgc2VlIHRoZSBzY29yZSBiZWluZyBjYWxjdWxhdGVkXCJcbiAgLz5cblxuICA8U2NvcmVDb250YWluZXJcbiAgICB0aXRsZT1cIkZsZXNjaCBLaW5jYWlkIFJlYWRpbmcgRWFzZVwiXG4gICAgdmFsdWU9e2ZsZXNjaEtpbmNhaWRTY29yZX1cbiAgICBsZWZ0VmFsdWU9e01BWF9GTEVTQ19LSU5DQUlEfVxuICAgIHJpZ2h0VmFsdWU9e01JTl9GTEVTQ19LSU5DQUlEfVxuICAgIHJldmVyc2U9e3RydWV9XG4gIC8+XG4gIDxTY29yZUNvbnRhaW5lclxuICAgIHRpdGxlPVwiR3VubmluZyBmb2cgaW5kZXhcIlxuICAgIHZhbHVlPXtndW5uaW5nRmxvZ1Njb3JlfVxuICAgIHN1YnRpdGxlPXtHdW5uaW5nRmxvZ1Njb3Jlci5zY29yaW5nTGV2ZWwoZ3VubmluZ0Zsb2dTY29yZSl9XG4gICAgbGVmdFZhbHVlPXtNSU5fR1VOTklOR19GTE9HfVxuICAgIHJpZ2h0VmFsdWU9e01BWF9HVU5OSU5HX0ZMT0d9XG4gIC8+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBbUIsY0FBRSxDQUFDLEFBQ3BCLFdBQVcsQ0FBRSxZQUFZLENBQUMsQ0FBQyxVQUFVLEFBQUUsQ0FBQyxBQUVsQyxLQUFLLEFBQUMsQ0FDTixRQUFRLEFBQUUsQ0FBQyxBQUNqQixVQUFVLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FDeEMsa0JBQWtCLENBQUUsSUFBSSxDQUN4QixNQUFNLENBQUUsQ0FBQyxDQUNULFdBQVcsQ0FBRSxPQUFPLENBQ3BCLFNBQVMsQ0FBRSxPQUFPLEFBQUUsQ0FBQyxBQUV2QixVQUFVLGNBQUMsQ0FBQyxBQUNWLE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLE1BQU0sQ0FDdEIsVUFBVSxDQUFFLE1BQU0sQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div, h1, t1, t2, small, t3, hr, t4, updating_value, t5, t6, current;

	function formgroup_value_binding(value) {
		ctx.formgroup_value_binding.call(null, value);
		updating_value = true;
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_value = false);
	}

	let formgroup_props = {
		id: "subjectText",
		placeholder: "Write your text here and see the score being calculated"
	};
	if (ctx.subjectText !== void 0) {
		formgroup_props.value = ctx.subjectText;
	}
	var formgroup = new _components_FormGroup_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ props: formgroup_props, $$inline: true });

	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(formgroup, 'value', formgroup_value_binding));

	var scorecontainer0 = new _components_ScoreContainer_svelte__WEBPACK_IMPORTED_MODULE_3__["default"]({
		props: {
		title: "Flesch Kincaid Reading Ease",
		value: ctx.fleschKincaidScore,
		leftValue: _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_4__["MAX_FLESC_KINCAID"],
		rightValue: _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_4__["MIN_FLESC_KINCAID"],
		reverse: true
	},
		$$inline: true
	});

	var scorecontainer1 = new _components_ScoreContainer_svelte__WEBPACK_IMPORTED_MODULE_3__["default"]({
		props: {
		title: "Gunning fog index",
		value: ctx.gunningFlogScore,
		subtitle: _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_5__["GunningFlogScorer"].scoringLevel(ctx.gunningFlogScore),
		leftValue: _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_5__["MIN_GUNNING_FLOG"],
		rightValue: _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_5__["MAX_GUNNING_FLOG"]
	},
		$$inline: true
	});

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("How readable is your text?");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			small = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			hr = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			formgroup.$$.fragment.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			scorecontainer0.$$.fragment.c();
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			scorecontainer1.$$.fragment.c();
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "How readable is your text?");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n  ");

			small = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "SMALL", { class: true }, false);
			var small_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small);

			small_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n  ");

			hr = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "HR", { class: true }, false);
			var hr_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(hr);

			hr_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n  ");
			formgroup.$$.fragment.l(div_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n\n  ");
			scorecontainer0.$$.fragment.l(div_nodes);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n  ");
			scorecontainer1.$$.fragment.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Text Score";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h1, "class", "svelte-9ooowb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 44, 2, 1080);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small, "class", "svelte-9ooowb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small, file, 45, 2, 1118);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(hr, "class", "svelte-9ooowb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr, file, 46, 2, 1136);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", "container svelte-9ooowb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 43, 0, 1054);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, small);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, hr);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(formgroup, div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(scorecontainer0, div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(scorecontainer1, div, null);
			current = true;
		},

		p: function update(changed, ctx) {
			var formgroup_changes = {};
			if (!updating_value && changed.subjectText) {
				formgroup_changes.value = ctx.subjectText;
			}
			formgroup.$set(formgroup_changes);

			var scorecontainer0_changes = {};
			if (changed.fleschKincaidScore) scorecontainer0_changes.value = ctx.fleschKincaidScore;
			if (changed.MAX_FLESC_KINCAID) scorecontainer0_changes.leftValue = _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_4__["MAX_FLESC_KINCAID"];
			if (changed.MIN_FLESC_KINCAID) scorecontainer0_changes.rightValue = _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_4__["MIN_FLESC_KINCAID"];
			scorecontainer0.$set(scorecontainer0_changes);

			var scorecontainer1_changes = {};
			if (changed.gunningFlogScore) scorecontainer1_changes.value = ctx.gunningFlogScore;
			if (changed.GunningFlogScorer || changed.gunningFlogScore) scorecontainer1_changes.subtitle = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_5__["GunningFlogScorer"].scoringLevel(ctx.gunningFlogScore);
			if (changed.MIN_GUNNING_FLOG) scorecontainer1_changes.leftValue = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_5__["MIN_GUNNING_FLOG"];
			if (changed.MAX_GUNNING_FLOG) scorecontainer1_changes.rightValue = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_5__["MAX_GUNNING_FLOG"];
			scorecontainer1.$set(scorecontainer1_changes);
		},

		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(formgroup.$$.fragment, local);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(scorecontainer0.$$.fragment, local);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(scorecontainer1.$$.fragment, local);

			current = true;
		},

		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(formgroup.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(scorecontainer0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(scorecontainer1.$$.fragment, local);
			current = false;
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(formgroup);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(scorecontainer0);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(scorecontainer1);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	

  let subjectText = "";

	function formgroup_value_binding(value) {
		subjectText = value;
		$$invalidate('subjectText', subjectText);
	}

	let fleschKincaidScore, gunningFlogScore;

	$$self.$$.update = ($$dirty = { subjectText: 1 }) => {
		if ($$dirty.subjectText) { $$invalidate('fleschKincaidScore', fleschKincaidScore = _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_4__["FleschKincaidScorer"].calculate(subjectText)); }
		if ($$dirty.subjectText) { $$invalidate('gunningFlogScore', gunningFlogScore = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_5__["GunningFlogScorer"].calculate(subjectText)); }
	};

	return {
		subjectText,
		fleschKincaidScore,
		gunningFlogScore,
		formgroup_value_binding
	};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-9ooowb-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9jb21wb25lbnRzL0ZsZXNjaEtpbmNhaWRTY29yZXIuanMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9Gb3JtR3JvdXAuc3ZlbHRlIiwid2VicGFjazovLy93ZWJwYWNrOi8vLy4vc3JjL2NvbXBvbmVudHMvR3VubmluZ0Zsb2dTY29yZXIuanMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9TY29yZUNvbnRhaW5lci5zdmVsdGUiLCJ3ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9WYWx1ZVJhbmdlLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9oZWxwZXJzL2NyZWF0ZVJHQlZhbHVlLmpzIiwid2VicGFjazovLy93ZWJwYWNrOi8vLy4vc3JjL2hlbHBlcnMvd3JpdHRlbkxhbmd1YWdlSGVscGVycy5qcyIsIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9yb3V0ZXMvaW5kZXguc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBSTJDOztBQUVwQztBQUNBOztBQUVBO0FBQ1A7QUFDQTtBQUNBO0FBQ0E7O0FBRUEsa0JBQWtCLGtGQUFVO0FBQzVCLHdCQUF3QixzRkFBYztBQUN0QyxnQkFBZ0Isc0ZBQWM7QUFDOUI7O0FBRUE7QUFDQTtBQUNBLEtBQUs7QUFDTDtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0ZDUFEsRUFBRTs7OzZGQUlPLFdBQVc7a0dBQ04sV0FBVzs7Ozs7Ozs7Ozs7d0JBRmpCLEtBQUs7Ozs7MkNBQUwsS0FBSzs7O3FGQUhiLEVBQUU7Ozs7OEZBSU8sV0FBVzttR0FDTixXQUFXOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Q0FkeEIsTUFBSSxLQUFLLEdBQUcsRUFBRSxFQUNWLFFBQVEsR0FBRyxFQUFFLEVBQ2IsU0FBUyxHQUFHLEVBQUUsRUFDZCxFQUFFLEdBQUcsRUFBRSxFQUNQLFdBQVcsR0FBRyxjQUFFLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ2hCOUI7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUkyQzs7QUFFcEM7QUFDQTs7QUFFUDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVPO0FBQ1A7QUFDQTtBQUNBO0FBQ0E7O0FBRUEsa0JBQWtCLGtGQUFVO0FBQzVCLHdCQUF3QixzRkFBYztBQUN0Qyx1QkFBdUIsc0ZBQWM7QUFDckM7O0FBRUE7QUFDQTtBQUNBLEtBQUs7QUFDTDtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0EsS0FBSztBQUNMO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5RUM5QjRCLFFBQVE7Ozs7Ozs7Ozs7Ozs7OzRGQUFSLFFBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZFQUFSLFFBQVE7Ozs7Ozs7Ozs7Ozs7OzsrQ0FKL0IsS0FBSyxRQUFJLEtBQUssQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDOztxQkFFckIsUUFBUTs7O01BS0MsZUFBZTs7Ozs7Ozs7Ozs7Ozs7eUVBUnJCLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs0RkFBTCxLQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkVBQUwsS0FBSzs7O21FQUNaLEtBQUssUUFBSSxLQUFLLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQzs7OztXQUVyQixRQUFROzs7Ozs7Ozs7Ozs7OztRQUtDLGVBQWU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQXpCeEIsTUFBSSxLQUFLLEVBQ0wsUUFBUSxHQUFHLEVBQUUsRUFDYixLQUFLLEVBQ0wsU0FBUyxFQUNULFVBQVUsRUFDVixPQUFPLEdBQUcscUJBQVMsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxSEFFNUIsZUFBZSxHQUFHO0lBQ3ZCLElBQUksS0FBSztJQUNULElBQUksU0FBUztJQUNiLElBQUksVUFBVTtJQUNkLElBQUksT0FBTztJQUNYLElBQUcsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7eUVDOEU0QixTQUFTOzs7O3lFQUdULFVBQVU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NEZBSFYsU0FBUzs7Ozs7Ozs7Ozs7NEZBR1QsVUFBVTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7bUZBRUwsaUJBQWlCOzs7Ozs7a0dBWDVCLHNCQUFzQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZFQU1oQixTQUFTOzs7OzZFQUdULFVBQVU7Ozs7b0ZBRUwsaUJBQWlCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQXZDTzs7RUFFcEQsTUFBSSxTQUFTLEVBQ1QsVUFBVSxFQUNWLEtBQUssRUFDTCxPQUFPLEdBQUcsaUJBQUssQ0FBQzs7RUFFM0IsSUFBSSxtQkFBbUIsR0FBRyxDQUFDLENBQUM7RUFDNUIsTUFBTSxNQUFNLEdBQUc7SUFDYixFQUFFLEdBQUcsRUFBRSxFQUFFLEVBQUUsS0FBSyxFQUFFLEdBQUcsRUFBRSxJQUFJLEVBQUUsR0FBRyxHQUFHO0lBQ25DLEVBQUUsR0FBRyxFQUFFLEdBQUcsRUFBRSxLQUFLLEVBQUUsR0FBRyxFQUFFLElBQUksRUFBRSxFQUFFLEdBQUc7SUFDbkMsRUFBRSxHQUFHLEVBQUUsR0FBRyxFQUFFLEtBQUssRUFBRSxFQUFFLEVBQUUsSUFBSSxFQUFFLEVBQUUsR0FBRztHQUNuQyxDQUFDO0VBQ0YsTUFBTSxRQUFRLEdBQUcsNkRBQU8sQ0FBQyxDQUFDLEVBQUUsRUFBRSxRQUFRLEVBQUUsR0FBRyxFQUFFLE1BQU0sRUFBRSxzREFBUSxFQUFFLHdRQUFDLENBQUM7RUFDakUsTUFBTSxzQkFBc0IsR0FBRyxNQUFNO3dDQUNuQyxtQkFBbUIsR0FBRyxRQUFRLENBQUMsYUFBYSxDQUFDLGVBQWUsQ0FBQyxDQUFDLHFCQUFxQixFQUFFLENBQUMsTUFBSyxDQUFDO0dBQzdGLENBT2tKOztFQUVuSixzREFBTyxDQUFDLHNCQUFzQixDQUFDLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7O2tFQVA3QixRQUFRLENBQUMsR0FBRyxDQUFDLEtBQUssR0FBRyxJQUFJLENBQUMsR0FBRyxDQUFDLFVBQVUsRUFBRSxTQUFTLENBQUMsQ0FBQyxDQUFDO3dHQUN0RCx5Q0FBeUMsR0FBRyxDQUFDLE9BQU8sR0FBRyxTQUFTLEdBQUcsR0FBRyxHQUFHLFNBQVMsR0FBRyxHQUFHLEVBQUMsQ0FBQzt5SUFDMUYsOEJBQThCLEdBQUcsQ0FBQyxFQUFFLHlDQUF5QyxHQUFHLG1CQUFtQixHQUFHLENBQUMsQ0FBQyxFQUFFLEVBQUMsQ0FBQztvRUFDNUcsS0FBSyxHQUFHLDhFQUFjLENBQUMsT0FBTyxHQUFHLENBQUMsR0FBRyxTQUFTLEdBQUcsU0FBUyxFQUFFLE1BQU0sRUFBQyxDQUFDOzJDQUNwRSxHQUFHLEdBQUcsQ0FBQyxJQUFJLEVBQUUsS0FBSyxDQUFDLEdBQUcsQ0FBQyxFQUFFLEVBQUUsS0FBSyxDQUFDLEtBQUssQ0FBQyxFQUFFLEVBQUUsS0FBSyxDQUFDLElBQUksQ0FBQyxDQUFDLEVBQUMsQ0FBQzt5SUFDekQsaUJBQWlCLEdBQUcsQ0FBQyxrQkFBa0IsRUFBRSxHQUFHLENBQUMsYUFBYSxFQUFFLE9BQU8sR0FBRyxTQUFTLEdBQUcsRUFBRSxDQUFDLEVBQUUsU0FBUyxHQUFHLEdBQUcsQ0FBQyxJQUFJLEVBQUUsOEJBQThCLENBQUMsRUFBRSxFQUFDLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQzNGcko7QUFBQTtBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0EsV0FBVyxPQUFPO0FBQ2xCLFlBQVksYUFBYSxlQUFlLGNBQWMsRUFBRSxHQUFHO0FBQzNEO0FBQ087QUFDUDtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0EsR0FBRztBQUNIO0FBQ0E7O0FBRUE7QUFDQTtBQUNBLEdBQUc7QUFDSDtBQUNBOztBQUVBO0FBQ0E7QUFDQSxHQUFHO0FBQ0g7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Ozs7Ozs7Ozs7Ozs7QUM5Q0E7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFnQzs7QUFFekI7QUFDUDtBQUNBOztBQUVPO0FBQ1A7QUFDQTs7QUFFTztBQUNQO0FBQ0E7QUFDQTs7QUFFTztBQUNQO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQSxHQUFHOztBQUVIO0FBQ0E7O0FBRU87QUFDUDtBQUNBOztBQUVBO0FBQ0E7QUFDQSxHQUFHOztBQUVIOztBQUVBOztBQUVBO0FBQ0EsU0FBUywrQ0FBUTtBQUNqQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNNUSxhQUFhOzs7U0FDTCxXQUFXOzhCQUFYLFdBQVc7Ozs7Ozs7OzthQU1oQixrQkFBa0I7YUFDZCxvRkFBaUI7Y0FDaEIsb0ZBQWlCO1dBQ3BCLElBQUk7Ozs7Ozs7O2FBSU4sZ0JBQWdCO1lBQ2Isa0ZBQWlCLENBQUMsWUFBWSxLQUFDLGdCQUFnQixDQUFDO2FBQy9DLGlGQUFnQjtjQUNmLGlGQUFnQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tDQWhCaEIsV0FBVzs7Ozs7dUVBTWhCLGtCQUFrQjtzRUFDZCxvRkFBaUI7dUVBQ2hCLG9GQUFpQjs7OztxRUFLdEIsZ0JBQWdCO2lHQUNiLGtGQUFpQixDQUFDLFlBQVksS0FBQyxnQkFBZ0IsQ0FBQztxRUFDL0MsaUZBQWdCO3NFQUNmLGlGQUFnQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Q0FqQ2M7O0VBRTVDLElBQUksV0FBVyxHQUFHLEVBQUUsQ0FBQzs7Ozs7Ozs7OztnRUFDbEIsa0JBQWtCLEdBQUcsc0ZBQW1CLENBQUMsU0FBUyxDQUFDLFdBQVcsRUFBQyxDQUFDOzhEQUNoRSxnQkFBZ0IsR0FBRyxrRkFBaUIsQ0FBQyxTQUFTLENBQUMsV0FBVyxFQUFDLENBQUMiLCJmaWxlIjoiMWQwOTVhNzllNWI1ODI1YTRlMDEvaW5kZXguaW5kZXguanMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQge1xuICBjb3VudFNlbnRlbmNlcyxcbiAgY291bnRTeWxsYWJsZXMsXG4gIGNvdW50V29yZHMsXG59IGZyb20gXCIuLi9oZWxwZXJzL3dyaXR0ZW5MYW5ndWFnZUhlbHBlcnNcIjtcblxuZXhwb3J0IGNvbnN0IE1BWF9GTEVTQ19LSU5DQUlEID0gMTIwO1xuZXhwb3J0IGNvbnN0IE1JTl9GTEVTQ19LSU5DQUlEID0gMDtcblxuZXhwb3J0IGNsYXNzIEZsZXNjaEtpbmNhaWRTY29yZXIge1xuICBzdGF0aWMgY2FsY3VsYXRlKHRleHQpIHtcbiAgICBpZiAoIXRleHQpIHtcbiAgICAgIHJldHVybiBNQVhfRkxFU0NfS0lOQ0FJRDtcbiAgICB9XG5cbiAgICBjb25zdCB3b3JkcyA9IGNvdW50V29yZHModGV4dCk7XG4gICAgY29uc3QgYXNsID0gd29yZHMgLyBjb3VudFNlbnRlbmNlcyh0ZXh0KTtcbiAgICBjb25zdCBhc3cgPSBjb3VudFN5bGxhYmxlcyh0ZXh0KSAvIHdvcmRzO1xuICAgIGxldCBzY29yZSA9IDIwNi44MzUgLSAoMS4wMTUgKiBhc2wpIC0gKDg0LjYgKiBhc3cpO1xuXG4gICAgaWYgKHNjb3JlID4gTUFYX0ZMRVNDX0tJTkNBSUQpIHtcbiAgICAgIHNjb3JlID0gTUFYX0ZMRVNDX0tJTkNBSUQ7XG4gICAgfSBlbHNlIGlmKHNjb3JlIDwgTUlOX0ZMRVNDX0tJTkNBSUQpIHtcbiAgICAgIHNjb3JlID0gTUlOX0ZMRVNDX0tJTkNBSUQ7XG4gICAgfVxuXG4gICAgcmV0dXJuIHNjb3JlO1xuICB9XG59XG4iLCI8c3R5bGUgbGFuZz1cInNjc3NcIj4uZm9ybS1ncm91cCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IH1cblxuLmZvcm0taW5wdXQge1xuICBwYWRkaW5nOiAwLjVlbTtcbiAgd2lkdGg6IDEwMCUgIWltcG9ydGFudDtcbiAgbWluLWhlaWdodDogOGVtOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPUZvcm1Hcm91cC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgdmFsdWUgPSBcIlwiXG4gIGV4cG9ydCBsZXQgc2VsZWN0ZWQgPSBcIlwiO1xuICBleHBvcnQgbGV0IGxhYmVsVGV4dCA9IFwiXCI7XG4gIGV4cG9ydCBsZXQgaWQgPSBcIlwiO1xuICBleHBvcnQgbGV0IHBsYWNlaG9sZGVyID0gXCJcIjtcbjwvc2NyaXB0PlxuXG48ZGl2IGNsYXNzPVwiZm9ybS1ncm91cFwiPlxuICA8dGV4dGFyZWFcbiAgICBpZD17aWR9XG4gICAgY2xhc3M9XCJmb3JtLWlucHV0XCJcbiAgICB0eXBlPVwidGV4dFwiXG4gICAgYmluZDp2YWx1ZT17dmFsdWV9XG4gICAgcGxhY2Vob2xkZXI9e3BsYWNlaG9sZGVyfVxuICAgIGFyaWEtcGxhY2Vob2xkZXI9e3BsYWNlaG9sZGVyfVxuICAvPlxuPC9kaXY+XG4iLCJpbXBvcnQge1xuICBjb3VudFNlbnRlbmNlcyxcbiAgY291bnRXb3JkcyxcbiAgY291bnRIYXJkV29yZHMsXG59IGZyb20gXCIuLi9oZWxwZXJzL3dyaXR0ZW5MYW5ndWFnZUhlbHBlcnNcIjtcblxuZXhwb3J0IGNvbnN0IE1JTl9HVU5OSU5HX0ZMT0cgPSAwO1xuZXhwb3J0IGNvbnN0IE1BWF9HVU5OSU5HX0ZMT0cgPSAzMDtcblxuY29uc3Qgc2NvcmVUb0xldmVsTWFwID0ge1xuICAyMDpcdFwiUG9zdC1ncmFkdWF0ZSBQbHVzXCIsXG4gIDE5Olx0XCJQb3N0LWdyYWR1YXRlXCIsXG4gIDE4Olx0XCJQb3N0LWdyYWR1YXRlXCIsXG4gIDE3Olx0XCJDb2xsZWdlIGdyYWR1YXRlXCIsXG4gIDE2Olx0XCJDb2xsZWdlIHNlbmlvclwiLFxuICAxNTpcdFwiQ29sbGVnZSBqdW5pb3JcIixcbiAgMTQ6XHRcIkNvbGxlZ2Ugc29waG9tb3JlXCIsXG4gIDEzOlx0XCJDb2xsZWdlIGZyZXNobWFuXCIsXG4gIDEyOlx0XCJIaWdoIHNjaG9vbCBzZW5pb3JcIixcbiAgMTE6XHRcIkhpZ2ggc2Nob29sIGp1bmlvclwiLFxuICAxMDpcdFwiSGlnaCBzY2hvb2wgc29waG9tb3JlXCIsXG4gIDk6XHRcIkhpZ2ggc2Nob29sIGZyZXNobWFuXCIsXG4gIDg6XHRcIkVpZ2h0aCBncmFkZVwiLFxuICA3Olx0XCJTZXZlbnRoIGdyYWRlXCIsXG4gIDY6XHRcIlNpeHRoIGdyYWRlXCIsXG59XG5cbmV4cG9ydCBjbGFzcyBHdW5uaW5nRmxvZ1Njb3JlciB7XG4gIHN0YXRpYyBjYWxjdWxhdGUodGV4dCkge1xuICAgIGlmICghdGV4dCkge1xuICAgICAgcmV0dXJuIE1JTl9HVU5OSU5HX0ZMT0c7XG4gICAgfVxuXG4gICAgY29uc3Qgd29yZHMgPSBjb3VudFdvcmRzKHRleHQpO1xuICAgIGNvbnN0IGFzbCA9IHdvcmRzIC8gY291bnRTZW50ZW5jZXModGV4dCk7XG4gICAgY29uc3QgcGh3ID0gMTAwICogKGNvdW50SGFyZFdvcmRzKHRleHQpIC8gd29yZHMpO1xuICAgIGxldCBzY29yZSA9IDAuNCAqIChhc2wgKyBwaHcpXG5cbiAgICBpZiAoc2NvcmUgPiBNQVhfR1VOTklOR19GTE9HKSB7XG4gICAgICBzY29yZSA9IE1BWF9HVU5OSU5HX0ZMT0c7XG4gICAgfSBlbHNlIGlmKHNjb3JlIDwgTUlOX0dVTk5JTkdfRkxPRykge1xuICAgICAgc2NvcmUgPSBNSU5fR1VOTklOR19GTE9HO1xuICAgIH1cblxuICAgIHJldHVybiBzY29yZTtcbiAgfVxuICBzdGF0aWMgc2NvcmluZ0xldmVsKHNjb3JlKSB7XG4gICAgY29uc3QgaW50ZWdlclNjb3JlID0gcGFyc2VJbnQoc2NvcmUpO1xuICAgIGNvbnN0IHNjb3JlcyA9IE9iamVjdC5rZXlzKHNjb3JlVG9MZXZlbE1hcCk7XG4gICAgY29uc3QgbWluU2NvcmUgPSBzY29yZXNbMF07XG4gICAgY29uc3QgbWF4U2NvcmUgPSBzY29yZXNbc2NvcmVzLmxlbmd0aCAtIDFdO1xuXG4gICAgaWYgKGludGVnZXJTY29yZSA8IG1pblNjb3JlKSB7XG4gICAgICByZXR1cm4gXCJcIjtcbiAgICB9O1xuXG4gICAgaWYgKHNjb3JlID4gbWF4U2NvcmUpIHtcbiAgICAgIHJldHVybiBzY29yZVRvTGV2ZWxNYXBbbWF4U2NvcmVdXG4gICAgfSBlbHNlIGlmIChzY29yZSA8IG1pblNjb3JlKSB7XG4gICAgICByZXR1cm4gc2NvcmVUb0xldmVsTWFwW21pblNjb3JlXVxuICAgIH1cblxuICAgIHJldHVybiBzY29yZVRvTGV2ZWxNYXBbaW50ZWdlclNjb3JlXVxuICB9XG59XG4iLCI8c3R5bGUgbGFuZz1cInNjc3NcIj4uY29udGFpbmVyIHtcbiAgbWFyZ2luOiAxZW0gMDsgfVxuXG4ubGFiZWwge1xuICBtYXJnaW46IDA7XG4gIGNvbG9yOiAjMzQ0OTVlOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPVNjb3JlQ29udGFpbmVyLnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IFZhbHVlUmFuZ2UgZnJvbSBcIi4uL2NvbXBvbmVudHMvVmFsdWVSYW5nZS5zdmVsdGVcIjtcblxuICBleHBvcnQgbGV0IHRpdGxlO1xuICBleHBvcnQgbGV0IHN1YnRpdGxlID0gXCJcIjtcbiAgZXhwb3J0IGxldCB2YWx1ZTtcbiAgZXhwb3J0IGxldCBsZWZ0VmFsdWU7XG4gIGV4cG9ydCBsZXQgcmlnaHRWYWx1ZTtcbiAgZXhwb3J0IGxldCByZXZlcnNlID0gdW5kZWZpbmVkO1xuXG4gICQ6IHZhbHVlUmFuZ2VQcm9wcyA9IHtcbiAgICB2YWx1ZSxcbiAgICBsZWZ0VmFsdWUsXG4gICAgcmlnaHRWYWx1ZSxcbiAgICByZXZlcnNlLFxuICB9O1xuPC9zY3JpcHQ+XG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgPHAgY2xhc3M9XCJsYWJlbFwiPlxuICAgIDxzbWFsbD57dGl0bGV9Ojwvc21hbGw+XG4gICAge3ZhbHVlICYmIHZhbHVlLnRvRml4ZWQoMil9XG5cbiAgICB7I2lmIHN1YnRpdGxlfVxuICAgICAgPGJyLz5cbiAgICAgIDxzbWFsbCBjbGFzcz1cImxhYmVsXCI+e3N1YnRpdGxlfTwvc21hbGw+XG4gICAgey9pZn1cbiAgPC9wPlxuICA8VmFsdWVSYW5nZSB7Li4udmFsdWVSYW5nZVByb3BzfSAvPlxuPC9kaXY+XG4iLCI8c3R5bGUgbGFuZz1cInNjc3NcIj4uY29udGFpbmVyIHtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xuICB3aWR0aDogMTAwJTsgfVxuXG4udmFsdWVDb250YWluZXIge1xuICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gIHdpZHRoOiA1MCU7XG4gIG1hcmdpbjogMCBhdXRvO1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICBoZWlnaHQ6IDEuNWVtOyB9XG4gIEBtZWRpYSAobWF4LXdpZHRoOiA3NjhweCkge1xuICAgIC52YWx1ZUNvbnRhaW5lciB7XG4gICAgICB3aWR0aDogMTAwJTsgfSB9XG5cbi5yYW5nZSB7XG4gIGhlaWdodDogMnB4O1xuICBsZWZ0OiAwO1xuICByaWdodDogMDtcbiAgdG9wOiA1MCU7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtNTAlKTtcbiAgYmFja2dyb3VuZC1jb2xvcjogI2VjZjBmMTtcbiAgZmxleDogMTsgfVxuXG4ubWluVmFsdWUge1xuICBsZWZ0OiAwO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZSgtMTAwJSwgLTUwJSk7XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgdG9wOiA1MCU7XG4gIHdpZHRoOiAxcHg7XG4gIGhlaWdodDogMS41ZW07XG4gIGJhY2tncm91bmQtY29sb3I6ICMzNDQ5NWU7XG4gIGJvcmRlci1yYWRpdXM6IDEwMHB4OyB9XG5cbi5tYXhWYWx1ZSB7XG4gIHJpZ2h0OiAwO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZSgxMDAlLCAtNTAlKTtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICB0b3A6IDUwJTtcbiAgd2lkdGg6IDFweDtcbiAgaGVpZ2h0OiAxLjVlbTtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzM0NDk1ZTtcbiAgYm9yZGVyLXJhZGl1czogMTAwcHg7IH1cblxuLmN1cnJlbnRWYWx1ZSB7XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzM0NDk1ZTtcbiAgd2lkdGg6IDN2dztcbiAgaGVpZ2h0OiAzdnc7XG4gIG1heC13aWR0aDogMWVtO1xuICBtYXgtaGVpZ2h0OiAxZW07XG4gIGJvcmRlci1yYWRpdXM6IDEwMDBweDtcbiAgbGVmdDogNDMlO1xuICB0b3A6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC01MCUpOyB9XG5cbi5saW1pdExhYmVsIHtcbiAgYm90dG9tOiAtMTAwJTtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICBsZWZ0OiA1MCU7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlWCgtNTAlKTsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1WYWx1ZVJhbmdlLnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IHsgb25Nb3VudCB9IGZyb20gJ3N2ZWx0ZSc7XG4gIGltcG9ydCB7IHR3ZWVuZWQgfSBmcm9tICdzdmVsdGUvbW90aW9uJztcbiAgaW1wb3J0IHsgY3ViaWNPdXQgfSBmcm9tICdzdmVsdGUvZWFzaW5nJztcbiAgaW1wb3J0IHsgY3JlYXRlUkdCVmFsdWUgfSBmcm9tIFwiLi4vaGVscGVycy9jcmVhdGVSR0JWYWx1ZVwiO1xuXG4gIGV4cG9ydCBsZXQgbGVmdFZhbHVlO1xuICBleHBvcnQgbGV0IHJpZ2h0VmFsdWU7XG4gIGV4cG9ydCBsZXQgdmFsdWU7XG4gIGV4cG9ydCBsZXQgcmV2ZXJzZSA9IGZhbHNlO1xuXG4gIGxldCBjdXJyZW50RWxlbWVudFdpZHRoID0gMDtcbiAgY29uc3QgY29sb3JzID0gW1xuICAgIHsgcmVkOiA0NiwgZ3JlZW46IDIwNCwgYmx1ZTogMTEzLCB9LFxuICAgIHsgcmVkOiAyNDMsIGdyZWVuOiAxNTYsIGJsdWU6IDE4LCB9LFxuICAgIHsgcmVkOiAyMzEsIGdyZWVuOiA3NiwgYmx1ZTogNjAsIH0sXG4gIF07XG4gIGNvbnN0IHByb2dyZXNzID0gdHdlZW5lZCgwLCB7IGR1cmF0aW9uOiAzMDAsIGVhc2luZzogY3ViaWNPdXQgfSk7XG4gIGNvbnN0IHNldEN1cnJlbnRFbGVtZW50V2lkdGggPSAoKSA9PiB7XG4gICAgY3VycmVudEVsZW1lbnRXaWR0aCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIuY3VycmVudFZhbHVlXCIpLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpLndpZHRoO1xuICB9O1xuXG4gICQ6IHByb2dyZXNzLnNldCh2YWx1ZSAvIE1hdGgubWF4KHJpZ2h0VmFsdWUsIGxlZnRWYWx1ZSkpO1xuICAkOiBjdXJyZW50VmFsdWVFbGVtZW50V2lkdGhIYXNUb0JlU3VidHJhY3RlZCA9IChyZXZlcnNlID8gJHByb2dyZXNzIDwgMC41IDogJHByb2dyZXNzID4gMC41KTtcbiAgJDogc3VidHJhY3RWYWx1ZVRvUHJldmVudE92ZXJmbG93ID0gYCR7Y3VycmVudFZhbHVlRWxlbWVudFdpZHRoSGFzVG9CZVN1YnRyYWN0ZWQgPyBjdXJyZW50RWxlbWVudFdpZHRoIDogMH1weGA7XG4gICQ6IGNvbG9yID0gY3JlYXRlUkdCVmFsdWUocmV2ZXJzZSA/IDEgLSAkcHJvZ3Jlc3MgOiAkcHJvZ3Jlc3MsIGNvbG9ycyk7XG4gICQ6IHJnYiA9IGByZ2IoJHtjb2xvci5yZWR9LCAke2NvbG9yLmdyZWVufSwgJHtjb2xvci5ibHVlfSlgO1xuICAkOiBjdXJyZW50VmFsdWVTdHlsZSA9IGBiYWNrZ3JvdW5kLWNvbG9yOiAke3JnYn07IGxlZnQ6IGNhbGMoJHtyZXZlcnNlID8gXCIxMDAlIC0gXCIgOiBcIlwifSR7JHByb2dyZXNzICogMTAwfSUgLSAke3N1YnRyYWN0VmFsdWVUb1ByZXZlbnRPdmVyZmxvd30pO2A7XG5cbiAgb25Nb3VudChzZXRDdXJyZW50RWxlbWVudFdpZHRoKTtcbjwvc2NyaXB0PlxuXG48c3ZlbHRlOndpbmRvdyBvbjpyZXNpemU9e3NldEN1cnJlbnRFbGVtZW50V2lkdGh9IC8+XG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgPGRpdiBjbGFzcz1cInZhbHVlQ29udGFpbmVyXCI+XG4gICAgPGRpdiBjbGFzcz1cInJhbmdlXCIgLz5cbiAgICA8ZGl2IGNsYXNzPVwibWluVmFsdWVcIj5cbiAgICAgIDxzcGFuIGNsYXNzPVwibGltaXRMYWJlbFwiPntsZWZ0VmFsdWV9PC9zcGFuPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJtYXhWYWx1ZVwiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJsaW1pdExhYmVsXCI+e3JpZ2h0VmFsdWV9PC9zcGFuPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJjdXJyZW50VmFsdWVcIiBzdHlsZT17Y3VycmVudFZhbHVlU3R5bGV9IC8+XG4gIDwvZGl2PlxuPC9kaXY+XG4iLCJmdW5jdGlvbiBpbnRlcnBvbGF0ZSh2YWx1ZSwgbWluLCBtYXgpIHtcbiAgdmFyIGRlbHRhID0gbWF4IC0gbWluO1xuICB2YXIgc3RlcFZhbHVlID0gZGVsdGEgLyAxMDA7XG4gIHJldHVybiBtaW4gKyBzdGVwVmFsdWUgKiBNYXRoLmZsb29yKHZhbHVlICogMTAwKTtcbn1cblxuLyoqXG4gKiBDcmVhdGUgYW4gUkdCIHZhbHVlIGxvY2F0ZWQgYmV0d2VlbiAzIGNvbG9yc1xuICpcbiAqIEBwYXJhbSB7bnVtYmVyfSB2YWx1ZSAtIFZhbHVlIGJldHdlZW4gMCBhbmQgMVxuICogQHBhcmFtIHt7IHJlZDogbnVtYmVyOyBncmVlbjogbnVtYmVyOyBibHVlOiBudW1iZXI7IH1bXX0gY29sb3JzIC0gQXJyYXkgb2YgcmdiIGNvbG9yc1xuICovXG5leHBvcnQgZnVuY3Rpb24gY3JlYXRlUkdCVmFsdWUodmFsdWUsIGNvbG9ycykge1xuICBsZXQgcmVkO1xuICBsZXQgZ3JlZW47XG4gIGxldCBibHVlO1xuXG4gIGNvbnN0IFtcbiAgICBzdGFydENvbG9yLFxuICAgIG1pZENvbG9yLFxuICAgIGVuZENvbG9yLFxuICBdID0gY29sb3JzO1xuXG4gIGlmICh2YWx1ZSA+IDAuNSkge1xuICAgIHJlZCA9IGludGVycG9sYXRlKCh2YWx1ZSAtIDAuNSkgLyAwLjUsIG1pZENvbG9yLnJlZCwgZW5kQ29sb3IucmVkKTtcbiAgfSBlbHNlIHtcbiAgICByZWQgPSBpbnRlcnBvbGF0ZSh2YWx1ZSAvIDAuNSwgc3RhcnRDb2xvci5yZWQsIG1pZENvbG9yLnJlZCk7XG4gIH1cblxuICBpZiAodmFsdWUgPiAwLjUpIHtcbiAgICBncmVlbiA9IGludGVycG9sYXRlKCh2YWx1ZSAtIDAuNSkgLyAwLjUsIG1pZENvbG9yLmdyZWVuLCBlbmRDb2xvci5ncmVlbik7XG4gIH0gZWxzZSB7XG4gICAgZ3JlZW4gPSBpbnRlcnBvbGF0ZSh2YWx1ZSAvIDAuNSwgc3RhcnRDb2xvci5ncmVlbiwgbWlkQ29sb3IuZ3JlZW4pO1xuICB9XG5cbiAgaWYgKHZhbHVlID4gMC41KSB7XG4gICAgYmx1ZSA9IGludGVycG9sYXRlKCh2YWx1ZSAtIDAuNSkgLyAwLjUsIG1pZENvbG9yLmJsdWUsIGVuZENvbG9yLmJsdWUpO1xuICB9IGVsc2Uge1xuICAgIGJsdWUgPSBpbnRlcnBvbGF0ZSh2YWx1ZSAvIDAuNSwgc3RhcnRDb2xvci5ibHVlLCBtaWRDb2xvci5ibHVlKTtcbiAgfVxuXG4gIHJldHVybiB7XG4gICAgcmVkLFxuICAgIGdyZWVuLFxuICAgIGJsdWUsXG4gIH07XG59XG4iLCJpbXBvcnQgc3lsbGFibGUgZnJvbSBcInN5bGxhYmxlXCI7XG5cbmV4cG9ydCBmdW5jdGlvbiBjb3VudFdvcmRzKHRleHQpIHtcbiAgcmV0dXJuIGZpbmRXb3Jkcyh0ZXh0KS5sZW5ndGggfHwgMTtcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGZpbmRXb3Jkcyh0ZXh0KSB7XG4gIHJldHVybiB0ZXh0Lm1hdGNoKC8oW15cXHUwMDAwLVxcdTAwN0ZdfFxcdykrL2cpIHx8IFtdO1xufVxuXG5leHBvcnQgZnVuY3Rpb24gY291bnRTZW50ZW5jZXModGV4dCkge1xuICBjb25zdCBtYXRjaCA9IHRleHQubWF0Y2goL1tcXHddXFwpP1suPyFdKFxcc3wkKS9nKSB8fCBbXTtcbiAgcmV0dXJuIG1hdGNoLmxlbmd0aCB8fCAxO1xufVxuXG5leHBvcnQgZnVuY3Rpb24gY291bnRIYXJkV29yZHModGV4dCkge1xuICBjb25zdCB0ZXh0TG93ZXIgPSB0ZXh0LnRvTG93ZXJDYXNlKCk7XG4gIGxldCBjb3VudCA9IDA7XG5cbiAgZmluZFdvcmRzKHRleHRMb3dlcikuZm9yRWFjaCh3b3JkID0+IHtcbiAgICBpZiAoY291bnRXb3JkU3lsbGFibGVzKHdvcmQpID49IDMpIHtcbiAgICAgIGNvdW50ICs9IDE7XG4gICAgfVxuICB9KVxuXG4gIHJldHVybiBjb3VudDtcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGNvdW50U3lsbGFibGVzKHRleHQpIHtcbiAgY29uc3QgdGV4dExvd2VyID0gdGV4dC50b0xvd2VyQ2FzZSgpO1xuICBsZXQgY291bnQgPSAwO1xuXG4gIGZpbmRXb3Jkcyh0ZXh0TG93ZXIpLmZvckVhY2god29yZD0+IHtcbiAgICBjb3VudCArPSBjb3VudFdvcmRTeWxsYWJsZXMod29yZCk7XG4gIH0pXG5cbiAgcmV0dXJuIGNvdW50XG5cbn1cblxuZnVuY3Rpb24gY291bnRXb3JkU3lsbGFibGVzKG9yaWdpbmFsV29yZCkge1xuICByZXR1cm4gc3lsbGFibGUob3JpZ2luYWxXb3JkKVxufVxuIiwiPHN0eWxlIGxhbmc9XCJzY3NzXCI+KiB7XG4gIGZvbnQtZmFtaWx5OiBcIk1vbnRzZXJyYXRcIiwgc2Fucy1zZXJpZjsgfVxuXG46Z2xvYmFsKGlucHV0KSxcbjpnbG9iYWwodGV4dGFyZWEpIHtcbiAgYm94LXNoYWRvdzogMCAwIDAuNWVtIHJnYmEoMCwgMCwgMCwgMC4xKTtcbiAgLXdlYmtpdC1hcHBlYXJhbmNlOiBub25lO1xuICBib3JkZXI6IDA7XG4gIGZvbnQtZmFtaWx5OiBpbmhlcml0O1xuICBmb250LXNpemU6IGluaGVyaXQ7IH1cblxuLmNvbnRhaW5lciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gIHRleHQtYWxpZ246IGNlbnRlcjsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzY3JpcHQ+XG4gIGltcG9ydCBGb3JtR3JvdXAgZnJvbSBcIi4uL2NvbXBvbmVudHMvRm9ybUdyb3VwLnN2ZWx0ZVwiO1xuICBpbXBvcnQgVmFsdWVSYW5nZSBmcm9tIFwiLi4vY29tcG9uZW50cy9WYWx1ZVJhbmdlLnN2ZWx0ZVwiO1xuICBpbXBvcnQgU2NvcmVDb250YWluZXIgZnJvbSBcIi4uL2NvbXBvbmVudHMvU2NvcmVDb250YWluZXIuc3ZlbHRlXCI7XG5cbiAgaW1wb3J0IHtcbiAgICBGbGVzY2hLaW5jYWlkU2NvcmVyLFxuICAgIE1BWF9GTEVTQ19LSU5DQUlELFxuICAgIE1JTl9GTEVTQ19LSU5DQUlELFxuICB9IGZyb20gXCIuLi9jb21wb25lbnRzL0ZsZXNjaEtpbmNhaWRTY29yZXIuanNcIjtcbiAgaW1wb3J0IHtcbiAgICBHdW5uaW5nRmxvZ1Njb3JlcixcbiAgICBNQVhfR1VOTklOR19GTE9HLFxuICAgIE1JTl9HVU5OSU5HX0ZMT0csXG4gIH0gZnJvbSBcIi4uL2NvbXBvbmVudHMvR3VubmluZ0Zsb2dTY29yZXIuanNcIjtcblxuICBsZXQgc3ViamVjdFRleHQgPSBcIlwiO1xuICAkOiBmbGVzY2hLaW5jYWlkU2NvcmUgPSBGbGVzY2hLaW5jYWlkU2NvcmVyLmNhbGN1bGF0ZShzdWJqZWN0VGV4dCk7XG4gICQ6IGd1bm5pbmdGbG9nU2NvcmUgPSBHdW5uaW5nRmxvZ1Njb3Jlci5jYWxjdWxhdGUoc3ViamVjdFRleHQpO1xuPC9zY3JpcHQ+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlRleHQgU2NvcmU8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICA8aDE+SG93IHJlYWRhYmxlIGlzIHlvdXIgdGV4dD88L2gxPlxuICA8c21hbGw+PC9zbWFsbD5cbiAgPGhyLz5cbiAgPEZvcm1Hcm91cFxuICAgIGlkPXtcInN1YmplY3RUZXh0XCJ9XG4gICAgYmluZDp2YWx1ZT17c3ViamVjdFRleHR9XG4gICAgcGxhY2Vob2xkZXI9XCJXcml0ZSB5b3VyIHRleHQgaGVyZSBhbmQgc2VlIHRoZSBzY29yZSBiZWluZyBjYWxjdWxhdGVkXCJcbiAgLz5cblxuICA8U2NvcmVDb250YWluZXJcbiAgICB0aXRsZT1cIkZsZXNjaCBLaW5jYWlkIFJlYWRpbmcgRWFzZVwiXG4gICAgdmFsdWU9e2ZsZXNjaEtpbmNhaWRTY29yZX1cbiAgICBsZWZ0VmFsdWU9e01BWF9GTEVTQ19LSU5DQUlEfVxuICAgIHJpZ2h0VmFsdWU9e01JTl9GTEVTQ19LSU5DQUlEfVxuICAgIHJldmVyc2U9e3RydWV9XG4gIC8+XG4gIDxTY29yZUNvbnRhaW5lclxuICAgIHRpdGxlPVwiR3VubmluZyBmb2cgaW5kZXhcIlxuICAgIHZhbHVlPXtndW5uaW5nRmxvZ1Njb3JlfVxuICAgIHN1YnRpdGxlPXtHdW5uaW5nRmxvZ1Njb3Jlci5zY29yaW5nTGV2ZWwoZ3VubmluZ0Zsb2dTY29yZSl9XG4gICAgbGVmdFZhbHVlPXtNSU5fR1VOTklOR19GTE9HfVxuICAgIHJpZ2h0VmFsdWU9e01BWF9HVU5OSU5HX0ZMT0d9XG4gIC8+XG48L2Rpdj5cbiJdLCJzb3VyY2VSb290IjoiIn0=