(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/FleschKincaidScorer.js":
/*!***********************************************!*\
  !*** ./src/components/FleschKincaidScorer.js ***!
  \***********************************************/
/*! exports provided: MAX_FLESC_KINCAID, MIN_FLESC_KINCAID, FleschKincaidScorer */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MAX_FLESC_KINCAID", function() { return MAX_FLESC_KINCAID; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MIN_FLESC_KINCAID", function() { return MIN_FLESC_KINCAID; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FleschKincaidScorer", function() { return FleschKincaidScorer; });
/* harmony import */ var _helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../helpers/writtenLanguageHelpers */ "./src/helpers/writtenLanguageHelpers.js");


const MAX_FLESC_KINCAID = 120;
const MIN_FLESC_KINCAID = 0;

class FleschKincaidScorer {
  static calculate(text) {
    if (!text) {
      return MAX_FLESC_KINCAID;
    }

    const words = Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countWords"])(text);
    const asl = words / Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countSentences"])(text);
    const asw = Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countSyllables"])(text) / words;
    let score = 206.835 - (1.015 * asl) - (84.6 * asw);

    if (score > MAX_FLESC_KINCAID) {
      score = MAX_FLESC_KINCAID;
    } else if(score < MIN_FLESC_KINCAID) {
      score = MIN_FLESC_KINCAID;
    }

    return score;
  }
}


/***/ }),

/***/ "./src/components/FormGroup.svelte":
/*!*****************************************!*\
  !*** ./src/components/FormGroup.svelte ***!
  \*****************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/FormGroup.svelte generated by Svelte v3.7.1 */


const file = "src/components/FormGroup.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-zw7kt-style';
	style.textContent = ".form-group.svelte-zw7kt{display:flex;flex-direction:column}.label.svelte-zw7kt{font-size:1.2em;color:rgba(0, 0, 0, 0.1)}.label.active.svelte-zw7kt{color:rgba(0, 0, 0, 0.9)}.form-input.svelte-zw7kt{padding:0.5em;width:100% !important;min-height:10em}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRm9ybUdyb3VwLnN2ZWx0ZSIsInNvdXJjZXMiOlsiRm9ybUdyb3VwLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3R5bGUgbGFuZz1cInNjc3NcIj4uZm9ybS1ncm91cCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IH1cblxuLmxhYmVsIHtcbiAgZm9udC1zaXplOiAxLjJlbTtcbiAgY29sb3I6IHJnYmEoMCwgMCwgMCwgMC4xKTsgfVxuICAubGFiZWwuYWN0aXZlIHtcbiAgICBjb2xvcjogcmdiYSgwLCAwLCAwLCAwLjkpOyB9XG5cbi5mb3JtLWlucHV0IHtcbiAgcGFkZGluZzogMC41ZW07XG4gIHdpZHRoOiAxMDAlICFpbXBvcnRhbnQ7XG4gIG1pbi1oZWlnaHQ6IDEwZW07IH1cblxuLyojIHNvdXJjZU1hcHBpbmdVUkw9Rm9ybUdyb3VwLnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgZXhwb3J0IGxldCB2YWx1ZSA9IFwiXCJcblxuICBleHBvcnQgbGV0IHNlbGVjdGVkID0gXCJcIjtcbiAgZXhwb3J0IGxldCBsYWJlbFRleHQgPSBcIlwiO1xuICBleHBvcnQgbGV0IGlkID0gXCJcIjtcbiAgZXhwb3J0IGxldCBwbGFjZWhvbGRlciA9IFwiXCI7XG48L3NjcmlwdD5cblxuPGRpdiBjbGFzcz1cImZvcm0tZ3JvdXBcIj5cbiAgPGxhYmVsIGZvcj17aWR9IGNsYXNzPXtgbGFiZWwgJHtzZWxlY3RlZCA9PT0gaWQgPyBcImFjdGl2ZVwiIDogXCJcIn1gfT57bGFiZWxUZXh0fTwvbGFiZWw+XG4gIDx0ZXh0YXJlYVxuICAgIGlkPXtpZH1cbiAgICBjbGFzcz1cImZvcm0taW5wdXRcIlxuICAgIHR5cGU9XCJ0ZXh0XCJcbiAgICBiaW5kOnZhbHVlPXt2YWx1ZX1cbiAgICBwbGFjZWhvbGRlcj17cGxhY2Vob2xkZXJ9XG4gICAgYXJpYS1wbGFjZWhvbGRlcj17cGxhY2Vob2xkZXJ9XG4gIC8+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBbUIsV0FBVyxhQUFDLENBQUMsQUFDOUIsT0FBTyxDQUFFLElBQUksQ0FDYixjQUFjLENBQUUsTUFBTSxBQUFFLENBQUMsQUFFM0IsTUFBTSxhQUFDLENBQUMsQUFDTixTQUFTLENBQUUsS0FBSyxDQUNoQixLQUFLLENBQUUsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQUFBRSxDQUFDLEFBQzVCLE1BQU0sT0FBTyxhQUFDLENBQUMsQUFDYixLQUFLLENBQUUsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQUFBRSxDQUFDLEFBRWhDLFdBQVcsYUFBQyxDQUFDLEFBQ1gsT0FBTyxDQUFFLEtBQUssQ0FDZCxLQUFLLENBQUUsSUFBSSxDQUFDLFVBQVUsQ0FDdEIsVUFBVSxDQUFFLElBQUksQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var div, label, t0, label_class_value, t1, textarea, dispose;

	return {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("label");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.labelText);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			textarea = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("textarea");
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "LABEL", { for: true, class: true }, false);
			var label_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(label);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(label_nodes, ctx.labelText);
			label_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n  ");

			textarea = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "TEXTAREA", { id: true, class: true, type: true, placeholder: true, "aria-placeholder": true }, false);
			var textarea_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(textarea);

			textarea_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(label, "for", ctx.id);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(label, "class", label_class_value = "" + Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["null_to_empty"])((`label ${ctx.selected === ctx.id ? "active" : ""}`)) + " svelte-zw7kt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(label, file, 27, 2, 512);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "id", ctx.id);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "class", "form-input svelte-zw7kt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "type", "text");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "placeholder", ctx.placeholder);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "aria-placeholder", ctx.placeholder);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(textarea, file, 28, 2, 601);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", "form-group svelte-zw7kt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 26, 0, 485);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(textarea, "input", ctx.textarea_input_handler);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, label);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(label, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, textarea);

			textarea.value = ctx.value;
		},

		p: function update(changed, ctx) {
			if (changed.labelText) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, ctx.labelText);
			}

			if (changed.id) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(label, "for", ctx.id);
			}

			if ((changed.selected || changed.id) && label_class_value !== (label_class_value = "" + Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["null_to_empty"])((`label ${ctx.selected === ctx.id ? "active" : ""}`)) + " svelte-zw7kt")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(label, "class", label_class_value);
			}

			if (changed.value) textarea.value = ctx.value;

			if (changed.id) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "id", ctx.id);
			}

			if (changed.placeholder) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "placeholder", ctx.placeholder);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "aria-placeholder", ctx.placeholder);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
			}

			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { value = "", selected = "", labelText = "", id = "", placeholder = "" } = $$props;

	const writable_props = ['value', 'selected', 'labelText', 'id', 'placeholder'];
	Object.keys($$props).forEach(key => {
		if (!writable_props.includes(key) && !key.startsWith('$$')) console.warn(`<FormGroup> was created with unknown prop '${key}'`);
	});

	function textarea_input_handler() {
		value = this.value;
		$$invalidate('value', value);
	}

	$$self.$set = $$props => {
		if ('value' in $$props) $$invalidate('value', value = $$props.value);
		if ('selected' in $$props) $$invalidate('selected', selected = $$props.selected);
		if ('labelText' in $$props) $$invalidate('labelText', labelText = $$props.labelText);
		if ('id' in $$props) $$invalidate('id', id = $$props.id);
		if ('placeholder' in $$props) $$invalidate('placeholder', placeholder = $$props.placeholder);
	};

	return {
		value,
		selected,
		labelText,
		id,
		placeholder,
		textarea_input_handler
	};
}

class FormGroup extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-zw7kt-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], ["value", "selected", "labelText", "id", "placeholder"]);
	}

	get value() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set value(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get selected() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set selected(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get labelText() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set labelText(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get id() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set id(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get placeholder() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set placeholder(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (FormGroup);

/***/ }),

/***/ "./src/components/GunningFlogScorer.js":
/*!*********************************************!*\
  !*** ./src/components/GunningFlogScorer.js ***!
  \*********************************************/
/*! exports provided: MIN_GUNNING_FLOG, MAX_GUNNING_FLOG, GunningFlogScorer */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MIN_GUNNING_FLOG", function() { return MIN_GUNNING_FLOG; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MAX_GUNNING_FLOG", function() { return MAX_GUNNING_FLOG; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "GunningFlogScorer", function() { return GunningFlogScorer; });
/* harmony import */ var _helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../helpers/writtenLanguageHelpers */ "./src/helpers/writtenLanguageHelpers.js");


const MIN_GUNNING_FLOG = 0;
const MAX_GUNNING_FLOG = 30;

const scoreToLevelMap = {
  20:	"Post-graduate Plus",
  19:	"Post-graduate",
  18:	"Post-graduate",
  17:	"College graduate",
  16:	"College senior",
  15:	"College junior",
  14:	"College sophomore",
  13:	"College freshman",
  12:	"High school senior",
  11:	"High school junior",
  10:	"High school sophomore",
  9:	"High school freshman",
  8:	"Eighth grade",
  7:	"Seventh grade",
  6:	"Sixth grade",
}

class GunningFlogScorer {
  static calculate(text) {
    if (!text) {
      return MIN_GUNNING_FLOG;
    }

    const words = Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countWords"])(text);
    const asl = words / Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countSentences"])(text);
    const phw = 100 * (Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countHardWords"])(text) / words);
    let score = 0.4 * (asl + phw)

    if (score > MAX_GUNNING_FLOG) {
      score = MAX_GUNNING_FLOG;
    } else if(score < MIN_GUNNING_FLOG) {
      score = MIN_GUNNING_FLOG;
    }

    return score;
  }
  static scoringLevel(score) {
    const integerScore = parseInt(score);
    const scores = Object.keys(scoreToLevelMap);
    const minScore = scores[0];
    const maxScore = scores[scores.length - 1];

    if (integerScore < minScore) {
      return "";
    };

    if (score > maxScore) {
      return scoreToLevelMap[maxScore]
    } else if (score < minScore) {
      return scoreToLevelMap[minScore]
    }

    return scoreToLevelMap[integerScore]
  }
}


/***/ }),

/***/ "./src/components/ValueRange.svelte":
/*!******************************************!*\
  !*** ./src/components/ValueRange.svelte ***!
  \******************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var svelte_motion__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte/motion */ "./node_modules/svelte/motion/index.mjs");
/* harmony import */ var svelte_easing__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! svelte/easing */ "./node_modules/svelte/easing/index.mjs");
/* src/components/ValueRange.svelte generated by Svelte v3.7.1 */

const { document: document_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];




const file = "src/components/ValueRange.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1z0ksal-style';
	style.textContent = ".container.svelte-1z0ksal{text-align:center;width:100%}.valueContainer.svelte-1z0ksal{position:relative;width:50%;margin:0 auto;display:flex;align-items:center;height:1.5em}@media(max-width: 768px){.valueContainer.svelte-1z0ksal{width:100%}}.range.svelte-1z0ksal{height:2px;left:0;right:0;top:50%;transform:translateY(-50%);background-color:#ecf0f1;flex:1}.minValue.svelte-1z0ksal{left:0;transform:translate(-100%, -50%);position:absolute;top:50%;width:1px;height:1.5em;background-color:#34495e;border-radius:100px}.maxValue.svelte-1z0ksal{right:0;transform:translate(100%, -50%);position:absolute;top:50%;width:1px;height:1.5em;background-color:#34495e;border-radius:100px}.currentValue.svelte-1z0ksal{position:absolute;background-color:#34495e;width:3vw;height:3vw;max-width:1em;max-height:1em;border-radius:1000px;left:43%;top:50%;transform:translateY(-50%);border:1px solid #34495e}.limitLabel.svelte-1z0ksal{bottom:-100%;position:absolute;left:50%;transform:translateX(-50%)}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVmFsdWVSYW5nZS5zdmVsdGUiLCJzb3VyY2VzIjpbIlZhbHVlUmFuZ2Uuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzdHlsZSBsYW5nPVwic2Nzc1wiPi5jb250YWluZXIge1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIHdpZHRoOiAxMDAlOyB9XG5cbi52YWx1ZUNvbnRhaW5lciB7XG4gIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgd2lkdGg6IDUwJTtcbiAgbWFyZ2luOiAwIGF1dG87XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGhlaWdodDogMS41ZW07IH1cbiAgQG1lZGlhIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gICAgLnZhbHVlQ29udGFpbmVyIHtcbiAgICAgIHdpZHRoOiAxMDAlOyB9IH1cblxuLnJhbmdlIHtcbiAgaGVpZ2h0OiAycHg7XG4gIGxlZnQ6IDA7XG4gIHJpZ2h0OiAwO1xuICB0b3A6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC01MCUpO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZWNmMGYxO1xuICBmbGV4OiAxOyB9XG5cbi5taW5WYWx1ZSB7XG4gIGxlZnQ6IDA7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlKC0xMDAlLCAtNTAlKTtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICB0b3A6IDUwJTtcbiAgd2lkdGg6IDFweDtcbiAgaGVpZ2h0OiAxLjVlbTtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzM0NDk1ZTtcbiAgYm9yZGVyLXJhZGl1czogMTAwcHg7IH1cblxuLm1heFZhbHVlIHtcbiAgcmlnaHQ6IDA7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlKDEwMCUsIC01MCUpO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHRvcDogNTAlO1xuICB3aWR0aDogMXB4O1xuICBoZWlnaHQ6IDEuNWVtO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMzQ0OTVlO1xuICBib3JkZXItcmFkaXVzOiAxMDBweDsgfVxuXG4uY3VycmVudFZhbHVlIHtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMzQ0OTVlO1xuICB3aWR0aDogM3Z3O1xuICBoZWlnaHQ6IDN2dztcbiAgbWF4LXdpZHRoOiAxZW07XG4gIG1heC1oZWlnaHQ6IDFlbTtcbiAgYm9yZGVyLXJhZGl1czogMTAwMHB4O1xuICBsZWZ0OiA0MyU7XG4gIHRvcDogNTAlO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7XG4gIGJvcmRlcjogMXB4IHNvbGlkICMzNDQ5NWU7IH1cblxuLmxpbWl0TGFiZWwge1xuICBib3R0b206IC0xMDAlO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIGxlZnQ6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC01MCUpOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPVZhbHVlUmFuZ2Uuc3ZlbHRlLmNzcy5tYXAgKi88L3N0eWxlPlxuXG48c2NyaXB0PlxuICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJztcbiAgaW1wb3J0IHsgdHdlZW5lZCB9IGZyb20gJ3N2ZWx0ZS9tb3Rpb24nO1xuICBpbXBvcnQgeyBjdWJpY091dCB9IGZyb20gJ3N2ZWx0ZS9lYXNpbmcnO1xuXG4gIGNvbnN0IHByb2dyZXNzID0gdHdlZW5lZCgwLCB7XG5cdFx0ZHVyYXRpb246IDMwMCxcblx0XHRlYXNpbmc6IGN1YmljT3V0XG5cdH0pO1xuXG4gIGV4cG9ydCBsZXQgbGVmdFZhbHVlO1xuICBleHBvcnQgbGV0IHJpZ2h0VmFsdWU7XG4gIGV4cG9ydCBsZXQgdmFsdWU7XG4gIGV4cG9ydCBsZXQgcmV2ZXJzZSA9IGZhbHNlO1xuICBsZXQgY3VycmVudEVsZW1lbnRXaWR0aCA9IDA7XG4gICQ6IHByb2dyZXNzLnNldCh2YWx1ZSAvIE1hdGgubWF4KHJpZ2h0VmFsdWUsIGxlZnRWYWx1ZSkpO1xuXG4gIGNvbnN0IHNldEN1cnJlbnRFbGVtZW50V2lkdGggPSAoKSA9PiB7XG4gICAgY3VycmVudEVsZW1lbnRXaWR0aCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIuY3VycmVudFZhbHVlXCIpLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpLndpZHRoO1xuICB9O1xuICBvbk1vdW50KHNldEN1cnJlbnRFbGVtZW50V2lkdGgpO1xuXG4gICQ6IGN1cnJlbnRWYWx1ZUVsZW1lbnRXaWR0aEhhc1RvQmVTdWJ0cmFjdGVkID0gKHJldmVyc2UgPyAkcHJvZ3Jlc3MgPCAwLjUgOiAkcHJvZ3Jlc3MgPiAwLjUpO1xuICAkOiBzdWJ0cmFjdFZhbHVlVG9QcmV2ZW50T3ZlcmZsb3cgPSBgJHtjdXJyZW50VmFsdWVFbGVtZW50V2lkdGhIYXNUb0JlU3VidHJhY3RlZCA/IGN1cnJlbnRFbGVtZW50V2lkdGggOiAwfXB4YDtcbiAgJDogY3VycmVudFZhbHVlU3R5bGUgPSBgbGVmdDogY2FsYygke3JldmVyc2UgPyBcIjEwMCUgLSBcIiA6IFwiXCJ9JHskcHJvZ3Jlc3MgKiAxMDB9JSAtICR7c3VidHJhY3RWYWx1ZVRvUHJldmVudE92ZXJmbG93fSk7YDtcbjwvc2NyaXB0PlxuXG48c3ZlbHRlOndpbmRvdyBvbjpyZXNpemU9e3NldEN1cnJlbnRFbGVtZW50V2lkdGh9IC8+XG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgPGRpdiBjbGFzcz1cInZhbHVlQ29udGFpbmVyXCI+XG4gICAgPGRpdiBjbGFzcz1cInJhbmdlXCI+PC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cIm1pblZhbHVlXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cImxpbWl0TGFiZWxcIj57bGVmdFZhbHVlfTwvc3Bhbj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwibWF4VmFsdWVcIj5cbiAgICAgIDxzcGFuIGNsYXNzPVwibGltaXRMYWJlbFwiPntyaWdodFZhbHVlfTwvc3Bhbj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwiY3VycmVudFZhbHVlXCIgc3R5bGU9e2N1cnJlbnRWYWx1ZVN0eWxlfSAvPlxuICA8L2Rpdj5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFtQixVQUFVLGVBQUMsQ0FBQyxBQUM3QixVQUFVLENBQUUsTUFBTSxDQUNsQixLQUFLLENBQUUsSUFBSSxBQUFFLENBQUMsQUFFaEIsZUFBZSxlQUFDLENBQUMsQUFDZixRQUFRLENBQUUsUUFBUSxDQUNsQixLQUFLLENBQUUsR0FBRyxDQUNWLE1BQU0sQ0FBRSxDQUFDLENBQUMsSUFBSSxDQUNkLE9BQU8sQ0FBRSxJQUFJLENBQ2IsV0FBVyxDQUFFLE1BQU0sQ0FDbkIsTUFBTSxDQUFFLEtBQUssQUFBRSxDQUFDLEFBQ2hCLE1BQU0sQUFBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekIsZUFBZSxlQUFDLENBQUMsQUFDZixLQUFLLENBQUUsSUFBSSxBQUFFLENBQUMsQUFBQyxDQUFDLEFBRXRCLE1BQU0sZUFBQyxDQUFDLEFBQ04sTUFBTSxDQUFFLEdBQUcsQ0FDWCxJQUFJLENBQUUsQ0FBQyxDQUNQLEtBQUssQ0FBRSxDQUFDLENBQ1IsR0FBRyxDQUFFLEdBQUcsQ0FDUixTQUFTLENBQUUsV0FBVyxJQUFJLENBQUMsQ0FDM0IsZ0JBQWdCLENBQUUsT0FBTyxDQUN6QixJQUFJLENBQUUsQ0FBQyxBQUFFLENBQUMsQUFFWixTQUFTLGVBQUMsQ0FBQyxBQUNULElBQUksQ0FBRSxDQUFDLENBQ1AsU0FBUyxDQUFFLFVBQVUsS0FBSyxDQUFDLENBQUMsSUFBSSxDQUFDLENBQ2pDLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLEdBQUcsQ0FBRSxHQUFHLENBQ1IsS0FBSyxDQUFFLEdBQUcsQ0FDVixNQUFNLENBQUUsS0FBSyxDQUNiLGdCQUFnQixDQUFFLE9BQU8sQ0FDekIsYUFBYSxDQUFFLEtBQUssQUFBRSxDQUFDLEFBRXpCLFNBQVMsZUFBQyxDQUFDLEFBQ1QsS0FBSyxDQUFFLENBQUMsQ0FDUixTQUFTLENBQUUsVUFBVSxJQUFJLENBQUMsQ0FBQyxJQUFJLENBQUMsQ0FDaEMsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsR0FBRyxDQUFFLEdBQUcsQ0FDUixLQUFLLENBQUUsR0FBRyxDQUNWLE1BQU0sQ0FBRSxLQUFLLENBQ2IsZ0JBQWdCLENBQUUsT0FBTyxDQUN6QixhQUFhLENBQUUsS0FBSyxBQUFFLENBQUMsQUFFekIsYUFBYSxlQUFDLENBQUMsQUFDYixRQUFRLENBQUUsUUFBUSxDQUNsQixnQkFBZ0IsQ0FBRSxPQUFPLENBQ3pCLEtBQUssQ0FBRSxHQUFHLENBQ1YsTUFBTSxDQUFFLEdBQUcsQ0FDWCxTQUFTLENBQUUsR0FBRyxDQUNkLFVBQVUsQ0FBRSxHQUFHLENBQ2YsYUFBYSxDQUFFLE1BQU0sQ0FDckIsSUFBSSxDQUFFLEdBQUcsQ0FDVCxHQUFHLENBQUUsR0FBRyxDQUNSLFNBQVMsQ0FBRSxXQUFXLElBQUksQ0FBQyxDQUMzQixNQUFNLENBQUUsR0FBRyxDQUFDLEtBQUssQ0FBQyxPQUFPLEFBQUUsQ0FBQyxBQUU5QixXQUFXLGVBQUMsQ0FBQyxBQUNYLE1BQU0sQ0FBRSxLQUFLLENBQ2IsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsSUFBSSxDQUFFLEdBQUcsQ0FDVCxTQUFTLENBQUUsV0FBVyxJQUFJLENBQUMsQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document_1.head, style);
}

function create_fragment(ctx) {
	var div5, div4, div0, t0, div1, span0, t1, t2, div2, span1, t3, t4, div3, dispose;

	return {
		c: function create() {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.leftValue);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.rightValue);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			this.h()
		},

		l: function claim(nodes) {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ctx.leftValue);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, ctx.rightValue);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true, style: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "range svelte-1z0ksal");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 96, 4, 2214);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "limitLabel svelte-1z0ksal");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 98, 6, 2273);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div1, "class", "minValue svelte-1z0ksal");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 97, 4, 2244);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "limitLabel svelte-1z0ksal");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 101, 6, 2361);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div2, "class", "maxValue svelte-1z0ksal");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 100, 4, 2332);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "class", "currentValue svelte-1z0ksal");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "style", ctx.currentValueStyle);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 103, 4, 2421);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div4, "class", "valueContainer svelte-1z0ksal");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 95, 2, 2181);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div5, "class", "container svelte-1z0ksal");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 94, 0, 2155);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(window, "resize", ctx.setCurrentElementWidth);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div5, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div3);
		},

		p: function update(changed, ctx) {
			if (changed.leftValue) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, ctx.leftValue);
			}

			if (changed.rightValue) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t3, ctx.rightValue);
			}

			if (changed.currentValueStyle) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "style", ctx.currentValueStyle);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div5);
			}

			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $progress;

	

  const progress = Object(svelte_motion__WEBPACK_IMPORTED_MODULE_2__["tweened"])(0, {
		duration: 300,
		easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["cubicOut"]
	}); Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(progress, 'progress'); Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, progress, $$value => { $progress = $$value; $$invalidate('$progress', $progress) });

  let { leftValue, rightValue, value, reverse = false } = $$props;
  let currentElementWidth = 0;

  const setCurrentElementWidth = () => {
    $$invalidate('currentElementWidth', currentElementWidth = document.querySelector(".currentValue").getBoundingClientRect().width);
  };
  Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(setCurrentElementWidth);

	const writable_props = ['leftValue', 'rightValue', 'value', 'reverse'];
	Object.keys($$props).forEach(key => {
		if (!writable_props.includes(key) && !key.startsWith('$$')) console.warn(`<ValueRange> was created with unknown prop '${key}'`);
	});

	$$self.$set = $$props => {
		if ('leftValue' in $$props) $$invalidate('leftValue', leftValue = $$props.leftValue);
		if ('rightValue' in $$props) $$invalidate('rightValue', rightValue = $$props.rightValue);
		if ('value' in $$props) $$invalidate('value', value = $$props.value);
		if ('reverse' in $$props) $$invalidate('reverse', reverse = $$props.reverse);
	};

	let currentValueElementWidthHasToBeSubtracted, subtractValueToPreventOverflow, currentValueStyle;

	$$self.$$.update = ($$dirty = { value: 1, rightValue: 1, leftValue: 1, reverse: 1, $progress: 1, currentValueElementWidthHasToBeSubtracted: 1, currentElementWidth: 1, subtractValueToPreventOverflow: 1 }) => {
		if ($$dirty.value || $$dirty.rightValue || $$dirty.leftValue) { progress.set(value / Math.max(rightValue, leftValue)); }
		if ($$dirty.reverse || $$dirty.$progress) { $$invalidate('currentValueElementWidthHasToBeSubtracted', currentValueElementWidthHasToBeSubtracted = (reverse ? $progress < 0.5 : $progress > 0.5)); }
		if ($$dirty.currentValueElementWidthHasToBeSubtracted || $$dirty.currentElementWidth) { $$invalidate('subtractValueToPreventOverflow', subtractValueToPreventOverflow = `${currentValueElementWidthHasToBeSubtracted ? currentElementWidth : 0}px`); }
		if ($$dirty.reverse || $$dirty.$progress || $$dirty.subtractValueToPreventOverflow) { $$invalidate('currentValueStyle', currentValueStyle = `left: calc(${reverse ? "100% - " : ""}${$progress * 100}% - ${subtractValueToPreventOverflow});`); }
	};

	return {
		progress,
		leftValue,
		rightValue,
		value,
		reverse,
		setCurrentElementWidth,
		currentValueStyle
	};
}

class ValueRange extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document_1.getElementById("svelte-1z0ksal-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], ["leftValue", "rightValue", "value", "reverse"]);

		const { ctx } = this.$$;
		const props = options.props || {};
		if (ctx.leftValue === undefined && !('leftValue' in props)) {
			console.warn("<ValueRange> was created without expected prop 'leftValue'");
		}
		if (ctx.rightValue === undefined && !('rightValue' in props)) {
			console.warn("<ValueRange> was created without expected prop 'rightValue'");
		}
		if (ctx.value === undefined && !('value' in props)) {
			console.warn("<ValueRange> was created without expected prop 'value'");
		}
	}

	get leftValue() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set leftValue(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get rightValue() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set rightValue(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get value() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set value(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get reverse() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set reverse(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (ValueRange);

/***/ }),

/***/ "./src/helpers/writtenLanguageHelpers.js":
/*!***********************************************!*\
  !*** ./src/helpers/writtenLanguageHelpers.js ***!
  \***********************************************/
/*! exports provided: countWords, findWords, countSentences, countHardWords, countSyllables */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countWords", function() { return countWords; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "findWords", function() { return findWords; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countSentences", function() { return countSentences; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countHardWords", function() { return countHardWords; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countSyllables", function() { return countSyllables; });
/* harmony import */ var syllable__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! syllable */ "./node_modules/syllable/index.js");
/* harmony import */ var syllable__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(syllable__WEBPACK_IMPORTED_MODULE_0__);


function countWords(text) {
  return findWords(text).length || 1;
}

function findWords(text) {
  return text.match(/([^\u0000-\u007F]|\w)+/g) || [];
}

function countSentences(text) {
  const match = text.match(/[\w]\)?[.?!](\s|$)/g) || [];
  return match.length || 1;
}

function countHardWords(text) {
  const textLower = text.toLowerCase();
  let count = 0;

  findWords(textLower).forEach(word => {
    if (countWordSyllables(word) >= 3) {
      count += 1;
    }
  })

  return count;
}

function countSyllables(text) {
  const textLower = text.toLowerCase();
  let count = 0;

  findWords(textLower).forEach(word=> {
    count += countWordSyllables(word);
  })

  return count

}

function countWordSyllables(originalWord) {
  return syllable__WEBPACK_IMPORTED_MODULE_0___default()(originalWord)
}


/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_FormGroup_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/FormGroup.svelte */ "./src/components/FormGroup.svelte");
/* harmony import */ var _components_ValueRange_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/ValueRange.svelte */ "./src/components/ValueRange.svelte");
/* harmony import */ var _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/FleschKincaidScorer.js */ "./src/components/FleschKincaidScorer.js");
/* harmony import */ var _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../components/GunningFlogScorer.js */ "./src/components/GunningFlogScorer.js");
/* src/routes/index.svelte generated by Svelte v3.7.1 */






const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-29m5oy-style';
	style.textContent = ".svelte-29m5oy{font-family:\"Montserrat\", sans-serif}input,textarea{box-shadow:0 0 0.5em rgba(0, 0, 0, 0.1);-webkit-appearance:none;border:0;font-family:inherit;font-size:inherit}.container.svelte-29m5oy{display:flex;flex-direction:column;text-align:center}.score-container.svelte-29m5oy{margin:1em 0}.score-label.svelte-29m5oy{margin:0;color:#34495e}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN0eWxlIGxhbmc9XCJzY3NzXCI+KiB7XG4gIGZvbnQtZmFtaWx5OiBcIk1vbnRzZXJyYXRcIiwgc2Fucy1zZXJpZjsgfVxuXG46Z2xvYmFsKGlucHV0KSxcbjpnbG9iYWwodGV4dGFyZWEpIHtcbiAgYm94LXNoYWRvdzogMCAwIDAuNWVtIHJnYmEoMCwgMCwgMCwgMC4xKTtcbiAgLXdlYmtpdC1hcHBlYXJhbmNlOiBub25lO1xuICBib3JkZXI6IDA7XG4gIGZvbnQtZmFtaWx5OiBpbmhlcml0O1xuICBmb250LXNpemU6IGluaGVyaXQ7IH1cblxuLmNvbnRhaW5lciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gIHRleHQtYWxpZ246IGNlbnRlcjsgfVxuXG4uc2NvcmUtY29udGFpbmVyIHtcbiAgbWFyZ2luOiAxZW0gMDsgfVxuXG4uc2NvcmUtbGFiZWwge1xuICBtYXJnaW46IDA7XG4gIGNvbG9yOiAjMzQ0OTVlOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IEZvcm1Hcm91cCBmcm9tIFwiLi4vY29tcG9uZW50cy9Gb3JtR3JvdXAuc3ZlbHRlXCI7XG4gIGltcG9ydCBWYWx1ZVJhbmdlIGZyb20gXCIuLi9jb21wb25lbnRzL1ZhbHVlUmFuZ2Uuc3ZlbHRlXCI7XG4gIGltcG9ydCB7XG4gICAgRmxlc2NoS2luY2FpZFNjb3JlcixcbiAgICBNQVhfRkxFU0NfS0lOQ0FJRCxcbiAgICBNSU5fRkxFU0NfS0lOQ0FJRCxcbiAgfSBmcm9tIFwiLi4vY29tcG9uZW50cy9GbGVzY2hLaW5jYWlkU2NvcmVyLmpzXCI7XG4gIGltcG9ydCB7XG4gICAgR3VubmluZ0Zsb2dTY29yZXIsXG4gICAgTUFYX0dVTk5JTkdfRkxPRyxcbiAgICBNSU5fR1VOTklOR19GTE9HLFxuICB9IGZyb20gXCIuLi9jb21wb25lbnRzL0d1bm5pbmdGbG9nU2NvcmVyLmpzXCI7XG5cbiAgbGV0IHN1YmplY3RUZXh0ID0gXCJcIjtcbiAgJDogZmxlc2NoS2luY2FpZFNjb3JlID0gRmxlc2NoS2luY2FpZFNjb3Jlci5jYWxjdWxhdGUoc3ViamVjdFRleHQpO1xuICAkOiBndW5uaW5nRmxvZ1Njb3JlID0gR3VubmluZ0Zsb2dTY29yZXIuY2FsY3VsYXRlKHN1YmplY3RUZXh0KTtcbjwvc2NyaXB0PlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5UZXh0IFNjb3JlPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgPGgxPkhvdyByZWFkYWJsZSBpcyB5b3VyIHRleHQ/PC9oMT5cbiAgPHNtYWxsPjwvc21hbGw+XG4gIDxoci8+XG4gIDxGb3JtR3JvdXBcbiAgICBpZD17XCJzdWJqZWN0VGV4dFwifVxuICAgIGJpbmQ6dmFsdWU9e3N1YmplY3RUZXh0fVxuICAgIHBsYWNlaG9sZGVyPVwiV3JpdGUgeW91ciB0ZXh0IGhlcmUgYW5kIHNlZSB0aGUgc2NvcmUgYmVpbmcgY2FsY3VsYXRlZFwiXG4gIC8+XG4gIDxkaXYgY2xhc3M9XCJzY29yZS1jb250YWluZXJcIj5cbiAgICA8cCBjbGFzcz1cInNjb3JlLWxhYmVsXCI+XG4gICAgICA8c21hbGw+Rmxlc2NoIEtpbmNhaWQgUmVhZGluZyBFYXNlOjwvc21hbGw+XG4gICAgICA8c3BhbiBjbGFzcz1cInNjb3JlLXZhbHVlXCI+e2ZsZXNjaEtpbmNhaWRTY29yZS50b0ZpeGVkKDIpfTwvc3Bhbj5cbiAgICA8L3A+XG4gICAgPFZhbHVlUmFuZ2VcbiAgICAgIHJldmVyc2U9e3RydWV9XG4gICAgICByaWdodFZhbHVlPXtNSU5fRkxFU0NfS0lOQ0FJRH1cbiAgICAgIGxlZnRWYWx1ZT17TUFYX0ZMRVNDX0tJTkNBSUR9XG4gICAgICB2YWx1ZT17Zmxlc2NoS2luY2FpZFNjb3JlfVxuICAgIC8+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwic2NvcmUtY29udGFpbmVyXCI+XG4gICAgPHAgY2xhc3M9XCJzY29yZS1sYWJlbFwiPlxuICAgICAgPHNtYWxsPkd1bm5pbmcgZm9nIGluZGV4Ojwvc21hbGw+XG4gICAgICA8c3BhbiBjbGFzcz1cInNjb3JlLXZhbHVlXCI+e2d1bm5pbmdGbG9nU2NvcmUudG9GaXhlZCgyKX08L3NwYW4+XG4gICAgICA8YnIvPlxuICAgICAgPHNtYWxsIGNsYXNzPVwic2NvcmUtbGFiZWxcIj57R3VubmluZ0Zsb2dTY29yZXIuc2NvcmluZ0xldmVsKGd1bm5pbmdGbG9nU2NvcmUpfTwvc21hbGw+XG4gICAgPC9wPlxuICAgIDxWYWx1ZVJhbmdlXG4gICAgICBsZWZ0VmFsdWU9e01JTl9HVU5OSU5HX0ZMT0d9XG4gICAgICByaWdodFZhbHVlPXtNQVhfR1VOTklOR19GTE9HfVxuICAgICAgdmFsdWU9e2d1bm5pbmdGbG9nU2NvcmV9XG4gICAgLz5cbiAgPC9kaXY+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBbUIsY0FBRSxDQUFDLEFBQ3BCLFdBQVcsQ0FBRSxZQUFZLENBQUMsQ0FBQyxVQUFVLEFBQUUsQ0FBQyxBQUVsQyxLQUFLLEFBQUMsQ0FDTixRQUFRLEFBQUUsQ0FBQyxBQUNqQixVQUFVLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FDeEMsa0JBQWtCLENBQUUsSUFBSSxDQUN4QixNQUFNLENBQUUsQ0FBQyxDQUNULFdBQVcsQ0FBRSxPQUFPLENBQ3BCLFNBQVMsQ0FBRSxPQUFPLEFBQUUsQ0FBQyxBQUV2QixVQUFVLGNBQUMsQ0FBQyxBQUNWLE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLE1BQU0sQ0FDdEIsVUFBVSxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBRXZCLGdCQUFnQixjQUFDLENBQUMsQUFDaEIsTUFBTSxDQUFFLEdBQUcsQ0FBQyxDQUFDLEFBQUUsQ0FBQyxBQUVsQixZQUFZLGNBQUMsQ0FBQyxBQUNaLE1BQU0sQ0FBRSxDQUFDLENBQ1QsS0FBSyxDQUFFLE9BQU8sQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div2, h1, t1, t2, small0, t3, hr, t4, updating_value, t5, div0, p0, small1, t6, t7, span0, t8_value = ctx.fleschKincaidScore.toFixed(2), t8, t9, t10, div1, p1, small2, t11, t12, span1, t13_value = ctx.gunningFlogScore.toFixed(2), t13, t14, br, t15, small3, t16_value = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["GunningFlogScorer"].scoringLevel(ctx.gunningFlogScore), t16, t17, current;

	function formgroup_value_binding(value) {
		ctx.formgroup_value_binding.call(null, value);
		updating_value = true;
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_value = false);
	}

	let formgroup_props = {
		id: "subjectText",
		placeholder: "Write your text here and see the score being calculated"
	};
	if (ctx.subjectText !== void 0) {
		formgroup_props.value = ctx.subjectText;
	}
	var formgroup = new _components_FormGroup_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ props: formgroup_props, $$inline: true });

	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(formgroup, 'value', formgroup_value_binding));

	var valuerange0 = new _components_ValueRange_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({
		props: {
		reverse: true,
		rightValue: _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["MIN_FLESC_KINCAID"],
		leftValue: _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["MAX_FLESC_KINCAID"],
		value: ctx.fleschKincaidScore
	},
		$$inline: true
	});

	var valuerange1 = new _components_ValueRange_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({
		props: {
		leftValue: _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["MIN_GUNNING_FLOG"],
		rightValue: _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["MAX_GUNNING_FLOG"],
		value: ctx.gunningFlogScore
	},
		$$inline: true
	});

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("How readable is your text?");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			small0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			hr = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			formgroup.$$.fragment.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			small1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Flesch Kincaid Reading Ease:");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t8_value);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			valuerange0.$$.fragment.c();
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			small2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Gunning fog index:");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t13_value);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			small3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t16_value);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			valuerange1.$$.fragment.c();
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "How readable is your text?");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");

			small0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "SMALL", { class: true }, false);
			var small0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small0);

			small0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");

			hr = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "HR", { class: true }, false);
			var hr_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(hr);

			hr_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");
			formgroup.$$.fragment.l(div2_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			small1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "SMALL", { class: true }, false);
			var small1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small1);

			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small1_nodes, "Flesch Kincaid Reading Ease:");
			small1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n      ");

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t8_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div0_nodes, "\n    ");
			valuerange0.$$.fragment.l(div0_nodes);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			small2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "SMALL", { class: true }, false);
			var small2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small2);

			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small2_nodes, "Gunning fog index:");
			small2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n      ");

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, t13_value);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n      ");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "BR", { class: true }, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n      ");

			small3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "SMALL", { class: true }, false);
			var small3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small3);

			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small3_nodes, t16_value);
			small3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n    ");
			valuerange1.$$.fragment.l(div1_nodes);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Text Score";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h1, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 49, 2, 1099);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small0, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small0, file, 50, 2, 1137);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(hr, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr, file, 51, 2, 1155);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small1, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small1, file, 59, 6, 1371);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "score-value svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 60, 6, 1421);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "score-label svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 58, 4, 1341);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "score-container svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 57, 2, 1307);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small2, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small2, file, 71, 6, 1720);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "score-value svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 72, 6, 1760);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(br, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 73, 6, 1829);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small3, "class", "score-label svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small3, file, 74, 6, 1841);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "score-label svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 70, 4, 1690);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div1, "class", "score-container svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 69, 2, 1656);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div2, "class", "container svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 48, 0, 1073);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, small0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, hr);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(formgroup, div2, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, small1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(small1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(valuerange0, div0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, small2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(small2, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, small3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(small3, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(valuerange1, div1, null);
			current = true;
		},

		p: function update(changed, ctx) {
			var formgroup_changes = {};
			if (!updating_value && changed.subjectText) {
				formgroup_changes.value = ctx.subjectText;
			}
			formgroup.$set(formgroup_changes);

			if ((!current || changed.fleschKincaidScore) && t8_value !== (t8_value = ctx.fleschKincaidScore.toFixed(2))) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t8, t8_value);
			}

			var valuerange0_changes = {};
			if (changed.MIN_FLESC_KINCAID) valuerange0_changes.rightValue = _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["MIN_FLESC_KINCAID"];
			if (changed.MAX_FLESC_KINCAID) valuerange0_changes.leftValue = _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["MAX_FLESC_KINCAID"];
			if (changed.fleschKincaidScore) valuerange0_changes.value = ctx.fleschKincaidScore;
			valuerange0.$set(valuerange0_changes);

			if ((!current || changed.gunningFlogScore) && t13_value !== (t13_value = ctx.gunningFlogScore.toFixed(2))) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t13, t13_value);
			}

			if ((!current || changed.gunningFlogScore) && t16_value !== (t16_value = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["GunningFlogScorer"].scoringLevel(ctx.gunningFlogScore))) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t16, t16_value);
			}

			var valuerange1_changes = {};
			if (changed.MIN_GUNNING_FLOG) valuerange1_changes.leftValue = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["MIN_GUNNING_FLOG"];
			if (changed.MAX_GUNNING_FLOG) valuerange1_changes.rightValue = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["MAX_GUNNING_FLOG"];
			if (changed.gunningFlogScore) valuerange1_changes.value = ctx.gunningFlogScore;
			valuerange1.$set(valuerange1_changes);
		},

		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(formgroup.$$.fragment, local);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(valuerange0.$$.fragment, local);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(valuerange1.$$.fragment, local);

			current = true;
		},

		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(formgroup.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(valuerange0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(valuerange1.$$.fragment, local);
			current = false;
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div2);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(formgroup);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(valuerange0);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(valuerange1);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	

  let subjectText = "";

	function formgroup_value_binding(value) {
		subjectText = value;
		$$invalidate('subjectText', subjectText);
	}

	let fleschKincaidScore, gunningFlogScore;

	$$self.$$.update = ($$dirty = { subjectText: 1 }) => {
		if ($$dirty.subjectText) { $$invalidate('fleschKincaidScore', fleschKincaidScore = _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["FleschKincaidScorer"].calculate(subjectText)); }
		if ($$dirty.subjectText) { $$invalidate('gunningFlogScore', gunningFlogScore = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["GunningFlogScorer"].calculate(subjectText)); }
	};

	return {
		subjectText,
		fleschKincaidScore,
		gunningFlogScore,
		formgroup_value_binding
	};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-29m5oy-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9jb21wb25lbnRzL0ZsZXNjaEtpbmNhaWRTY29yZXIuanMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9Gb3JtR3JvdXAuc3ZlbHRlIiwid2VicGFjazovLy93ZWJwYWNrOi8vLy4vc3JjL2NvbXBvbmVudHMvR3VubmluZ0Zsb2dTY29yZXIuanMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9WYWx1ZVJhbmdlLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9oZWxwZXJzL3dyaXR0ZW5MYW5ndWFnZUhlbHBlcnMuanMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7O0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUkyQzs7QUFFcEM7QUFDQTs7QUFFQTtBQUNQO0FBQ0E7QUFDQTtBQUNBOztBQUVBLGtCQUFrQixrRkFBVTtBQUM1Qix3QkFBd0Isc0ZBQWM7QUFDdEMsZ0JBQWdCLHNGQUFjO0FBQzlCOztBQUVBO0FBQ0E7QUFDQSxLQUFLO0FBQ0w7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7eUVDRHNFLFNBQVM7Ozs7Ozs7Ozs7Ozs7NEZBQVQsU0FBUzs7Ozs7Ozs7Ozs7OztrRkFBakUsRUFBRTtnTEFBUyxDQUFDLE1BQU0sTUFBRSxRQUFRLFNBQUssRUFBRSxHQUFHLFFBQVEsR0FBRyxFQUFFLENBQUMsQ0FBQzs7b0ZBRTNELEVBQUU7Ozs2RkFJTyxXQUFXO2tHQUNOLFdBQVc7Ozs7Ozs7Ozs7Ozs7O3dCQUZqQixLQUFLOzs7Ozs2RUFMaUQsU0FBUzs7OzttRkFBakUsRUFBRTs7O2tLQUFTLENBQUMsTUFBTSxNQUFFLFFBQVEsU0FBSyxFQUFFLEdBQUcsUUFBUSxHQUFHLEVBQUUsQ0FBQyxDQUFDOzs7OzJDQUtuRCxLQUFLOzs7cUZBSGIsRUFBRTs7Ozs4RkFJTyxXQUFXO21HQUNOLFdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQWhCeEIsTUFBSSxLQUFLLEdBQUcsRUFBRSxFQUVWLFFBQVEsR0FBRyxFQUFFLEVBQ2IsU0FBUyxHQUFHLEVBQUUsRUFDZCxFQUFFLEdBQUcsRUFBRSxFQUNQLFdBQVcsR0FBRyxjQUFFLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ3ZCOUI7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUkyQzs7QUFFcEM7QUFDQTs7QUFFUDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVPO0FBQ1A7QUFDQTtBQUNBO0FBQ0E7O0FBRUEsa0JBQWtCLGtGQUFVO0FBQzVCLHdCQUF3QixzRkFBYztBQUN0Qyx1QkFBdUIsc0ZBQWM7QUFDckM7O0FBRUE7QUFDQTtBQUNBLEtBQUs7QUFDTDtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0EsS0FBSztBQUNMO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7eUVDa0NnQyxTQUFTOzs7O3lFQUdULFVBQVU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NEZBSFYsU0FBUzs7Ozs7Ozs7Ozs7NEZBR1QsVUFBVTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7bUZBRUwsaUJBQWlCOzs7Ozs7a0dBWDVCLHNCQUFzQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZFQU1oQixTQUFTOzs7OzZFQUdULFVBQVU7Ozs7b0ZBRUwsaUJBQWlCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQW5DWDs7RUFFekMsTUFBTSxRQUFRLEdBQUcsNkRBQU8sQ0FBQyxDQUFDLEVBQUU7RUFDNUIsUUFBUSxFQUFFLEdBQUc7RUFDYixNQUFNLEVBQUUsc0RBQVE7RUFDaEIsd1FBQUMsQ0FBQzs7RUFFSyxNQUFJLFNBQVMsRUFDVCxVQUFVLEVBQ1YsS0FBSyxFQUNMLE9BQU8sR0FBRyxpQkFBSyxDQUFDO0VBQzNCLElBQUksbUJBQW1CLEdBQUcsQ0FBQyxDQUM4Qjs7RUFFekQsTUFBTSxzQkFBc0IsR0FBRyxNQUFNO3dDQUNuQyxtQkFBbUIsR0FBRyxRQUFRLENBQUMsYUFBYSxDQUFDLGVBQWUsQ0FBQyxDQUFDLHFCQUFxQixFQUFFLENBQUMsTUFBSyxDQUFDO0dBQzdGLENBQUM7RUFDRixzREFBTyxDQUFDLHNCQUFzQixDQUFDLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7O2tFQUw3QixRQUFRLENBQUMsR0FBRyxDQUFDLEtBQUssR0FBRyxJQUFJLENBQUMsR0FBRyxDQUFDLFVBQVUsRUFBRSxTQUFTLENBQUMsQ0FBQyxDQUFDO3dHQU90RCx5Q0FBeUMsR0FBRyxDQUFDLE9BQU8sR0FBRyxTQUFTLEdBQUcsR0FBRyxHQUFHLFNBQVMsR0FBRyxHQUFHLEVBQUMsQ0FBQzt5SUFDMUYsOEJBQThCLEdBQUcsQ0FBQyxFQUFFLHlDQUF5QyxHQUFHLG1CQUFtQixHQUFHLENBQUMsQ0FBQyxFQUFFLEVBQUMsQ0FBQzswSEFDNUcsaUJBQWlCLEdBQUcsQ0FBQyxXQUFXLEVBQUUsT0FBTyxHQUFHLFNBQVMsR0FBRyxFQUFFLENBQUMsRUFBRSxTQUFTLEdBQUcsR0FBRyxDQUFDLElBQUksRUFBRSw4QkFBOEIsQ0FBQyxFQUFFLEVBQUMsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDekYzSDtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQWdDOztBQUV6QjtBQUNQO0FBQ0E7O0FBRU87QUFDUDtBQUNBOztBQUVPO0FBQ1A7QUFDQTtBQUNBOztBQUVPO0FBQ1A7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLEdBQUc7O0FBRUg7QUFDQTs7QUFFTztBQUNQO0FBQ0E7O0FBRUE7QUFDQTtBQUNBLEdBQUc7O0FBRUg7O0FBRUE7O0FBRUE7QUFDQSxTQUFTLCtDQUFRO0FBQ2pCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7bUhDa0JpQyxrQkFBa0IsQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDLGtFQVk3QixnQkFBZ0IsQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDLHlDQUUxQixrRkFBaUIsQ0FBQyxZQUFZLEtBQUMsZ0JBQWdCLENBQUM7Ozs7Ozs7OztNQXJCMUUsYUFBYTs7O1NBQ0wsV0FBVzs4QkFBWCxXQUFXOzs7Ozs7OztXQVNaLElBQUk7Y0FDRCxvRkFBaUI7YUFDbEIsb0ZBQWlCO2FBQ3JCLGtCQUFrQjs7Ozs7OzthQVdkLGlGQUFnQjtjQUNmLGlGQUFnQjthQUNyQixnQkFBZ0I7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tDQXpCYixXQUFXOzs7O2dGQU1NLGtCQUFrQixDQUFDLE9BQU8sQ0FBQyxDQUFDLENBQUM7Ozs7O21FQUk1QyxvRkFBaUI7a0VBQ2xCLG9GQUFpQjttRUFDckIsa0JBQWtCOzs7Z0ZBTUUsZ0JBQWdCLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQzs7Ozs0RUFFMUIsa0ZBQWlCLENBQUMsWUFBWSxLQUFDLGdCQUFnQixDQUFDOzs7OztpRUFHakUsaUZBQWdCO2tFQUNmLGlGQUFnQjtpRUFDckIsZ0JBQWdCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQTFDaUI7O0VBRTVDLElBQUksV0FBVyxHQUFHLEVBQUUsQ0FBQzs7Ozs7Ozs7OztnRUFDbEIsa0JBQWtCLEdBQUcsc0ZBQW1CLENBQUMsU0FBUyxDQUFDLFdBQVcsRUFBQyxDQUFDOzhEQUNoRSxnQkFBZ0IsR0FBRyxrRkFBaUIsQ0FBQyxTQUFTLENBQUMsV0FBVyxFQUFDLENBQUMiLCJmaWxlIjoiMzMzYzhjYmZmMzYyMDk2OTYwZmQvaW5kZXguaW5kZXguanMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQge1xuICBjb3VudFNlbnRlbmNlcyxcbiAgY291bnRTeWxsYWJsZXMsXG4gIGNvdW50V29yZHMsXG59IGZyb20gXCIuLi9oZWxwZXJzL3dyaXR0ZW5MYW5ndWFnZUhlbHBlcnNcIjtcblxuZXhwb3J0IGNvbnN0IE1BWF9GTEVTQ19LSU5DQUlEID0gMTIwO1xuZXhwb3J0IGNvbnN0IE1JTl9GTEVTQ19LSU5DQUlEID0gMDtcblxuZXhwb3J0IGNsYXNzIEZsZXNjaEtpbmNhaWRTY29yZXIge1xuICBzdGF0aWMgY2FsY3VsYXRlKHRleHQpIHtcbiAgICBpZiAoIXRleHQpIHtcbiAgICAgIHJldHVybiBNQVhfRkxFU0NfS0lOQ0FJRDtcbiAgICB9XG5cbiAgICBjb25zdCB3b3JkcyA9IGNvdW50V29yZHModGV4dCk7XG4gICAgY29uc3QgYXNsID0gd29yZHMgLyBjb3VudFNlbnRlbmNlcyh0ZXh0KTtcbiAgICBjb25zdCBhc3cgPSBjb3VudFN5bGxhYmxlcyh0ZXh0KSAvIHdvcmRzO1xuICAgIGxldCBzY29yZSA9IDIwNi44MzUgLSAoMS4wMTUgKiBhc2wpIC0gKDg0LjYgKiBhc3cpO1xuXG4gICAgaWYgKHNjb3JlID4gTUFYX0ZMRVNDX0tJTkNBSUQpIHtcbiAgICAgIHNjb3JlID0gTUFYX0ZMRVNDX0tJTkNBSUQ7XG4gICAgfSBlbHNlIGlmKHNjb3JlIDwgTUlOX0ZMRVNDX0tJTkNBSUQpIHtcbiAgICAgIHNjb3JlID0gTUlOX0ZMRVNDX0tJTkNBSUQ7XG4gICAgfVxuXG4gICAgcmV0dXJuIHNjb3JlO1xuICB9XG59XG4iLCI8c3R5bGUgbGFuZz1cInNjc3NcIj4uZm9ybS1ncm91cCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IH1cblxuLmxhYmVsIHtcbiAgZm9udC1zaXplOiAxLjJlbTtcbiAgY29sb3I6IHJnYmEoMCwgMCwgMCwgMC4xKTsgfVxuICAubGFiZWwuYWN0aXZlIHtcbiAgICBjb2xvcjogcmdiYSgwLCAwLCAwLCAwLjkpOyB9XG5cbi5mb3JtLWlucHV0IHtcbiAgcGFkZGluZzogMC41ZW07XG4gIHdpZHRoOiAxMDAlICFpbXBvcnRhbnQ7XG4gIG1pbi1oZWlnaHQ6IDEwZW07IH1cblxuLyojIHNvdXJjZU1hcHBpbmdVUkw9Rm9ybUdyb3VwLnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgZXhwb3J0IGxldCB2YWx1ZSA9IFwiXCJcblxuICBleHBvcnQgbGV0IHNlbGVjdGVkID0gXCJcIjtcbiAgZXhwb3J0IGxldCBsYWJlbFRleHQgPSBcIlwiO1xuICBleHBvcnQgbGV0IGlkID0gXCJcIjtcbiAgZXhwb3J0IGxldCBwbGFjZWhvbGRlciA9IFwiXCI7XG48L3NjcmlwdD5cblxuPGRpdiBjbGFzcz1cImZvcm0tZ3JvdXBcIj5cbiAgPGxhYmVsIGZvcj17aWR9IGNsYXNzPXtgbGFiZWwgJHtzZWxlY3RlZCA9PT0gaWQgPyBcImFjdGl2ZVwiIDogXCJcIn1gfT57bGFiZWxUZXh0fTwvbGFiZWw+XG4gIDx0ZXh0YXJlYVxuICAgIGlkPXtpZH1cbiAgICBjbGFzcz1cImZvcm0taW5wdXRcIlxuICAgIHR5cGU9XCJ0ZXh0XCJcbiAgICBiaW5kOnZhbHVlPXt2YWx1ZX1cbiAgICBwbGFjZWhvbGRlcj17cGxhY2Vob2xkZXJ9XG4gICAgYXJpYS1wbGFjZWhvbGRlcj17cGxhY2Vob2xkZXJ9XG4gIC8+XG48L2Rpdj5cbiIsImltcG9ydCB7XG4gIGNvdW50U2VudGVuY2VzLFxuICBjb3VudFdvcmRzLFxuICBjb3VudEhhcmRXb3Jkcyxcbn0gZnJvbSBcIi4uL2hlbHBlcnMvd3JpdHRlbkxhbmd1YWdlSGVscGVyc1wiO1xuXG5leHBvcnQgY29uc3QgTUlOX0dVTk5JTkdfRkxPRyA9IDA7XG5leHBvcnQgY29uc3QgTUFYX0dVTk5JTkdfRkxPRyA9IDMwO1xuXG5jb25zdCBzY29yZVRvTGV2ZWxNYXAgPSB7XG4gIDIwOlx0XCJQb3N0LWdyYWR1YXRlIFBsdXNcIixcbiAgMTk6XHRcIlBvc3QtZ3JhZHVhdGVcIixcbiAgMTg6XHRcIlBvc3QtZ3JhZHVhdGVcIixcbiAgMTc6XHRcIkNvbGxlZ2UgZ3JhZHVhdGVcIixcbiAgMTY6XHRcIkNvbGxlZ2Ugc2VuaW9yXCIsXG4gIDE1Olx0XCJDb2xsZWdlIGp1bmlvclwiLFxuICAxNDpcdFwiQ29sbGVnZSBzb3Bob21vcmVcIixcbiAgMTM6XHRcIkNvbGxlZ2UgZnJlc2htYW5cIixcbiAgMTI6XHRcIkhpZ2ggc2Nob29sIHNlbmlvclwiLFxuICAxMTpcdFwiSGlnaCBzY2hvb2wganVuaW9yXCIsXG4gIDEwOlx0XCJIaWdoIHNjaG9vbCBzb3Bob21vcmVcIixcbiAgOTpcdFwiSGlnaCBzY2hvb2wgZnJlc2htYW5cIixcbiAgODpcdFwiRWlnaHRoIGdyYWRlXCIsXG4gIDc6XHRcIlNldmVudGggZ3JhZGVcIixcbiAgNjpcdFwiU2l4dGggZ3JhZGVcIixcbn1cblxuZXhwb3J0IGNsYXNzIEd1bm5pbmdGbG9nU2NvcmVyIHtcbiAgc3RhdGljIGNhbGN1bGF0ZSh0ZXh0KSB7XG4gICAgaWYgKCF0ZXh0KSB7XG4gICAgICByZXR1cm4gTUlOX0dVTk5JTkdfRkxPRztcbiAgICB9XG5cbiAgICBjb25zdCB3b3JkcyA9IGNvdW50V29yZHModGV4dCk7XG4gICAgY29uc3QgYXNsID0gd29yZHMgLyBjb3VudFNlbnRlbmNlcyh0ZXh0KTtcbiAgICBjb25zdCBwaHcgPSAxMDAgKiAoY291bnRIYXJkV29yZHModGV4dCkgLyB3b3Jkcyk7XG4gICAgbGV0IHNjb3JlID0gMC40ICogKGFzbCArIHBodylcblxuICAgIGlmIChzY29yZSA+IE1BWF9HVU5OSU5HX0ZMT0cpIHtcbiAgICAgIHNjb3JlID0gTUFYX0dVTk5JTkdfRkxPRztcbiAgICB9IGVsc2UgaWYoc2NvcmUgPCBNSU5fR1VOTklOR19GTE9HKSB7XG4gICAgICBzY29yZSA9IE1JTl9HVU5OSU5HX0ZMT0c7XG4gICAgfVxuXG4gICAgcmV0dXJuIHNjb3JlO1xuICB9XG4gIHN0YXRpYyBzY29yaW5nTGV2ZWwoc2NvcmUpIHtcbiAgICBjb25zdCBpbnRlZ2VyU2NvcmUgPSBwYXJzZUludChzY29yZSk7XG4gICAgY29uc3Qgc2NvcmVzID0gT2JqZWN0LmtleXMoc2NvcmVUb0xldmVsTWFwKTtcbiAgICBjb25zdCBtaW5TY29yZSA9IHNjb3Jlc1swXTtcbiAgICBjb25zdCBtYXhTY29yZSA9IHNjb3Jlc1tzY29yZXMubGVuZ3RoIC0gMV07XG5cbiAgICBpZiAoaW50ZWdlclNjb3JlIDwgbWluU2NvcmUpIHtcbiAgICAgIHJldHVybiBcIlwiO1xuICAgIH07XG5cbiAgICBpZiAoc2NvcmUgPiBtYXhTY29yZSkge1xuICAgICAgcmV0dXJuIHNjb3JlVG9MZXZlbE1hcFttYXhTY29yZV1cbiAgICB9IGVsc2UgaWYgKHNjb3JlIDwgbWluU2NvcmUpIHtcbiAgICAgIHJldHVybiBzY29yZVRvTGV2ZWxNYXBbbWluU2NvcmVdXG4gICAgfVxuXG4gICAgcmV0dXJuIHNjb3JlVG9MZXZlbE1hcFtpbnRlZ2VyU2NvcmVdXG4gIH1cbn1cbiIsIjxzdHlsZSBsYW5nPVwic2Nzc1wiPi5jb250YWluZXIge1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIHdpZHRoOiAxMDAlOyB9XG5cbi52YWx1ZUNvbnRhaW5lciB7XG4gIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgd2lkdGg6IDUwJTtcbiAgbWFyZ2luOiAwIGF1dG87XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGhlaWdodDogMS41ZW07IH1cbiAgQG1lZGlhIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gICAgLnZhbHVlQ29udGFpbmVyIHtcbiAgICAgIHdpZHRoOiAxMDAlOyB9IH1cblxuLnJhbmdlIHtcbiAgaGVpZ2h0OiAycHg7XG4gIGxlZnQ6IDA7XG4gIHJpZ2h0OiAwO1xuICB0b3A6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC01MCUpO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZWNmMGYxO1xuICBmbGV4OiAxOyB9XG5cbi5taW5WYWx1ZSB7XG4gIGxlZnQ6IDA7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlKC0xMDAlLCAtNTAlKTtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICB0b3A6IDUwJTtcbiAgd2lkdGg6IDFweDtcbiAgaGVpZ2h0OiAxLjVlbTtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzM0NDk1ZTtcbiAgYm9yZGVyLXJhZGl1czogMTAwcHg7IH1cblxuLm1heFZhbHVlIHtcbiAgcmlnaHQ6IDA7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlKDEwMCUsIC01MCUpO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHRvcDogNTAlO1xuICB3aWR0aDogMXB4O1xuICBoZWlnaHQ6IDEuNWVtO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMzQ0OTVlO1xuICBib3JkZXItcmFkaXVzOiAxMDBweDsgfVxuXG4uY3VycmVudFZhbHVlIHtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMzQ0OTVlO1xuICB3aWR0aDogM3Z3O1xuICBoZWlnaHQ6IDN2dztcbiAgbWF4LXdpZHRoOiAxZW07XG4gIG1heC1oZWlnaHQ6IDFlbTtcbiAgYm9yZGVyLXJhZGl1czogMTAwMHB4O1xuICBsZWZ0OiA0MyU7XG4gIHRvcDogNTAlO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7XG4gIGJvcmRlcjogMXB4IHNvbGlkICMzNDQ5NWU7IH1cblxuLmxpbWl0TGFiZWwge1xuICBib3R0b206IC0xMDAlO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIGxlZnQ6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC01MCUpOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPVZhbHVlUmFuZ2Uuc3ZlbHRlLmNzcy5tYXAgKi88L3N0eWxlPlxuXG48c2NyaXB0PlxuICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJztcbiAgaW1wb3J0IHsgdHdlZW5lZCB9IGZyb20gJ3N2ZWx0ZS9tb3Rpb24nO1xuICBpbXBvcnQgeyBjdWJpY091dCB9IGZyb20gJ3N2ZWx0ZS9lYXNpbmcnO1xuXG4gIGNvbnN0IHByb2dyZXNzID0gdHdlZW5lZCgwLCB7XG5cdFx0ZHVyYXRpb246IDMwMCxcblx0XHRlYXNpbmc6IGN1YmljT3V0XG5cdH0pO1xuXG4gIGV4cG9ydCBsZXQgbGVmdFZhbHVlO1xuICBleHBvcnQgbGV0IHJpZ2h0VmFsdWU7XG4gIGV4cG9ydCBsZXQgdmFsdWU7XG4gIGV4cG9ydCBsZXQgcmV2ZXJzZSA9IGZhbHNlO1xuICBsZXQgY3VycmVudEVsZW1lbnRXaWR0aCA9IDA7XG4gICQ6IHByb2dyZXNzLnNldCh2YWx1ZSAvIE1hdGgubWF4KHJpZ2h0VmFsdWUsIGxlZnRWYWx1ZSkpO1xuXG4gIGNvbnN0IHNldEN1cnJlbnRFbGVtZW50V2lkdGggPSAoKSA9PiB7XG4gICAgY3VycmVudEVsZW1lbnRXaWR0aCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIuY3VycmVudFZhbHVlXCIpLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpLndpZHRoO1xuICB9O1xuICBvbk1vdW50KHNldEN1cnJlbnRFbGVtZW50V2lkdGgpO1xuXG4gICQ6IGN1cnJlbnRWYWx1ZUVsZW1lbnRXaWR0aEhhc1RvQmVTdWJ0cmFjdGVkID0gKHJldmVyc2UgPyAkcHJvZ3Jlc3MgPCAwLjUgOiAkcHJvZ3Jlc3MgPiAwLjUpO1xuICAkOiBzdWJ0cmFjdFZhbHVlVG9QcmV2ZW50T3ZlcmZsb3cgPSBgJHtjdXJyZW50VmFsdWVFbGVtZW50V2lkdGhIYXNUb0JlU3VidHJhY3RlZCA/IGN1cnJlbnRFbGVtZW50V2lkdGggOiAwfXB4YDtcbiAgJDogY3VycmVudFZhbHVlU3R5bGUgPSBgbGVmdDogY2FsYygke3JldmVyc2UgPyBcIjEwMCUgLSBcIiA6IFwiXCJ9JHskcHJvZ3Jlc3MgKiAxMDB9JSAtICR7c3VidHJhY3RWYWx1ZVRvUHJldmVudE92ZXJmbG93fSk7YDtcbjwvc2NyaXB0PlxuXG48c3ZlbHRlOndpbmRvdyBvbjpyZXNpemU9e3NldEN1cnJlbnRFbGVtZW50V2lkdGh9IC8+XG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgPGRpdiBjbGFzcz1cInZhbHVlQ29udGFpbmVyXCI+XG4gICAgPGRpdiBjbGFzcz1cInJhbmdlXCI+PC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cIm1pblZhbHVlXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cImxpbWl0TGFiZWxcIj57bGVmdFZhbHVlfTwvc3Bhbj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwibWF4VmFsdWVcIj5cbiAgICAgIDxzcGFuIGNsYXNzPVwibGltaXRMYWJlbFwiPntyaWdodFZhbHVlfTwvc3Bhbj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwiY3VycmVudFZhbHVlXCIgc3R5bGU9e2N1cnJlbnRWYWx1ZVN0eWxlfSAvPlxuICA8L2Rpdj5cbjwvZGl2PlxuIiwiaW1wb3J0IHN5bGxhYmxlIGZyb20gXCJzeWxsYWJsZVwiO1xuXG5leHBvcnQgZnVuY3Rpb24gY291bnRXb3Jkcyh0ZXh0KSB7XG4gIHJldHVybiBmaW5kV29yZHModGV4dCkubGVuZ3RoIHx8IDE7XG59XG5cbmV4cG9ydCBmdW5jdGlvbiBmaW5kV29yZHModGV4dCkge1xuICByZXR1cm4gdGV4dC5tYXRjaCgvKFteXFx1MDAwMC1cXHUwMDdGXXxcXHcpKy9nKSB8fCBbXTtcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGNvdW50U2VudGVuY2VzKHRleHQpIHtcbiAgY29uc3QgbWF0Y2ggPSB0ZXh0Lm1hdGNoKC9bXFx3XVxcKT9bLj8hXShcXHN8JCkvZykgfHwgW107XG4gIHJldHVybiBtYXRjaC5sZW5ndGggfHwgMTtcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGNvdW50SGFyZFdvcmRzKHRleHQpIHtcbiAgY29uc3QgdGV4dExvd2VyID0gdGV4dC50b0xvd2VyQ2FzZSgpO1xuICBsZXQgY291bnQgPSAwO1xuXG4gIGZpbmRXb3Jkcyh0ZXh0TG93ZXIpLmZvckVhY2god29yZCA9PiB7XG4gICAgaWYgKGNvdW50V29yZFN5bGxhYmxlcyh3b3JkKSA+PSAzKSB7XG4gICAgICBjb3VudCArPSAxO1xuICAgIH1cbiAgfSlcblxuICByZXR1cm4gY291bnQ7XG59XG5cbmV4cG9ydCBmdW5jdGlvbiBjb3VudFN5bGxhYmxlcyh0ZXh0KSB7XG4gIGNvbnN0IHRleHRMb3dlciA9IHRleHQudG9Mb3dlckNhc2UoKTtcbiAgbGV0IGNvdW50ID0gMDtcblxuICBmaW5kV29yZHModGV4dExvd2VyKS5mb3JFYWNoKHdvcmQ9PiB7XG4gICAgY291bnQgKz0gY291bnRXb3JkU3lsbGFibGVzKHdvcmQpO1xuICB9KVxuXG4gIHJldHVybiBjb3VudFxuXG59XG5cbmZ1bmN0aW9uIGNvdW50V29yZFN5bGxhYmxlcyhvcmlnaW5hbFdvcmQpIHtcbiAgcmV0dXJuIHN5bGxhYmxlKG9yaWdpbmFsV29yZClcbn1cbiIsIjxzdHlsZSBsYW5nPVwic2Nzc1wiPioge1xuICBmb250LWZhbWlseTogXCJNb250c2VycmF0XCIsIHNhbnMtc2VyaWY7IH1cblxuOmdsb2JhbChpbnB1dCksXG46Z2xvYmFsKHRleHRhcmVhKSB7XG4gIGJveC1zaGFkb3c6IDAgMCAwLjVlbSByZ2JhKDAsIDAsIDAsIDAuMSk7XG4gIC13ZWJraXQtYXBwZWFyYW5jZTogbm9uZTtcbiAgYm9yZGVyOiAwO1xuICBmb250LWZhbWlseTogaW5oZXJpdDtcbiAgZm9udC1zaXplOiBpbmhlcml0OyB9XG5cbi5jb250YWluZXIge1xuICBkaXNwbGF5OiBmbGV4O1xuICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7IH1cblxuLnNjb3JlLWNvbnRhaW5lciB7XG4gIG1hcmdpbjogMWVtIDA7IH1cblxuLnNjb3JlLWxhYmVsIHtcbiAgbWFyZ2luOiAwO1xuICBjb2xvcjogIzM0NDk1ZTsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzY3JpcHQ+XG4gIGltcG9ydCBGb3JtR3JvdXAgZnJvbSBcIi4uL2NvbXBvbmVudHMvRm9ybUdyb3VwLnN2ZWx0ZVwiO1xuICBpbXBvcnQgVmFsdWVSYW5nZSBmcm9tIFwiLi4vY29tcG9uZW50cy9WYWx1ZVJhbmdlLnN2ZWx0ZVwiO1xuICBpbXBvcnQge1xuICAgIEZsZXNjaEtpbmNhaWRTY29yZXIsXG4gICAgTUFYX0ZMRVNDX0tJTkNBSUQsXG4gICAgTUlOX0ZMRVNDX0tJTkNBSUQsXG4gIH0gZnJvbSBcIi4uL2NvbXBvbmVudHMvRmxlc2NoS2luY2FpZFNjb3Jlci5qc1wiO1xuICBpbXBvcnQge1xuICAgIEd1bm5pbmdGbG9nU2NvcmVyLFxuICAgIE1BWF9HVU5OSU5HX0ZMT0csXG4gICAgTUlOX0dVTk5JTkdfRkxPRyxcbiAgfSBmcm9tIFwiLi4vY29tcG9uZW50cy9HdW5uaW5nRmxvZ1Njb3Jlci5qc1wiO1xuXG4gIGxldCBzdWJqZWN0VGV4dCA9IFwiXCI7XG4gICQ6IGZsZXNjaEtpbmNhaWRTY29yZSA9IEZsZXNjaEtpbmNhaWRTY29yZXIuY2FsY3VsYXRlKHN1YmplY3RUZXh0KTtcbiAgJDogZ3VubmluZ0Zsb2dTY29yZSA9IEd1bm5pbmdGbG9nU2NvcmVyLmNhbGN1bGF0ZShzdWJqZWN0VGV4dCk7XG48L3NjcmlwdD5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+VGV4dCBTY29yZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gIDxoMT5Ib3cgcmVhZGFibGUgaXMgeW91ciB0ZXh0PzwvaDE+XG4gIDxzbWFsbD48L3NtYWxsPlxuICA8aHIvPlxuICA8Rm9ybUdyb3VwXG4gICAgaWQ9e1wic3ViamVjdFRleHRcIn1cbiAgICBiaW5kOnZhbHVlPXtzdWJqZWN0VGV4dH1cbiAgICBwbGFjZWhvbGRlcj1cIldyaXRlIHlvdXIgdGV4dCBoZXJlIGFuZCBzZWUgdGhlIHNjb3JlIGJlaW5nIGNhbGN1bGF0ZWRcIlxuICAvPlxuICA8ZGl2IGNsYXNzPVwic2NvcmUtY29udGFpbmVyXCI+XG4gICAgPHAgY2xhc3M9XCJzY29yZS1sYWJlbFwiPlxuICAgICAgPHNtYWxsPkZsZXNjaCBLaW5jYWlkIFJlYWRpbmcgRWFzZTo8L3NtYWxsPlxuICAgICAgPHNwYW4gY2xhc3M9XCJzY29yZS12YWx1ZVwiPntmbGVzY2hLaW5jYWlkU2NvcmUudG9GaXhlZCgyKX08L3NwYW4+XG4gICAgPC9wPlxuICAgIDxWYWx1ZVJhbmdlXG4gICAgICByZXZlcnNlPXt0cnVlfVxuICAgICAgcmlnaHRWYWx1ZT17TUlOX0ZMRVNDX0tJTkNBSUR9XG4gICAgICBsZWZ0VmFsdWU9e01BWF9GTEVTQ19LSU5DQUlEfVxuICAgICAgdmFsdWU9e2ZsZXNjaEtpbmNhaWRTY29yZX1cbiAgICAvPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cInNjb3JlLWNvbnRhaW5lclwiPlxuICAgIDxwIGNsYXNzPVwic2NvcmUtbGFiZWxcIj5cbiAgICAgIDxzbWFsbD5HdW5uaW5nIGZvZyBpbmRleDo8L3NtYWxsPlxuICAgICAgPHNwYW4gY2xhc3M9XCJzY29yZS12YWx1ZVwiPntndW5uaW5nRmxvZ1Njb3JlLnRvRml4ZWQoMil9PC9zcGFuPlxuICAgICAgPGJyLz5cbiAgICAgIDxzbWFsbCBjbGFzcz1cInNjb3JlLWxhYmVsXCI+e0d1bm5pbmdGbG9nU2NvcmVyLnNjb3JpbmdMZXZlbChndW5uaW5nRmxvZ1Njb3JlKX08L3NtYWxsPlxuICAgIDwvcD5cbiAgICA8VmFsdWVSYW5nZVxuICAgICAgbGVmdFZhbHVlPXtNSU5fR1VOTklOR19GTE9HfVxuICAgICAgcmlnaHRWYWx1ZT17TUFYX0dVTk5JTkdfRkxPR31cbiAgICAgIHZhbHVlPXtndW5uaW5nRmxvZ1Njb3JlfVxuICAgIC8+XG4gIDwvZGl2PlxuPC9kaXY+XG4iXSwic291cmNlUm9vdCI6IiJ9