(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/FleschKincaidScorer.js":
/*!***********************************************!*\
  !*** ./src/components/FleschKincaidScorer.js ***!
  \***********************************************/
/*! exports provided: MAX_FLESC_KINCAID, MIN_FLESC_KINCAID, FleschKincaidScorer */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MAX_FLESC_KINCAID", function() { return MAX_FLESC_KINCAID; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MIN_FLESC_KINCAID", function() { return MIN_FLESC_KINCAID; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FleschKincaidScorer", function() { return FleschKincaidScorer; });
/* harmony import */ var _helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../helpers/writtenLanguageHelpers */ "./src/helpers/writtenLanguageHelpers.js");


const MAX_FLESC_KINCAID = 120;
const MIN_FLESC_KINCAID = 0;

class FleschKincaidScorer {
  static calculate(text) {
    if (!text) {
      return MAX_FLESC_KINCAID;
    }

    const words = Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countWords"])(text);
    const asl = words / Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countSentences"])(text);
    const asw = Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countSyllables"])(text) / words;
    let score = 206.835 - (1.015 * asl) - (84.6 * asw);

    if (score > MAX_FLESC_KINCAID) {
      score = MAX_FLESC_KINCAID;
    } else if(score < MIN_FLESC_KINCAID) {
      score = MIN_FLESC_KINCAID;
    }

    return score;
  }
}


/***/ }),

/***/ "./src/components/FormGroup.svelte":
/*!*****************************************!*\
  !*** ./src/components/FormGroup.svelte ***!
  \*****************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/FormGroup.svelte generated by Svelte v3.7.1 */


const file = "src/components/FormGroup.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-zw7kt-style';
	style.textContent = ".form-group.svelte-zw7kt{display:flex;flex-direction:column}.label.svelte-zw7kt{font-size:1.2em;color:rgba(0, 0, 0, 0.1)}.label.active.svelte-zw7kt{color:rgba(0, 0, 0, 0.9)}.form-input.svelte-zw7kt{padding:0.5em;width:100% !important;min-height:10em}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRm9ybUdyb3VwLnN2ZWx0ZSIsInNvdXJjZXMiOlsiRm9ybUdyb3VwLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3R5bGUgbGFuZz1cInNjc3NcIj4uZm9ybS1ncm91cCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IH1cblxuLmxhYmVsIHtcbiAgZm9udC1zaXplOiAxLjJlbTtcbiAgY29sb3I6IHJnYmEoMCwgMCwgMCwgMC4xKTsgfVxuICAubGFiZWwuYWN0aXZlIHtcbiAgICBjb2xvcjogcmdiYSgwLCAwLCAwLCAwLjkpOyB9XG5cbi5mb3JtLWlucHV0IHtcbiAgcGFkZGluZzogMC41ZW07XG4gIHdpZHRoOiAxMDAlICFpbXBvcnRhbnQ7XG4gIG1pbi1oZWlnaHQ6IDEwZW07IH1cblxuLyojIHNvdXJjZU1hcHBpbmdVUkw9Rm9ybUdyb3VwLnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgZXhwb3J0IGxldCB2YWx1ZSA9IFwiXCJcblxuICBleHBvcnQgbGV0IHNlbGVjdGVkID0gXCJcIjtcbiAgZXhwb3J0IGxldCBsYWJlbFRleHQgPSBcIlwiO1xuICBleHBvcnQgbGV0IGlkID0gXCJcIjtcbiAgZXhwb3J0IGxldCBwbGFjZWhvbGRlciA9IFwiXCI7XG48L3NjcmlwdD5cblxuPGRpdiBjbGFzcz1cImZvcm0tZ3JvdXBcIj5cbiAgPGxhYmVsIGZvcj17aWR9IGNsYXNzPXtgbGFiZWwgJHtzZWxlY3RlZCA9PT0gaWQgPyBcImFjdGl2ZVwiIDogXCJcIn1gfT57bGFiZWxUZXh0fTwvbGFiZWw+XG4gIDx0ZXh0YXJlYVxuICAgIGlkPXtpZH1cbiAgICBjbGFzcz1cImZvcm0taW5wdXRcIlxuICAgIHR5cGU9XCJ0ZXh0XCJcbiAgICBiaW5kOnZhbHVlPXt2YWx1ZX1cbiAgICBwbGFjZWhvbGRlcj17cGxhY2Vob2xkZXJ9XG4gICAgYXJpYS1wbGFjZWhvbGRlcj17cGxhY2Vob2xkZXJ9XG4gIC8+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBbUIsV0FBVyxhQUFDLENBQUMsQUFDOUIsT0FBTyxDQUFFLElBQUksQ0FDYixjQUFjLENBQUUsTUFBTSxBQUFFLENBQUMsQUFFM0IsTUFBTSxhQUFDLENBQUMsQUFDTixTQUFTLENBQUUsS0FBSyxDQUNoQixLQUFLLENBQUUsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQUFBRSxDQUFDLEFBQzVCLE1BQU0sT0FBTyxhQUFDLENBQUMsQUFDYixLQUFLLENBQUUsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQUFBRSxDQUFDLEFBRWhDLFdBQVcsYUFBQyxDQUFDLEFBQ1gsT0FBTyxDQUFFLEtBQUssQ0FDZCxLQUFLLENBQUUsSUFBSSxDQUFDLFVBQVUsQ0FDdEIsVUFBVSxDQUFFLElBQUksQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var div, label, t0, label_class_value, t1, textarea, dispose;

	return {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("label");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.labelText);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			textarea = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("textarea");
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "LABEL", { for: true, class: true }, false);
			var label_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(label);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(label_nodes, ctx.labelText);
			label_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n  ");

			textarea = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "TEXTAREA", { id: true, class: true, type: true, placeholder: true, "aria-placeholder": true }, false);
			var textarea_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(textarea);

			textarea_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(label, "for", ctx.id);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(label, "class", label_class_value = "" + Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["null_to_empty"])((`label ${ctx.selected === ctx.id ? "active" : ""}`)) + " svelte-zw7kt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(label, file, 27, 2, 512);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "id", ctx.id);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "class", "form-input svelte-zw7kt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "type", "text");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "placeholder", ctx.placeholder);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "aria-placeholder", ctx.placeholder);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(textarea, file, 28, 2, 601);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", "form-group svelte-zw7kt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 26, 0, 485);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(textarea, "input", ctx.textarea_input_handler);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, label);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(label, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, textarea);

			textarea.value = ctx.value;
		},

		p: function update(changed, ctx) {
			if (changed.labelText) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, ctx.labelText);
			}

			if (changed.id) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(label, "for", ctx.id);
			}

			if ((changed.selected || changed.id) && label_class_value !== (label_class_value = "" + Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["null_to_empty"])((`label ${ctx.selected === ctx.id ? "active" : ""}`)) + " svelte-zw7kt")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(label, "class", label_class_value);
			}

			if (changed.value) textarea.value = ctx.value;

			if (changed.id) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "id", ctx.id);
			}

			if (changed.placeholder) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "placeholder", ctx.placeholder);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(textarea, "aria-placeholder", ctx.placeholder);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
			}

			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { value = "", selected = "", labelText = "", id = "", placeholder = "" } = $$props;

	const writable_props = ['value', 'selected', 'labelText', 'id', 'placeholder'];
	Object.keys($$props).forEach(key => {
		if (!writable_props.includes(key) && !key.startsWith('$$')) console.warn(`<FormGroup> was created with unknown prop '${key}'`);
	});

	function textarea_input_handler() {
		value = this.value;
		$$invalidate('value', value);
	}

	$$self.$set = $$props => {
		if ('value' in $$props) $$invalidate('value', value = $$props.value);
		if ('selected' in $$props) $$invalidate('selected', selected = $$props.selected);
		if ('labelText' in $$props) $$invalidate('labelText', labelText = $$props.labelText);
		if ('id' in $$props) $$invalidate('id', id = $$props.id);
		if ('placeholder' in $$props) $$invalidate('placeholder', placeholder = $$props.placeholder);
	};

	return {
		value,
		selected,
		labelText,
		id,
		placeholder,
		textarea_input_handler
	};
}

class FormGroup extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-zw7kt-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], ["value", "selected", "labelText", "id", "placeholder"]);
	}

	get value() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set value(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get selected() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set selected(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get labelText() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set labelText(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get id() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set id(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get placeholder() {
		throw new Error("<FormGroup>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set placeholder(value) {
		throw new Error("<FormGroup>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (FormGroup);

/***/ }),

/***/ "./src/components/GunningFlogScorer.js":
/*!*********************************************!*\
  !*** ./src/components/GunningFlogScorer.js ***!
  \*********************************************/
/*! exports provided: MIN_GUNNING_FLOG, MAX_GUNNING_FLOG, GunningFlogScorer */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MIN_GUNNING_FLOG", function() { return MIN_GUNNING_FLOG; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MAX_GUNNING_FLOG", function() { return MAX_GUNNING_FLOG; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "GunningFlogScorer", function() { return GunningFlogScorer; });
/* harmony import */ var _helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../helpers/writtenLanguageHelpers */ "./src/helpers/writtenLanguageHelpers.js");


const MIN_GUNNING_FLOG = 0;
const MAX_GUNNING_FLOG = 30;

const scoreToLevelMap = {
  20:	"Post-graduate Plus",
  19:	"Post-graduate",
  18:	"Post-graduate",
  17:	"College graduate",
  16:	"College senior",
  15:	"College junior",
  14:	"College sophomore",
  13:	"College freshman",
  12:	"High school senior",
  11:	"High school junior",
  10:	"High school sophomore",
  9:	"High school freshman",
  8:	"Eighth grade",
  7:	"Seventh grade",
  6:	"Sixth grade",
}

class GunningFlogScorer {
  static calculate(text) {
    if (!text) {
      return MIN_GUNNING_FLOG;
    }

    const words = Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countWords"])(text);
    const asl = words / Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countSentences"])(text);
    const phw = 100 * (Object(_helpers_writtenLanguageHelpers__WEBPACK_IMPORTED_MODULE_0__["countHardWords"])(text) / words);
    let score = 0.4 * (asl + phw)

    if (score > MAX_GUNNING_FLOG) {
      score = MAX_GUNNING_FLOG;
    } else if(score < MIN_GUNNING_FLOG) {
      score = MIN_GUNNING_FLOG;
    }

    return score;
  }
  static scoringLevel(score) {
    const integerScore = parseInt(score);
    const scores = Object.keys(scoreToLevelMap);
    const minScore = scores[0];
    const maxScore = scores[scores.length - 1];

    if (integerScore < minScore) {
      return "";
    };

    if (score > maxScore) {
      return scoreToLevelMap[maxScore]
    } else if (score < minScore) {
      return scoreToLevelMap[minScore]
    }

    return scoreToLevelMap[integerScore]
  }
}


/***/ }),

/***/ "./src/components/ValueRange.svelte":
/*!******************************************!*\
  !*** ./src/components/ValueRange.svelte ***!
  \******************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var svelte_motion__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte/motion */ "./node_modules/svelte/motion/index.mjs");
/* harmony import */ var svelte_easing__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! svelte/easing */ "./node_modules/svelte/easing/index.mjs");
/* harmony import */ var _helpers_createRGBValue__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../helpers/createRGBValue */ "./src/helpers/createRGBValue.js");
/* src/components/ValueRange.svelte generated by Svelte v3.7.1 */

const { document: document_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];





const file = "src/components/ValueRange.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1iazmd3-style';
	style.textContent = ".container.svelte-1iazmd3{text-align:center;width:100%}.valueContainer.svelte-1iazmd3{position:relative;width:50%;margin:0 auto;display:flex;align-items:center;height:1.5em}@media(max-width: 768px){.valueContainer.svelte-1iazmd3{width:100%}}.range.svelte-1iazmd3{height:2px;left:0;right:0;top:50%;transform:translateY(-50%);background-color:#ecf0f1;flex:1}.minValue.svelte-1iazmd3{left:0;transform:translate(-100%, -50%);position:absolute;top:50%;width:1px;height:1.5em;background-color:#34495e;border-radius:100px}.maxValue.svelte-1iazmd3{right:0;transform:translate(100%, -50%);position:absolute;top:50%;width:1px;height:1.5em;background-color:#34495e;border-radius:100px}.currentValue.svelte-1iazmd3{position:absolute;background-color:#34495e;width:3vw;height:3vw;max-width:1em;max-height:1em;border-radius:1000px;left:43%;top:50%;transform:translateY(-50%)}.limitLabel.svelte-1iazmd3{bottom:-100%;position:absolute;left:50%;transform:translateX(-50%)}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVmFsdWVSYW5nZS5zdmVsdGUiLCJzb3VyY2VzIjpbIlZhbHVlUmFuZ2Uuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzdHlsZSBsYW5nPVwic2Nzc1wiPi5jb250YWluZXIge1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIHdpZHRoOiAxMDAlOyB9XG5cbi52YWx1ZUNvbnRhaW5lciB7XG4gIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgd2lkdGg6IDUwJTtcbiAgbWFyZ2luOiAwIGF1dG87XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGhlaWdodDogMS41ZW07IH1cbiAgQG1lZGlhIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gICAgLnZhbHVlQ29udGFpbmVyIHtcbiAgICAgIHdpZHRoOiAxMDAlOyB9IH1cblxuLnJhbmdlIHtcbiAgaGVpZ2h0OiAycHg7XG4gIGxlZnQ6IDA7XG4gIHJpZ2h0OiAwO1xuICB0b3A6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC01MCUpO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZWNmMGYxO1xuICBmbGV4OiAxOyB9XG5cbi5taW5WYWx1ZSB7XG4gIGxlZnQ6IDA7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlKC0xMDAlLCAtNTAlKTtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICB0b3A6IDUwJTtcbiAgd2lkdGg6IDFweDtcbiAgaGVpZ2h0OiAxLjVlbTtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzM0NDk1ZTtcbiAgYm9yZGVyLXJhZGl1czogMTAwcHg7IH1cblxuLm1heFZhbHVlIHtcbiAgcmlnaHQ6IDA7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlKDEwMCUsIC01MCUpO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHRvcDogNTAlO1xuICB3aWR0aDogMXB4O1xuICBoZWlnaHQ6IDEuNWVtO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMzQ0OTVlO1xuICBib3JkZXItcmFkaXVzOiAxMDBweDsgfVxuXG4uY3VycmVudFZhbHVlIHtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMzQ0OTVlO1xuICB3aWR0aDogM3Z3O1xuICBoZWlnaHQ6IDN2dztcbiAgbWF4LXdpZHRoOiAxZW07XG4gIG1heC1oZWlnaHQ6IDFlbTtcbiAgYm9yZGVyLXJhZGl1czogMTAwMHB4O1xuICBsZWZ0OiA0MyU7XG4gIHRvcDogNTAlO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7IH1cblxuLmxpbWl0TGFiZWwge1xuICBib3R0b206IC0xMDAlO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIGxlZnQ6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC01MCUpOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPVZhbHVlUmFuZ2Uuc3ZlbHRlLmNzcy5tYXAgKi88L3N0eWxlPlxuXG48c2NyaXB0PlxuICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJztcbiAgaW1wb3J0IHsgdHdlZW5lZCB9IGZyb20gJ3N2ZWx0ZS9tb3Rpb24nO1xuICBpbXBvcnQgeyBjdWJpY091dCB9IGZyb20gJ3N2ZWx0ZS9lYXNpbmcnO1xuICBpbXBvcnQgeyBjcmVhdGVSR0JWYWx1ZSB9IGZyb20gXCIuLi9oZWxwZXJzL2NyZWF0ZVJHQlZhbHVlXCI7XG5cbiAgZXhwb3J0IGxldCBsZWZ0VmFsdWU7XG4gIGV4cG9ydCBsZXQgcmlnaHRWYWx1ZTtcbiAgZXhwb3J0IGxldCB2YWx1ZTtcbiAgZXhwb3J0IGxldCByZXZlcnNlID0gZmFsc2U7XG5cbiAgbGV0IGN1cnJlbnRFbGVtZW50V2lkdGggPSAwO1xuICBjb25zdCBjb2xvcnMgPSBbXG4gICAgeyByZWQ6IDQ2LCBncmVlbjogMjA0LCBibHVlOiAxMTMsIH0sXG4gICAgeyByZWQ6IDI0MywgZ3JlZW46IDE1NiwgYmx1ZTogMTgsIH0sXG4gICAgeyByZWQ6IDIzMSwgZ3JlZW46IDc2LCBibHVlOiA2MCwgfSxcbiAgXTtcbiAgY29uc3QgcHJvZ3Jlc3MgPSB0d2VlbmVkKDAsIHsgZHVyYXRpb246IDMwMCwgZWFzaW5nOiBjdWJpY091dCB9KTtcbiAgY29uc3Qgc2V0Q3VycmVudEVsZW1lbnRXaWR0aCA9ICgpID0+IHtcbiAgICBjdXJyZW50RWxlbWVudFdpZHRoID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIi5jdXJyZW50VmFsdWVcIikuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCkud2lkdGg7XG4gIH07XG5cbiAgJDogcHJvZ3Jlc3Muc2V0KHZhbHVlIC8gTWF0aC5tYXgocmlnaHRWYWx1ZSwgbGVmdFZhbHVlKSk7XG4gICQ6IGN1cnJlbnRWYWx1ZUVsZW1lbnRXaWR0aEhhc1RvQmVTdWJ0cmFjdGVkID0gKHJldmVyc2UgPyAkcHJvZ3Jlc3MgPCAwLjUgOiAkcHJvZ3Jlc3MgPiAwLjUpO1xuICAkOiBzdWJ0cmFjdFZhbHVlVG9QcmV2ZW50T3ZlcmZsb3cgPSBgJHtjdXJyZW50VmFsdWVFbGVtZW50V2lkdGhIYXNUb0JlU3VidHJhY3RlZCA/IGN1cnJlbnRFbGVtZW50V2lkdGggOiAwfXB4YDtcbiAgJDogY29sb3IgPSBjcmVhdGVSR0JWYWx1ZShyZXZlcnNlID8gMSAtICRwcm9ncmVzcyA6ICRwcm9ncmVzcywgY29sb3JzKTtcbiAgJDogcmdiID0gYHJnYigke2NvbG9yLnJlZH0sICR7Y29sb3IuZ3JlZW59LCAke2NvbG9yLmJsdWV9KWA7XG4gICQ6IGN1cnJlbnRWYWx1ZVN0eWxlID0gYGJhY2tncm91bmQtY29sb3I6ICR7cmdifTsgbGVmdDogY2FsYygke3JldmVyc2UgPyBcIjEwMCUgLSBcIiA6IFwiXCJ9JHskcHJvZ3Jlc3MgKiAxMDB9JSAtICR7c3VidHJhY3RWYWx1ZVRvUHJldmVudE92ZXJmbG93fSk7YDtcblxuICBvbk1vdW50KHNldEN1cnJlbnRFbGVtZW50V2lkdGgpO1xuPC9zY3JpcHQ+XG5cbjxzdmVsdGU6d2luZG93IG9uOnJlc2l6ZT17c2V0Q3VycmVudEVsZW1lbnRXaWR0aH0gLz5cblxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICA8ZGl2IGNsYXNzPVwidmFsdWVDb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwicmFuZ2VcIiAvPlxuICAgIDxkaXYgY2xhc3M9XCJtaW5WYWx1ZVwiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJsaW1pdExhYmVsXCI+e2xlZnRWYWx1ZX08L3NwYW4+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cIm1heFZhbHVlXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cImxpbWl0TGFiZWxcIj57cmlnaHRWYWx1ZX08L3NwYW4+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cImN1cnJlbnRWYWx1ZVwiIHN0eWxlPXtjdXJyZW50VmFsdWVTdHlsZX0gLz5cbiAgPC9kaXY+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBbUIsVUFBVSxlQUFDLENBQUMsQUFDN0IsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsS0FBSyxDQUFFLElBQUksQUFBRSxDQUFDLEFBRWhCLGVBQWUsZUFBQyxDQUFDLEFBQ2YsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsS0FBSyxDQUFFLEdBQUcsQ0FDVixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQ0FDZCxPQUFPLENBQUUsSUFBSSxDQUNiLFdBQVcsQ0FBRSxNQUFNLENBQ25CLE1BQU0sQ0FBRSxLQUFLLEFBQUUsQ0FBQyxBQUNoQixNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLGVBQWUsZUFBQyxDQUFDLEFBQ2YsS0FBSyxDQUFFLElBQUksQUFBRSxDQUFDLEFBQUMsQ0FBQyxBQUV0QixNQUFNLGVBQUMsQ0FBQyxBQUNOLE1BQU0sQ0FBRSxHQUFHLENBQ1gsSUFBSSxDQUFFLENBQUMsQ0FDUCxLQUFLLENBQUUsQ0FBQyxDQUNSLEdBQUcsQ0FBRSxHQUFHLENBQ1IsU0FBUyxDQUFFLFdBQVcsSUFBSSxDQUFDLENBQzNCLGdCQUFnQixDQUFFLE9BQU8sQ0FDekIsSUFBSSxDQUFFLENBQUMsQUFBRSxDQUFDLEFBRVosU0FBUyxlQUFDLENBQUMsQUFDVCxJQUFJLENBQUUsQ0FBQyxDQUNQLFNBQVMsQ0FBRSxVQUFVLEtBQUssQ0FBQyxDQUFDLElBQUksQ0FBQyxDQUNqQyxRQUFRLENBQUUsUUFBUSxDQUNsQixHQUFHLENBQUUsR0FBRyxDQUNSLEtBQUssQ0FBRSxHQUFHLENBQ1YsTUFBTSxDQUFFLEtBQUssQ0FDYixnQkFBZ0IsQ0FBRSxPQUFPLENBQ3pCLGFBQWEsQ0FBRSxLQUFLLEFBQUUsQ0FBQyxBQUV6QixTQUFTLGVBQUMsQ0FBQyxBQUNULEtBQUssQ0FBRSxDQUFDLENBQ1IsU0FBUyxDQUFFLFVBQVUsSUFBSSxDQUFDLENBQUMsSUFBSSxDQUFDLENBQ2hDLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLEdBQUcsQ0FBRSxHQUFHLENBQ1IsS0FBSyxDQUFFLEdBQUcsQ0FDVixNQUFNLENBQUUsS0FBSyxDQUNiLGdCQUFnQixDQUFFLE9BQU8sQ0FDekIsYUFBYSxDQUFFLEtBQUssQUFBRSxDQUFDLEFBRXpCLGFBQWEsZUFBQyxDQUFDLEFBQ2IsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsZ0JBQWdCLENBQUUsT0FBTyxDQUN6QixLQUFLLENBQUUsR0FBRyxDQUNWLE1BQU0sQ0FBRSxHQUFHLENBQ1gsU0FBUyxDQUFFLEdBQUcsQ0FDZCxVQUFVLENBQUUsR0FBRyxDQUNmLGFBQWEsQ0FBRSxNQUFNLENBQ3JCLElBQUksQ0FBRSxHQUFHLENBQ1QsR0FBRyxDQUFFLEdBQUcsQ0FDUixTQUFTLENBQUUsV0FBVyxJQUFJLENBQUMsQUFBRSxDQUFDLEFBRWhDLFdBQVcsZUFBQyxDQUFDLEFBQ1gsTUFBTSxDQUFFLEtBQUssQ0FDYixRQUFRLENBQUUsUUFBUSxDQUNsQixJQUFJLENBQUUsR0FBRyxDQUNULFNBQVMsQ0FBRSxXQUFXLElBQUksQ0FBQyxBQUFFLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document_1.head, style);
}

function create_fragment(ctx) {
	var div5, div4, div0, t0, div1, span0, t1, t2, div2, span1, t3, t4, div3, dispose;

	return {
		c: function create() {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.leftValue);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.rightValue);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			this.h()
		},

		l: function claim(nodes) {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, ctx.leftValue);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, ctx.rightValue);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n    ");

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true, style: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "range svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 100, 4, 2551);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "limitLabel svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 102, 6, 2606);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div1, "class", "minValue svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 101, 4, 2577);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "limitLabel svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 105, 6, 2694);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div2, "class", "maxValue svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 104, 4, 2665);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "class", "currentValue svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "style", ctx.currentValueStyle);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 107, 4, 2754);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div4, "class", "valueContainer svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 99, 2, 2518);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div5, "class", "container svelte-1iazmd3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 98, 0, 2492);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(window, "resize", ctx.setCurrentElementWidth);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div5, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div3);
		},

		p: function update(changed, ctx) {
			if (changed.leftValue) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, ctx.leftValue);
			}

			if (changed.rightValue) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t3, ctx.rightValue);
			}

			if (changed.currentValueStyle) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "style", ctx.currentValueStyle);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div5);
			}

			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $progress;

	

  let { leftValue, rightValue, value, reverse = false } = $$props;

  let currentElementWidth = 0;
  const colors = [
    { red: 46, green: 204, blue: 113, },
    { red: 243, green: 156, blue: 18, },
    { red: 231, green: 76, blue: 60, },
  ];
  const progress = Object(svelte_motion__WEBPACK_IMPORTED_MODULE_2__["tweened"])(0, { duration: 300, easing: svelte_easing__WEBPACK_IMPORTED_MODULE_3__["cubicOut"] }); Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(progress, 'progress'); Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, progress, $$value => { $progress = $$value; $$invalidate('$progress', $progress) });
  const setCurrentElementWidth = () => {
    $$invalidate('currentElementWidth', currentElementWidth = document.querySelector(".currentValue").getBoundingClientRect().width);
  };

  Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(setCurrentElementWidth);

	const writable_props = ['leftValue', 'rightValue', 'value', 'reverse'];
	Object.keys($$props).forEach(key => {
		if (!writable_props.includes(key) && !key.startsWith('$$')) console.warn(`<ValueRange> was created with unknown prop '${key}'`);
	});

	$$self.$set = $$props => {
		if ('leftValue' in $$props) $$invalidate('leftValue', leftValue = $$props.leftValue);
		if ('rightValue' in $$props) $$invalidate('rightValue', rightValue = $$props.rightValue);
		if ('value' in $$props) $$invalidate('value', value = $$props.value);
		if ('reverse' in $$props) $$invalidate('reverse', reverse = $$props.reverse);
	};

	let currentValueElementWidthHasToBeSubtracted, subtractValueToPreventOverflow, color, rgb, currentValueStyle;

	$$self.$$.update = ($$dirty = { value: 1, rightValue: 1, leftValue: 1, reverse: 1, $progress: 1, currentValueElementWidthHasToBeSubtracted: 1, currentElementWidth: 1, color: 1, rgb: 1, subtractValueToPreventOverflow: 1 }) => {
		if ($$dirty.value || $$dirty.rightValue || $$dirty.leftValue) { progress.set(value / Math.max(rightValue, leftValue)); }
		if ($$dirty.reverse || $$dirty.$progress) { $$invalidate('currentValueElementWidthHasToBeSubtracted', currentValueElementWidthHasToBeSubtracted = (reverse ? $progress < 0.5 : $progress > 0.5)); }
		if ($$dirty.currentValueElementWidthHasToBeSubtracted || $$dirty.currentElementWidth) { $$invalidate('subtractValueToPreventOverflow', subtractValueToPreventOverflow = `${currentValueElementWidthHasToBeSubtracted ? currentElementWidth : 0}px`); }
		if ($$dirty.reverse || $$dirty.$progress) { $$invalidate('color', color = Object(_helpers_createRGBValue__WEBPACK_IMPORTED_MODULE_4__["createRGBValue"])(reverse ? 1 - $progress : $progress, colors)); }
		if ($$dirty.color) { $$invalidate('rgb', rgb = `rgb(${color.red}, ${color.green}, ${color.blue})`); }
		if ($$dirty.rgb || $$dirty.reverse || $$dirty.$progress || $$dirty.subtractValueToPreventOverflow) { $$invalidate('currentValueStyle', currentValueStyle = `background-color: ${rgb}; left: calc(${reverse ? "100% - " : ""}${$progress * 100}% - ${subtractValueToPreventOverflow});`); }
	};

	return {
		leftValue,
		rightValue,
		value,
		reverse,
		progress,
		setCurrentElementWidth,
		currentValueStyle
	};
}

class ValueRange extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document_1.getElementById("svelte-1iazmd3-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], ["leftValue", "rightValue", "value", "reverse"]);

		const { ctx } = this.$$;
		const props = options.props || {};
		if (ctx.leftValue === undefined && !('leftValue' in props)) {
			console.warn("<ValueRange> was created without expected prop 'leftValue'");
		}
		if (ctx.rightValue === undefined && !('rightValue' in props)) {
			console.warn("<ValueRange> was created without expected prop 'rightValue'");
		}
		if (ctx.value === undefined && !('value' in props)) {
			console.warn("<ValueRange> was created without expected prop 'value'");
		}
	}

	get leftValue() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set leftValue(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get rightValue() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set rightValue(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get value() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set value(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get reverse() {
		throw new Error("<ValueRange>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set reverse(value) {
		throw new Error("<ValueRange>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (ValueRange);

/***/ }),

/***/ "./src/helpers/createRGBValue.js":
/*!***************************************!*\
  !*** ./src/helpers/createRGBValue.js ***!
  \***************************************/
/*! exports provided: createRGBValue */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "createRGBValue", function() { return createRGBValue; });
function interpolate(value, min, max) {
  var delta = max - min;
  var stepValue = delta / 100;
  return min + stepValue * Math.floor(value * 100);
}

/**
 * Create an RGB value located between 3 colors
 *
 * @param {number} value - Value between 0 and 1
 * @param {{ red: number; green: number; blue: number; }[]} colors - Array of rgb colors
 */
function createRGBValue(value, colors) {
  let red;
  let green;
  let blue;

  const [
    startColor,
    midColor,
    endColor,
  ] = colors;

  if (value > 0.5) {
    red = interpolate((value - 0.5) / 0.5, midColor.red, endColor.red);
  } else {
    red = interpolate(value / 0.5, startColor.red, midColor.red);
  }

  if (value > 0.5) {
    green = interpolate((value - 0.5) / 0.5, midColor.green, endColor.green);
  } else {
    green = interpolate(value / 0.5, startColor.green, midColor.green);
  }

  if (value > 0.5) {
    blue = interpolate((value - 0.5) / 0.5, midColor.blue, endColor.blue);
  } else {
    blue = interpolate(value / 0.5, startColor.blue, midColor.blue);
  }

  return {
    red,
    green,
    blue,
  };
}


/***/ }),

/***/ "./src/helpers/writtenLanguageHelpers.js":
/*!***********************************************!*\
  !*** ./src/helpers/writtenLanguageHelpers.js ***!
  \***********************************************/
/*! exports provided: countWords, findWords, countSentences, countHardWords, countSyllables */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countWords", function() { return countWords; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "findWords", function() { return findWords; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countSentences", function() { return countSentences; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countHardWords", function() { return countHardWords; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "countSyllables", function() { return countSyllables; });
/* harmony import */ var syllable__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! syllable */ "./node_modules/syllable/index.js");
/* harmony import */ var syllable__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(syllable__WEBPACK_IMPORTED_MODULE_0__);


function countWords(text) {
  return findWords(text).length || 1;
}

function findWords(text) {
  return text.match(/([^\u0000-\u007F]|\w)+/g) || [];
}

function countSentences(text) {
  const match = text.match(/[\w]\)?[.?!](\s|$)/g) || [];
  return match.length || 1;
}

function countHardWords(text) {
  const textLower = text.toLowerCase();
  let count = 0;

  findWords(textLower).forEach(word => {
    if (countWordSyllables(word) >= 3) {
      count += 1;
    }
  })

  return count;
}

function countSyllables(text) {
  const textLower = text.toLowerCase();
  let count = 0;

  findWords(textLower).forEach(word=> {
    count += countWordSyllables(word);
  })

  return count

}

function countWordSyllables(originalWord) {
  return syllable__WEBPACK_IMPORTED_MODULE_0___default()(originalWord)
}


/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_FormGroup_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/FormGroup.svelte */ "./src/components/FormGroup.svelte");
/* harmony import */ var _components_ValueRange_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/ValueRange.svelte */ "./src/components/ValueRange.svelte");
/* harmony import */ var _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/FleschKincaidScorer.js */ "./src/components/FleschKincaidScorer.js");
/* harmony import */ var _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../components/GunningFlogScorer.js */ "./src/components/GunningFlogScorer.js");
/* src/routes/index.svelte generated by Svelte v3.7.1 */






const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-29m5oy-style';
	style.textContent = ".svelte-29m5oy{font-family:\"Montserrat\", sans-serif}input,textarea{box-shadow:0 0 0.5em rgba(0, 0, 0, 0.1);-webkit-appearance:none;border:0;font-family:inherit;font-size:inherit}.container.svelte-29m5oy{display:flex;flex-direction:column;text-align:center}.score-container.svelte-29m5oy{margin:1em 0}.score-label.svelte-29m5oy{margin:0;color:#34495e}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN0eWxlIGxhbmc9XCJzY3NzXCI+KiB7XG4gIGZvbnQtZmFtaWx5OiBcIk1vbnRzZXJyYXRcIiwgc2Fucy1zZXJpZjsgfVxuXG46Z2xvYmFsKGlucHV0KSxcbjpnbG9iYWwodGV4dGFyZWEpIHtcbiAgYm94LXNoYWRvdzogMCAwIDAuNWVtIHJnYmEoMCwgMCwgMCwgMC4xKTtcbiAgLXdlYmtpdC1hcHBlYXJhbmNlOiBub25lO1xuICBib3JkZXI6IDA7XG4gIGZvbnQtZmFtaWx5OiBpbmhlcml0O1xuICBmb250LXNpemU6IGluaGVyaXQ7IH1cblxuLmNvbnRhaW5lciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gIHRleHQtYWxpZ246IGNlbnRlcjsgfVxuXG4uc2NvcmUtY29udGFpbmVyIHtcbiAgbWFyZ2luOiAxZW0gMDsgfVxuXG4uc2NvcmUtbGFiZWwge1xuICBtYXJnaW46IDA7XG4gIGNvbG9yOiAjMzQ0OTVlOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IEZvcm1Hcm91cCBmcm9tIFwiLi4vY29tcG9uZW50cy9Gb3JtR3JvdXAuc3ZlbHRlXCI7XG4gIGltcG9ydCBWYWx1ZVJhbmdlIGZyb20gXCIuLi9jb21wb25lbnRzL1ZhbHVlUmFuZ2Uuc3ZlbHRlXCI7XG4gIGltcG9ydCB7XG4gICAgRmxlc2NoS2luY2FpZFNjb3JlcixcbiAgICBNQVhfRkxFU0NfS0lOQ0FJRCxcbiAgICBNSU5fRkxFU0NfS0lOQ0FJRCxcbiAgfSBmcm9tIFwiLi4vY29tcG9uZW50cy9GbGVzY2hLaW5jYWlkU2NvcmVyLmpzXCI7XG4gIGltcG9ydCB7XG4gICAgR3VubmluZ0Zsb2dTY29yZXIsXG4gICAgTUFYX0dVTk5JTkdfRkxPRyxcbiAgICBNSU5fR1VOTklOR19GTE9HLFxuICB9IGZyb20gXCIuLi9jb21wb25lbnRzL0d1bm5pbmdGbG9nU2NvcmVyLmpzXCI7XG5cbiAgbGV0IHN1YmplY3RUZXh0ID0gXCJcIjtcbiAgJDogZmxlc2NoS2luY2FpZFNjb3JlID0gRmxlc2NoS2luY2FpZFNjb3Jlci5jYWxjdWxhdGUoc3ViamVjdFRleHQpO1xuICAkOiBndW5uaW5nRmxvZ1Njb3JlID0gR3VubmluZ0Zsb2dTY29yZXIuY2FsY3VsYXRlKHN1YmplY3RUZXh0KTtcbjwvc2NyaXB0PlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5UZXh0IFNjb3JlPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgPGgxPkhvdyByZWFkYWJsZSBpcyB5b3VyIHRleHQ/PC9oMT5cbiAgPHNtYWxsPjwvc21hbGw+XG4gIDxoci8+XG4gIDxGb3JtR3JvdXBcbiAgICBpZD17XCJzdWJqZWN0VGV4dFwifVxuICAgIGJpbmQ6dmFsdWU9e3N1YmplY3RUZXh0fVxuICAgIHBsYWNlaG9sZGVyPVwiV3JpdGUgeW91ciB0ZXh0IGhlcmUgYW5kIHNlZSB0aGUgc2NvcmUgYmVpbmcgY2FsY3VsYXRlZFwiXG4gIC8+XG4gIDxkaXYgY2xhc3M9XCJzY29yZS1jb250YWluZXJcIj5cbiAgICA8cCBjbGFzcz1cInNjb3JlLWxhYmVsXCI+XG4gICAgICA8c21hbGw+Rmxlc2NoIEtpbmNhaWQgUmVhZGluZyBFYXNlOjwvc21hbGw+XG4gICAgICA8c3BhbiBjbGFzcz1cInNjb3JlLXZhbHVlXCI+e2ZsZXNjaEtpbmNhaWRTY29yZS50b0ZpeGVkKDIpfTwvc3Bhbj5cbiAgICA8L3A+XG4gICAgPFZhbHVlUmFuZ2VcbiAgICAgIHJldmVyc2U9e3RydWV9XG4gICAgICByaWdodFZhbHVlPXtNSU5fRkxFU0NfS0lOQ0FJRH1cbiAgICAgIGxlZnRWYWx1ZT17TUFYX0ZMRVNDX0tJTkNBSUR9XG4gICAgICB2YWx1ZT17Zmxlc2NoS2luY2FpZFNjb3JlfVxuICAgIC8+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwic2NvcmUtY29udGFpbmVyXCI+XG4gICAgPHAgY2xhc3M9XCJzY29yZS1sYWJlbFwiPlxuICAgICAgPHNtYWxsPkd1bm5pbmcgZm9nIGluZGV4Ojwvc21hbGw+XG4gICAgICA8c3BhbiBjbGFzcz1cInNjb3JlLXZhbHVlXCI+e2d1bm5pbmdGbG9nU2NvcmUudG9GaXhlZCgyKX08L3NwYW4+XG4gICAgICA8YnIvPlxuICAgICAgPHNtYWxsIGNsYXNzPVwic2NvcmUtbGFiZWxcIj57R3VubmluZ0Zsb2dTY29yZXIuc2NvcmluZ0xldmVsKGd1bm5pbmdGbG9nU2NvcmUpfTwvc21hbGw+XG4gICAgPC9wPlxuICAgIDxWYWx1ZVJhbmdlXG4gICAgICBsZWZ0VmFsdWU9e01JTl9HVU5OSU5HX0ZMT0d9XG4gICAgICByaWdodFZhbHVlPXtNQVhfR1VOTklOR19GTE9HfVxuICAgICAgdmFsdWU9e2d1bm5pbmdGbG9nU2NvcmV9XG4gICAgLz5cbiAgPC9kaXY+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBbUIsY0FBRSxDQUFDLEFBQ3BCLFdBQVcsQ0FBRSxZQUFZLENBQUMsQ0FBQyxVQUFVLEFBQUUsQ0FBQyxBQUVsQyxLQUFLLEFBQUMsQ0FDTixRQUFRLEFBQUUsQ0FBQyxBQUNqQixVQUFVLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FDeEMsa0JBQWtCLENBQUUsSUFBSSxDQUN4QixNQUFNLENBQUUsQ0FBQyxDQUNULFdBQVcsQ0FBRSxPQUFPLENBQ3BCLFNBQVMsQ0FBRSxPQUFPLEFBQUUsQ0FBQyxBQUV2QixVQUFVLGNBQUMsQ0FBQyxBQUNWLE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLE1BQU0sQ0FDdEIsVUFBVSxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBRXZCLGdCQUFnQixjQUFDLENBQUMsQUFDaEIsTUFBTSxDQUFFLEdBQUcsQ0FBQyxDQUFDLEFBQUUsQ0FBQyxBQUVsQixZQUFZLGNBQUMsQ0FBQyxBQUNaLE1BQU0sQ0FBRSxDQUFDLENBQ1QsS0FBSyxDQUFFLE9BQU8sQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div2, h1, t1, t2, small0, t3, hr, t4, updating_value, t5, div0, p0, small1, t6, t7, span0, t8_value = ctx.fleschKincaidScore.toFixed(2), t8, t9, t10, div1, p1, small2, t11, t12, span1, t13_value = ctx.gunningFlogScore.toFixed(2), t13, t14, br, t15, small3, t16_value = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["GunningFlogScorer"].scoringLevel(ctx.gunningFlogScore), t16, t17, current;

	function formgroup_value_binding(value) {
		ctx.formgroup_value_binding.call(null, value);
		updating_value = true;
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_value = false);
	}

	let formgroup_props = {
		id: "subjectText",
		placeholder: "Write your text here and see the score being calculated"
	};
	if (ctx.subjectText !== void 0) {
		formgroup_props.value = ctx.subjectText;
	}
	var formgroup = new _components_FormGroup_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ props: formgroup_props, $$inline: true });

	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(formgroup, 'value', formgroup_value_binding));

	var valuerange0 = new _components_ValueRange_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({
		props: {
		reverse: true,
		rightValue: _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["MIN_FLESC_KINCAID"],
		leftValue: _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["MAX_FLESC_KINCAID"],
		value: ctx.fleschKincaidScore
	},
		$$inline: true
	});

	var valuerange1 = new _components_ValueRange_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({
		props: {
		leftValue: _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["MIN_GUNNING_FLOG"],
		rightValue: _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["MAX_GUNNING_FLOG"],
		value: ctx.gunningFlogScore
	},
		$$inline: true
	});

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("How readable is your text?");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			small0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			hr = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			formgroup.$$.fragment.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			small1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Flesch Kincaid Reading Ease:");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t8_value);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			valuerange0.$$.fragment.c();
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			small2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Gunning fog index:");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t13_value);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			small3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("small");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t16_value);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			valuerange1.$$.fragment.c();
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "How readable is your text?");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");

			small0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "SMALL", { class: true }, false);
			var small0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small0);

			small0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");

			hr = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "HR", { class: true }, false);
			var hr_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(hr);

			hr_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");
			formgroup.$$.fragment.l(div2_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			small1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "SMALL", { class: true }, false);
			var small1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small1);

			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small1_nodes, "Flesch Kincaid Reading Ease:");
			small1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n      ");

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t8_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div0_nodes, "\n    ");
			valuerange0.$$.fragment.l(div0_nodes);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n  ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			small2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "SMALL", { class: true }, false);
			var small2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small2);

			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small2_nodes, "Gunning fog index:");
			small2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n      ");

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, t13_value);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n      ");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "BR", { class: true }, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n      ");

			small3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "SMALL", { class: true }, false);
			var small3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(small3);

			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(small3_nodes, t16_value);
			small3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n    ");
			valuerange1.$$.fragment.l(div1_nodes);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Text Score";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h1, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 49, 2, 1099);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small0, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small0, file, 50, 2, 1137);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(hr, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr, file, 51, 2, 1155);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small1, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small1, file, 59, 6, 1371);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "score-value svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 60, 6, 1421);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "score-label svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 58, 4, 1341);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "score-container svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 57, 2, 1307);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small2, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small2, file, 71, 6, 1720);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "score-value svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 72, 6, 1760);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(br, "class", "svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 73, 6, 1829);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(small3, "class", "score-label svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(small3, file, 74, 6, 1841);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "score-label svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 70, 4, 1690);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div1, "class", "score-container svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 69, 2, 1656);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div2, "class", "container svelte-29m5oy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 48, 0, 1073);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, small0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, hr);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(formgroup, div2, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, small1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(small1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(valuerange0, div0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, small2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(small2, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, small3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(small3, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(valuerange1, div1, null);
			current = true;
		},

		p: function update(changed, ctx) {
			var formgroup_changes = {};
			if (!updating_value && changed.subjectText) {
				formgroup_changes.value = ctx.subjectText;
			}
			formgroup.$set(formgroup_changes);

			if ((!current || changed.fleschKincaidScore) && t8_value !== (t8_value = ctx.fleschKincaidScore.toFixed(2))) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t8, t8_value);
			}

			var valuerange0_changes = {};
			if (changed.MIN_FLESC_KINCAID) valuerange0_changes.rightValue = _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["MIN_FLESC_KINCAID"];
			if (changed.MAX_FLESC_KINCAID) valuerange0_changes.leftValue = _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["MAX_FLESC_KINCAID"];
			if (changed.fleschKincaidScore) valuerange0_changes.value = ctx.fleschKincaidScore;
			valuerange0.$set(valuerange0_changes);

			if ((!current || changed.gunningFlogScore) && t13_value !== (t13_value = ctx.gunningFlogScore.toFixed(2))) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t13, t13_value);
			}

			if ((!current || changed.gunningFlogScore) && t16_value !== (t16_value = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["GunningFlogScorer"].scoringLevel(ctx.gunningFlogScore))) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t16, t16_value);
			}

			var valuerange1_changes = {};
			if (changed.MIN_GUNNING_FLOG) valuerange1_changes.leftValue = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["MIN_GUNNING_FLOG"];
			if (changed.MAX_GUNNING_FLOG) valuerange1_changes.rightValue = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["MAX_GUNNING_FLOG"];
			if (changed.gunningFlogScore) valuerange1_changes.value = ctx.gunningFlogScore;
			valuerange1.$set(valuerange1_changes);
		},

		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(formgroup.$$.fragment, local);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(valuerange0.$$.fragment, local);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(valuerange1.$$.fragment, local);

			current = true;
		},

		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(formgroup.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(valuerange0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(valuerange1.$$.fragment, local);
			current = false;
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div2);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(formgroup);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(valuerange0);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(valuerange1);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	

  let subjectText = "";

	function formgroup_value_binding(value) {
		subjectText = value;
		$$invalidate('subjectText', subjectText);
	}

	let fleschKincaidScore, gunningFlogScore;

	$$self.$$.update = ($$dirty = { subjectText: 1 }) => {
		if ($$dirty.subjectText) { $$invalidate('fleschKincaidScore', fleschKincaidScore = _components_FleschKincaidScorer_js__WEBPACK_IMPORTED_MODULE_3__["FleschKincaidScorer"].calculate(subjectText)); }
		if ($$dirty.subjectText) { $$invalidate('gunningFlogScore', gunningFlogScore = _components_GunningFlogScorer_js__WEBPACK_IMPORTED_MODULE_4__["GunningFlogScorer"].calculate(subjectText)); }
	};

	return {
		subjectText,
		fleschKincaidScore,
		gunningFlogScore,
		formgroup_value_binding
	};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-29m5oy-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9jb21wb25lbnRzL0ZsZXNjaEtpbmNhaWRTY29yZXIuanMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9Gb3JtR3JvdXAuc3ZlbHRlIiwid2VicGFjazovLy93ZWJwYWNrOi8vLy4vc3JjL2NvbXBvbmVudHMvR3VubmluZ0Zsb2dTY29yZXIuanMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9WYWx1ZVJhbmdlLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9oZWxwZXJzL2NyZWF0ZVJHQlZhbHVlLmpzIiwid2VicGFjazovLy93ZWJwYWNrOi8vLy4vc3JjL2hlbHBlcnMvd3JpdHRlbkxhbmd1YWdlSGVscGVycy5qcyIsIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9yb3V0ZXMvaW5kZXguc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBSTJDOztBQUVwQztBQUNBOztBQUVBO0FBQ1A7QUFDQTtBQUNBO0FBQ0E7O0FBRUEsa0JBQWtCLGtGQUFVO0FBQzVCLHdCQUF3QixzRkFBYztBQUN0QyxnQkFBZ0Isc0ZBQWM7QUFDOUI7O0FBRUE7QUFDQTtBQUNBLEtBQUs7QUFDTDtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5RUNEc0UsU0FBUzs7Ozs7Ozs7Ozs7Ozs0RkFBVCxTQUFTOzs7Ozs7Ozs7Ozs7O2tGQUFqRSxFQUFFO2dMQUFTLENBQUMsTUFBTSxNQUFFLFFBQVEsU0FBSyxFQUFFLEdBQUcsUUFBUSxHQUFHLEVBQUUsQ0FBQyxDQUFDOztvRkFFM0QsRUFBRTs7OzZGQUlPLFdBQVc7a0dBQ04sV0FBVzs7Ozs7Ozs7Ozs7Ozs7d0JBRmpCLEtBQUs7Ozs7OzZFQUxpRCxTQUFTOzs7O21GQUFqRSxFQUFFOzs7a0tBQVMsQ0FBQyxNQUFNLE1BQUUsUUFBUSxTQUFLLEVBQUUsR0FBRyxRQUFRLEdBQUcsRUFBRSxDQUFDLENBQUM7Ozs7MkNBS25ELEtBQUs7OztxRkFIYixFQUFFOzs7OzhGQUlPLFdBQVc7bUdBQ04sV0FBVzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0NBaEJ4QixNQUFJLEtBQUssR0FBRyxFQUFFLEVBRVYsUUFBUSxHQUFHLEVBQUUsRUFDYixTQUFTLEdBQUcsRUFBRSxFQUNkLEVBQUUsR0FBRyxFQUFFLEVBQ1AsV0FBVyxHQUFHLGNBQUUsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDdkI5QjtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBSTJDOztBQUVwQztBQUNBOztBQUVQO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRU87QUFDUDtBQUNBO0FBQ0E7QUFDQTs7QUFFQSxrQkFBa0Isa0ZBQVU7QUFDNUIsd0JBQXdCLHNGQUFjO0FBQ3RDLHVCQUF1QixzRkFBYztBQUNyQzs7QUFFQTtBQUNBO0FBQ0EsS0FBSztBQUNMO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQSxLQUFLO0FBQ0w7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lFQ3NDZ0MsU0FBUzs7Ozt5RUFHVCxVQUFVOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzRGQUhWLFNBQVM7Ozs7Ozs7Ozs7OzRGQUdULFVBQVU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O21GQUVMLGlCQUFpQjs7Ozs7O2tHQVg1QixzQkFBc0I7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2RUFNaEIsU0FBUzs7Ozs2RUFHVCxVQUFVOzs7O29GQUVMLGlCQUFpQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Q0F2Q087O0VBRXBELE1BQUksU0FBUyxFQUNULFVBQVUsRUFDVixLQUFLLEVBQ0wsT0FBTyxHQUFHLGlCQUFLLENBQUM7O0VBRTNCLElBQUksbUJBQW1CLEdBQUcsQ0FBQyxDQUFDO0VBQzVCLE1BQU0sTUFBTSxHQUFHO0lBQ2IsRUFBRSxHQUFHLEVBQUUsRUFBRSxFQUFFLEtBQUssRUFBRSxHQUFHLEVBQUUsSUFBSSxFQUFFLEdBQUcsR0FBRztJQUNuQyxFQUFFLEdBQUcsRUFBRSxHQUFHLEVBQUUsS0FBSyxFQUFFLEdBQUcsRUFBRSxJQUFJLEVBQUUsRUFBRSxHQUFHO0lBQ25DLEVBQUUsR0FBRyxFQUFFLEdBQUcsRUFBRSxLQUFLLEVBQUUsRUFBRSxFQUFFLElBQUksRUFBRSxFQUFFLEdBQUc7R0FDbkMsQ0FBQztFQUNGLE1BQU0sUUFBUSxHQUFHLDZEQUFPLENBQUMsQ0FBQyxFQUFFLEVBQUUsUUFBUSxFQUFFLEdBQUcsRUFBRSxNQUFNLEVBQUUsc0RBQVEsRUFBRSx3UUFBQyxDQUFDO0VBQ2pFLE1BQU0sc0JBQXNCLEdBQUcsTUFBTTt3Q0FDbkMsbUJBQW1CLEdBQUcsUUFBUSxDQUFDLGFBQWEsQ0FBQyxlQUFlLENBQUMsQ0FBQyxxQkFBcUIsRUFBRSxDQUFDLE1BQUssQ0FBQztHQUM3RixDQU9rSjs7RUFFbkosc0RBQU8sQ0FBQyxzQkFBc0IsQ0FBQyxDQUFDOzs7Ozs7Ozs7Ozs7Ozs7OztrRUFQN0IsUUFBUSxDQUFDLEdBQUcsQ0FBQyxLQUFLLEdBQUcsSUFBSSxDQUFDLEdBQUcsQ0FBQyxVQUFVLEVBQUUsU0FBUyxDQUFDLENBQUMsQ0FBQzt3R0FDdEQseUNBQXlDLEdBQUcsQ0FBQyxPQUFPLEdBQUcsU0FBUyxHQUFHLEdBQUcsR0FBRyxTQUFTLEdBQUcsR0FBRyxFQUFDLENBQUM7eUlBQzFGLDhCQUE4QixHQUFHLENBQUMsRUFBRSx5Q0FBeUMsR0FBRyxtQkFBbUIsR0FBRyxDQUFDLENBQUMsRUFBRSxFQUFDLENBQUM7b0VBQzVHLEtBQUssR0FBRyw4RUFBYyxDQUFDLE9BQU8sR0FBRyxDQUFDLEdBQUcsU0FBUyxHQUFHLFNBQVMsRUFBRSxNQUFNLEVBQUMsQ0FBQzsyQ0FDcEUsR0FBRyxHQUFHLENBQUMsSUFBSSxFQUFFLEtBQUssQ0FBQyxHQUFHLENBQUMsRUFBRSxFQUFFLEtBQUssQ0FBQyxLQUFLLENBQUMsRUFBRSxFQUFFLEtBQUssQ0FBQyxJQUFJLENBQUMsQ0FBQyxFQUFDLENBQUM7eUlBQ3pELGlCQUFpQixHQUFHLENBQUMsa0JBQWtCLEVBQUUsR0FBRyxDQUFDLGFBQWEsRUFBRSxPQUFPLEdBQUcsU0FBUyxHQUFHLEVBQUUsQ0FBQyxFQUFFLFNBQVMsR0FBRyxHQUFHLENBQUMsSUFBSSxFQUFFLDhCQUE4QixDQUFDLEVBQUUsRUFBQyxDQUFDOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUMzRnJKO0FBQUE7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBLFdBQVcsT0FBTztBQUNsQixZQUFZLGFBQWEsZUFBZSxjQUFjLEVBQUUsR0FBRztBQUMzRDtBQUNPO0FBQ1A7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBLEdBQUc7QUFDSDtBQUNBOztBQUVBO0FBQ0E7QUFDQSxHQUFHO0FBQ0g7QUFDQTs7QUFFQTtBQUNBO0FBQ0EsR0FBRztBQUNIO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOzs7Ozs7Ozs7Ozs7O0FDOUNBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBZ0M7O0FBRXpCO0FBQ1A7QUFDQTs7QUFFTztBQUNQO0FBQ0E7O0FBRU87QUFDUDtBQUNBO0FBQ0E7O0FBRU87QUFDUDtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsR0FBRzs7QUFFSDtBQUNBOztBQUVPO0FBQ1A7QUFDQTs7QUFFQTtBQUNBO0FBQ0EsR0FBRzs7QUFFSDs7QUFFQTs7QUFFQTtBQUNBLFNBQVMsK0NBQVE7QUFDakI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttSENrQmlDLGtCQUFrQixDQUFDLE9BQU8sQ0FBQyxDQUFDLENBQUMsa0VBWTdCLGdCQUFnQixDQUFDLE9BQU8sQ0FBQyxDQUFDLENBQUMseUNBRTFCLGtGQUFpQixDQUFDLFlBQVksS0FBQyxnQkFBZ0IsQ0FBQzs7Ozs7Ozs7O01BckIxRSxhQUFhOzs7U0FDTCxXQUFXOzhCQUFYLFdBQVc7Ozs7Ozs7O1dBU1osSUFBSTtjQUNELG9GQUFpQjthQUNsQixvRkFBaUI7YUFDckIsa0JBQWtCOzs7Ozs7O2FBV2QsaUZBQWdCO2NBQ2YsaUZBQWdCO2FBQ3JCLGdCQUFnQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7a0NBekJiLFdBQVc7Ozs7Z0ZBTU0sa0JBQWtCLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQzs7Ozs7bUVBSTVDLG9GQUFpQjtrRUFDbEIsb0ZBQWlCO21FQUNyQixrQkFBa0I7OztnRkFNRSxnQkFBZ0IsQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDOzs7OzRFQUUxQixrRkFBaUIsQ0FBQyxZQUFZLEtBQUMsZ0JBQWdCLENBQUM7Ozs7O2lFQUdqRSxpRkFBZ0I7a0VBQ2YsaUZBQWdCO2lFQUNyQixnQkFBZ0I7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0NBMUNpQjs7RUFFNUMsSUFBSSxXQUFXLEdBQUcsRUFBRSxDQUFDOzs7Ozs7Ozs7O2dFQUNsQixrQkFBa0IsR0FBRyxzRkFBbUIsQ0FBQyxTQUFTLENBQUMsV0FBVyxFQUFDLENBQUM7OERBQ2hFLGdCQUFnQixHQUFHLGtGQUFpQixDQUFDLFNBQVMsQ0FBQyxXQUFXLEVBQUMsQ0FBQyIsImZpbGUiOiJiNmU4YTYyYWIwMmNmNjkwYTI3YS9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7XG4gIGNvdW50U2VudGVuY2VzLFxuICBjb3VudFN5bGxhYmxlcyxcbiAgY291bnRXb3Jkcyxcbn0gZnJvbSBcIi4uL2hlbHBlcnMvd3JpdHRlbkxhbmd1YWdlSGVscGVyc1wiO1xuXG5leHBvcnQgY29uc3QgTUFYX0ZMRVNDX0tJTkNBSUQgPSAxMjA7XG5leHBvcnQgY29uc3QgTUlOX0ZMRVNDX0tJTkNBSUQgPSAwO1xuXG5leHBvcnQgY2xhc3MgRmxlc2NoS2luY2FpZFNjb3JlciB7XG4gIHN0YXRpYyBjYWxjdWxhdGUodGV4dCkge1xuICAgIGlmICghdGV4dCkge1xuICAgICAgcmV0dXJuIE1BWF9GTEVTQ19LSU5DQUlEO1xuICAgIH1cblxuICAgIGNvbnN0IHdvcmRzID0gY291bnRXb3Jkcyh0ZXh0KTtcbiAgICBjb25zdCBhc2wgPSB3b3JkcyAvIGNvdW50U2VudGVuY2VzKHRleHQpO1xuICAgIGNvbnN0IGFzdyA9IGNvdW50U3lsbGFibGVzKHRleHQpIC8gd29yZHM7XG4gICAgbGV0IHNjb3JlID0gMjA2LjgzNSAtICgxLjAxNSAqIGFzbCkgLSAoODQuNiAqIGFzdyk7XG5cbiAgICBpZiAoc2NvcmUgPiBNQVhfRkxFU0NfS0lOQ0FJRCkge1xuICAgICAgc2NvcmUgPSBNQVhfRkxFU0NfS0lOQ0FJRDtcbiAgICB9IGVsc2UgaWYoc2NvcmUgPCBNSU5fRkxFU0NfS0lOQ0FJRCkge1xuICAgICAgc2NvcmUgPSBNSU5fRkxFU0NfS0lOQ0FJRDtcbiAgICB9XG5cbiAgICByZXR1cm4gc2NvcmU7XG4gIH1cbn1cbiIsIjxzdHlsZSBsYW5nPVwic2Nzc1wiPi5mb3JtLWdyb3VwIHtcbiAgZGlzcGxheTogZmxleDtcbiAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsgfVxuXG4ubGFiZWwge1xuICBmb250LXNpemU6IDEuMmVtO1xuICBjb2xvcjogcmdiYSgwLCAwLCAwLCAwLjEpOyB9XG4gIC5sYWJlbC5hY3RpdmUge1xuICAgIGNvbG9yOiByZ2JhKDAsIDAsIDAsIDAuOSk7IH1cblxuLmZvcm0taW5wdXQge1xuICBwYWRkaW5nOiAwLjVlbTtcbiAgd2lkdGg6IDEwMCUgIWltcG9ydGFudDtcbiAgbWluLWhlaWdodDogMTBlbTsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1Gb3JtR3JvdXAuc3ZlbHRlLmNzcy5tYXAgKi88L3N0eWxlPlxuXG48c2NyaXB0PlxuICBleHBvcnQgbGV0IHZhbHVlID0gXCJcIlxuXG4gIGV4cG9ydCBsZXQgc2VsZWN0ZWQgPSBcIlwiO1xuICBleHBvcnQgbGV0IGxhYmVsVGV4dCA9IFwiXCI7XG4gIGV4cG9ydCBsZXQgaWQgPSBcIlwiO1xuICBleHBvcnQgbGV0IHBsYWNlaG9sZGVyID0gXCJcIjtcbjwvc2NyaXB0PlxuXG48ZGl2IGNsYXNzPVwiZm9ybS1ncm91cFwiPlxuICA8bGFiZWwgZm9yPXtpZH0gY2xhc3M9e2BsYWJlbCAke3NlbGVjdGVkID09PSBpZCA/IFwiYWN0aXZlXCIgOiBcIlwifWB9PntsYWJlbFRleHR9PC9sYWJlbD5cbiAgPHRleHRhcmVhXG4gICAgaWQ9e2lkfVxuICAgIGNsYXNzPVwiZm9ybS1pbnB1dFwiXG4gICAgdHlwZT1cInRleHRcIlxuICAgIGJpbmQ6dmFsdWU9e3ZhbHVlfVxuICAgIHBsYWNlaG9sZGVyPXtwbGFjZWhvbGRlcn1cbiAgICBhcmlhLXBsYWNlaG9sZGVyPXtwbGFjZWhvbGRlcn1cbiAgLz5cbjwvZGl2PlxuIiwiaW1wb3J0IHtcbiAgY291bnRTZW50ZW5jZXMsXG4gIGNvdW50V29yZHMsXG4gIGNvdW50SGFyZFdvcmRzLFxufSBmcm9tIFwiLi4vaGVscGVycy93cml0dGVuTGFuZ3VhZ2VIZWxwZXJzXCI7XG5cbmV4cG9ydCBjb25zdCBNSU5fR1VOTklOR19GTE9HID0gMDtcbmV4cG9ydCBjb25zdCBNQVhfR1VOTklOR19GTE9HID0gMzA7XG5cbmNvbnN0IHNjb3JlVG9MZXZlbE1hcCA9IHtcbiAgMjA6XHRcIlBvc3QtZ3JhZHVhdGUgUGx1c1wiLFxuICAxOTpcdFwiUG9zdC1ncmFkdWF0ZVwiLFxuICAxODpcdFwiUG9zdC1ncmFkdWF0ZVwiLFxuICAxNzpcdFwiQ29sbGVnZSBncmFkdWF0ZVwiLFxuICAxNjpcdFwiQ29sbGVnZSBzZW5pb3JcIixcbiAgMTU6XHRcIkNvbGxlZ2UganVuaW9yXCIsXG4gIDE0Olx0XCJDb2xsZWdlIHNvcGhvbW9yZVwiLFxuICAxMzpcdFwiQ29sbGVnZSBmcmVzaG1hblwiLFxuICAxMjpcdFwiSGlnaCBzY2hvb2wgc2VuaW9yXCIsXG4gIDExOlx0XCJIaWdoIHNjaG9vbCBqdW5pb3JcIixcbiAgMTA6XHRcIkhpZ2ggc2Nob29sIHNvcGhvbW9yZVwiLFxuICA5Olx0XCJIaWdoIHNjaG9vbCBmcmVzaG1hblwiLFxuICA4Olx0XCJFaWdodGggZ3JhZGVcIixcbiAgNzpcdFwiU2V2ZW50aCBncmFkZVwiLFxuICA2Olx0XCJTaXh0aCBncmFkZVwiLFxufVxuXG5leHBvcnQgY2xhc3MgR3VubmluZ0Zsb2dTY29yZXIge1xuICBzdGF0aWMgY2FsY3VsYXRlKHRleHQpIHtcbiAgICBpZiAoIXRleHQpIHtcbiAgICAgIHJldHVybiBNSU5fR1VOTklOR19GTE9HO1xuICAgIH1cblxuICAgIGNvbnN0IHdvcmRzID0gY291bnRXb3Jkcyh0ZXh0KTtcbiAgICBjb25zdCBhc2wgPSB3b3JkcyAvIGNvdW50U2VudGVuY2VzKHRleHQpO1xuICAgIGNvbnN0IHBodyA9IDEwMCAqIChjb3VudEhhcmRXb3Jkcyh0ZXh0KSAvIHdvcmRzKTtcbiAgICBsZXQgc2NvcmUgPSAwLjQgKiAoYXNsICsgcGh3KVxuXG4gICAgaWYgKHNjb3JlID4gTUFYX0dVTk5JTkdfRkxPRykge1xuICAgICAgc2NvcmUgPSBNQVhfR1VOTklOR19GTE9HO1xuICAgIH0gZWxzZSBpZihzY29yZSA8IE1JTl9HVU5OSU5HX0ZMT0cpIHtcbiAgICAgIHNjb3JlID0gTUlOX0dVTk5JTkdfRkxPRztcbiAgICB9XG5cbiAgICByZXR1cm4gc2NvcmU7XG4gIH1cbiAgc3RhdGljIHNjb3JpbmdMZXZlbChzY29yZSkge1xuICAgIGNvbnN0IGludGVnZXJTY29yZSA9IHBhcnNlSW50KHNjb3JlKTtcbiAgICBjb25zdCBzY29yZXMgPSBPYmplY3Qua2V5cyhzY29yZVRvTGV2ZWxNYXApO1xuICAgIGNvbnN0IG1pblNjb3JlID0gc2NvcmVzWzBdO1xuICAgIGNvbnN0IG1heFNjb3JlID0gc2NvcmVzW3Njb3Jlcy5sZW5ndGggLSAxXTtcblxuICAgIGlmIChpbnRlZ2VyU2NvcmUgPCBtaW5TY29yZSkge1xuICAgICAgcmV0dXJuIFwiXCI7XG4gICAgfTtcblxuICAgIGlmIChzY29yZSA+IG1heFNjb3JlKSB7XG4gICAgICByZXR1cm4gc2NvcmVUb0xldmVsTWFwW21heFNjb3JlXVxuICAgIH0gZWxzZSBpZiAoc2NvcmUgPCBtaW5TY29yZSkge1xuICAgICAgcmV0dXJuIHNjb3JlVG9MZXZlbE1hcFttaW5TY29yZV1cbiAgICB9XG5cbiAgICByZXR1cm4gc2NvcmVUb0xldmVsTWFwW2ludGVnZXJTY29yZV1cbiAgfVxufVxuIiwiPHN0eWxlIGxhbmc9XCJzY3NzXCI+LmNvbnRhaW5lciB7XG4gIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgd2lkdGg6IDEwMCU7IH1cblxuLnZhbHVlQ29udGFpbmVyIHtcbiAgcG9zaXRpb246IHJlbGF0aXZlO1xuICB3aWR0aDogNTAlO1xuICBtYXJnaW46IDAgYXV0bztcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgaGVpZ2h0OiAxLjVlbTsgfVxuICBAbWVkaWEgKG1heC13aWR0aDogNzY4cHgpIHtcbiAgICAudmFsdWVDb250YWluZXIge1xuICAgICAgd2lkdGg6IDEwMCU7IH0gfVxuXG4ucmFuZ2Uge1xuICBoZWlnaHQ6IDJweDtcbiAgbGVmdDogMDtcbiAgcmlnaHQ6IDA7XG4gIHRvcDogNTAlO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7XG4gIGJhY2tncm91bmQtY29sb3I6ICNlY2YwZjE7XG4gIGZsZXg6IDE7IH1cblxuLm1pblZhbHVlIHtcbiAgbGVmdDogMDtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGUoLTEwMCUsIC01MCUpO1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHRvcDogNTAlO1xuICB3aWR0aDogMXB4O1xuICBoZWlnaHQ6IDEuNWVtO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMzQ0OTVlO1xuICBib3JkZXItcmFkaXVzOiAxMDBweDsgfVxuXG4ubWF4VmFsdWUge1xuICByaWdodDogMDtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGUoMTAwJSwgLTUwJSk7XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgdG9wOiA1MCU7XG4gIHdpZHRoOiAxcHg7XG4gIGhlaWdodDogMS41ZW07XG4gIGJhY2tncm91bmQtY29sb3I6ICMzNDQ5NWU7XG4gIGJvcmRlci1yYWRpdXM6IDEwMHB4OyB9XG5cbi5jdXJyZW50VmFsdWUge1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIGJhY2tncm91bmQtY29sb3I6ICMzNDQ5NWU7XG4gIHdpZHRoOiAzdnc7XG4gIGhlaWdodDogM3Z3O1xuICBtYXgtd2lkdGg6IDFlbTtcbiAgbWF4LWhlaWdodDogMWVtO1xuICBib3JkZXItcmFkaXVzOiAxMDAwcHg7XG4gIGxlZnQ6IDQzJTtcbiAgdG9wOiA1MCU7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtNTAlKTsgfVxuXG4ubGltaXRMYWJlbCB7XG4gIGJvdHRvbTogLTEwMCU7XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgbGVmdDogNTAlO1xuICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoLTUwJSk7IH1cblxuLyojIHNvdXJjZU1hcHBpbmdVUkw9VmFsdWVSYW5nZS5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzY3JpcHQ+XG4gIGltcG9ydCB7IG9uTW91bnQgfSBmcm9tICdzdmVsdGUnO1xuICBpbXBvcnQgeyB0d2VlbmVkIH0gZnJvbSAnc3ZlbHRlL21vdGlvbic7XG4gIGltcG9ydCB7IGN1YmljT3V0IH0gZnJvbSAnc3ZlbHRlL2Vhc2luZyc7XG4gIGltcG9ydCB7IGNyZWF0ZVJHQlZhbHVlIH0gZnJvbSBcIi4uL2hlbHBlcnMvY3JlYXRlUkdCVmFsdWVcIjtcblxuICBleHBvcnQgbGV0IGxlZnRWYWx1ZTtcbiAgZXhwb3J0IGxldCByaWdodFZhbHVlO1xuICBleHBvcnQgbGV0IHZhbHVlO1xuICBleHBvcnQgbGV0IHJldmVyc2UgPSBmYWxzZTtcblxuICBsZXQgY3VycmVudEVsZW1lbnRXaWR0aCA9IDA7XG4gIGNvbnN0IGNvbG9ycyA9IFtcbiAgICB7IHJlZDogNDYsIGdyZWVuOiAyMDQsIGJsdWU6IDExMywgfSxcbiAgICB7IHJlZDogMjQzLCBncmVlbjogMTU2LCBibHVlOiAxOCwgfSxcbiAgICB7IHJlZDogMjMxLCBncmVlbjogNzYsIGJsdWU6IDYwLCB9LFxuICBdO1xuICBjb25zdCBwcm9ncmVzcyA9IHR3ZWVuZWQoMCwgeyBkdXJhdGlvbjogMzAwLCBlYXNpbmc6IGN1YmljT3V0IH0pO1xuICBjb25zdCBzZXRDdXJyZW50RWxlbWVudFdpZHRoID0gKCkgPT4ge1xuICAgIGN1cnJlbnRFbGVtZW50V2lkdGggPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiLmN1cnJlbnRWYWx1ZVwiKS5nZXRCb3VuZGluZ0NsaWVudFJlY3QoKS53aWR0aDtcbiAgfTtcblxuICAkOiBwcm9ncmVzcy5zZXQodmFsdWUgLyBNYXRoLm1heChyaWdodFZhbHVlLCBsZWZ0VmFsdWUpKTtcbiAgJDogY3VycmVudFZhbHVlRWxlbWVudFdpZHRoSGFzVG9CZVN1YnRyYWN0ZWQgPSAocmV2ZXJzZSA/ICRwcm9ncmVzcyA8IDAuNSA6ICRwcm9ncmVzcyA+IDAuNSk7XG4gICQ6IHN1YnRyYWN0VmFsdWVUb1ByZXZlbnRPdmVyZmxvdyA9IGAke2N1cnJlbnRWYWx1ZUVsZW1lbnRXaWR0aEhhc1RvQmVTdWJ0cmFjdGVkID8gY3VycmVudEVsZW1lbnRXaWR0aCA6IDB9cHhgO1xuICAkOiBjb2xvciA9IGNyZWF0ZVJHQlZhbHVlKHJldmVyc2UgPyAxIC0gJHByb2dyZXNzIDogJHByb2dyZXNzLCBjb2xvcnMpO1xuICAkOiByZ2IgPSBgcmdiKCR7Y29sb3IucmVkfSwgJHtjb2xvci5ncmVlbn0sICR7Y29sb3IuYmx1ZX0pYDtcbiAgJDogY3VycmVudFZhbHVlU3R5bGUgPSBgYmFja2dyb3VuZC1jb2xvcjogJHtyZ2J9OyBsZWZ0OiBjYWxjKCR7cmV2ZXJzZSA/IFwiMTAwJSAtIFwiIDogXCJcIn0keyRwcm9ncmVzcyAqIDEwMH0lIC0gJHtzdWJ0cmFjdFZhbHVlVG9QcmV2ZW50T3ZlcmZsb3d9KTtgO1xuXG4gIG9uTW91bnQoc2V0Q3VycmVudEVsZW1lbnRXaWR0aCk7XG48L3NjcmlwdD5cblxuPHN2ZWx0ZTp3aW5kb3cgb246cmVzaXplPXtzZXRDdXJyZW50RWxlbWVudFdpZHRofSAvPlxuXG48ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gIDxkaXYgY2xhc3M9XCJ2YWx1ZUNvbnRhaW5lclwiPlxuICAgIDxkaXYgY2xhc3M9XCJyYW5nZVwiIC8+XG4gICAgPGRpdiBjbGFzcz1cIm1pblZhbHVlXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cImxpbWl0TGFiZWxcIj57bGVmdFZhbHVlfTwvc3Bhbj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwibWF4VmFsdWVcIj5cbiAgICAgIDxzcGFuIGNsYXNzPVwibGltaXRMYWJlbFwiPntyaWdodFZhbHVlfTwvc3Bhbj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwiY3VycmVudFZhbHVlXCIgc3R5bGU9e2N1cnJlbnRWYWx1ZVN0eWxlfSAvPlxuICA8L2Rpdj5cbjwvZGl2PlxuIiwiZnVuY3Rpb24gaW50ZXJwb2xhdGUodmFsdWUsIG1pbiwgbWF4KSB7XG4gIHZhciBkZWx0YSA9IG1heCAtIG1pbjtcbiAgdmFyIHN0ZXBWYWx1ZSA9IGRlbHRhIC8gMTAwO1xuICByZXR1cm4gbWluICsgc3RlcFZhbHVlICogTWF0aC5mbG9vcih2YWx1ZSAqIDEwMCk7XG59XG5cbi8qKlxuICogQ3JlYXRlIGFuIFJHQiB2YWx1ZSBsb2NhdGVkIGJldHdlZW4gMyBjb2xvcnNcbiAqXG4gKiBAcGFyYW0ge251bWJlcn0gdmFsdWUgLSBWYWx1ZSBiZXR3ZWVuIDAgYW5kIDFcbiAqIEBwYXJhbSB7eyByZWQ6IG51bWJlcjsgZ3JlZW46IG51bWJlcjsgYmx1ZTogbnVtYmVyOyB9W119IGNvbG9ycyAtIEFycmF5IG9mIHJnYiBjb2xvcnNcbiAqL1xuZXhwb3J0IGZ1bmN0aW9uIGNyZWF0ZVJHQlZhbHVlKHZhbHVlLCBjb2xvcnMpIHtcbiAgbGV0IHJlZDtcbiAgbGV0IGdyZWVuO1xuICBsZXQgYmx1ZTtcblxuICBjb25zdCBbXG4gICAgc3RhcnRDb2xvcixcbiAgICBtaWRDb2xvcixcbiAgICBlbmRDb2xvcixcbiAgXSA9IGNvbG9ycztcblxuICBpZiAodmFsdWUgPiAwLjUpIHtcbiAgICByZWQgPSBpbnRlcnBvbGF0ZSgodmFsdWUgLSAwLjUpIC8gMC41LCBtaWRDb2xvci5yZWQsIGVuZENvbG9yLnJlZCk7XG4gIH0gZWxzZSB7XG4gICAgcmVkID0gaW50ZXJwb2xhdGUodmFsdWUgLyAwLjUsIHN0YXJ0Q29sb3IucmVkLCBtaWRDb2xvci5yZWQpO1xuICB9XG5cbiAgaWYgKHZhbHVlID4gMC41KSB7XG4gICAgZ3JlZW4gPSBpbnRlcnBvbGF0ZSgodmFsdWUgLSAwLjUpIC8gMC41LCBtaWRDb2xvci5ncmVlbiwgZW5kQ29sb3IuZ3JlZW4pO1xuICB9IGVsc2Uge1xuICAgIGdyZWVuID0gaW50ZXJwb2xhdGUodmFsdWUgLyAwLjUsIHN0YXJ0Q29sb3IuZ3JlZW4sIG1pZENvbG9yLmdyZWVuKTtcbiAgfVxuXG4gIGlmICh2YWx1ZSA+IDAuNSkge1xuICAgIGJsdWUgPSBpbnRlcnBvbGF0ZSgodmFsdWUgLSAwLjUpIC8gMC41LCBtaWRDb2xvci5ibHVlLCBlbmRDb2xvci5ibHVlKTtcbiAgfSBlbHNlIHtcbiAgICBibHVlID0gaW50ZXJwb2xhdGUodmFsdWUgLyAwLjUsIHN0YXJ0Q29sb3IuYmx1ZSwgbWlkQ29sb3IuYmx1ZSk7XG4gIH1cblxuICByZXR1cm4ge1xuICAgIHJlZCxcbiAgICBncmVlbixcbiAgICBibHVlLFxuICB9O1xufVxuIiwiaW1wb3J0IHN5bGxhYmxlIGZyb20gXCJzeWxsYWJsZVwiO1xuXG5leHBvcnQgZnVuY3Rpb24gY291bnRXb3Jkcyh0ZXh0KSB7XG4gIHJldHVybiBmaW5kV29yZHModGV4dCkubGVuZ3RoIHx8IDE7XG59XG5cbmV4cG9ydCBmdW5jdGlvbiBmaW5kV29yZHModGV4dCkge1xuICByZXR1cm4gdGV4dC5tYXRjaCgvKFteXFx1MDAwMC1cXHUwMDdGXXxcXHcpKy9nKSB8fCBbXTtcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGNvdW50U2VudGVuY2VzKHRleHQpIHtcbiAgY29uc3QgbWF0Y2ggPSB0ZXh0Lm1hdGNoKC9bXFx3XVxcKT9bLj8hXShcXHN8JCkvZykgfHwgW107XG4gIHJldHVybiBtYXRjaC5sZW5ndGggfHwgMTtcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGNvdW50SGFyZFdvcmRzKHRleHQpIHtcbiAgY29uc3QgdGV4dExvd2VyID0gdGV4dC50b0xvd2VyQ2FzZSgpO1xuICBsZXQgY291bnQgPSAwO1xuXG4gIGZpbmRXb3Jkcyh0ZXh0TG93ZXIpLmZvckVhY2god29yZCA9PiB7XG4gICAgaWYgKGNvdW50V29yZFN5bGxhYmxlcyh3b3JkKSA+PSAzKSB7XG4gICAgICBjb3VudCArPSAxO1xuICAgIH1cbiAgfSlcblxuICByZXR1cm4gY291bnQ7XG59XG5cbmV4cG9ydCBmdW5jdGlvbiBjb3VudFN5bGxhYmxlcyh0ZXh0KSB7XG4gIGNvbnN0IHRleHRMb3dlciA9IHRleHQudG9Mb3dlckNhc2UoKTtcbiAgbGV0IGNvdW50ID0gMDtcblxuICBmaW5kV29yZHModGV4dExvd2VyKS5mb3JFYWNoKHdvcmQ9PiB7XG4gICAgY291bnQgKz0gY291bnRXb3JkU3lsbGFibGVzKHdvcmQpO1xuICB9KVxuXG4gIHJldHVybiBjb3VudFxuXG59XG5cbmZ1bmN0aW9uIGNvdW50V29yZFN5bGxhYmxlcyhvcmlnaW5hbFdvcmQpIHtcbiAgcmV0dXJuIHN5bGxhYmxlKG9yaWdpbmFsV29yZClcbn1cbiIsIjxzdHlsZSBsYW5nPVwic2Nzc1wiPioge1xuICBmb250LWZhbWlseTogXCJNb250c2VycmF0XCIsIHNhbnMtc2VyaWY7IH1cblxuOmdsb2JhbChpbnB1dCksXG46Z2xvYmFsKHRleHRhcmVhKSB7XG4gIGJveC1zaGFkb3c6IDAgMCAwLjVlbSByZ2JhKDAsIDAsIDAsIDAuMSk7XG4gIC13ZWJraXQtYXBwZWFyYW5jZTogbm9uZTtcbiAgYm9yZGVyOiAwO1xuICBmb250LWZhbWlseTogaW5oZXJpdDtcbiAgZm9udC1zaXplOiBpbmhlcml0OyB9XG5cbi5jb250YWluZXIge1xuICBkaXNwbGF5OiBmbGV4O1xuICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7IH1cblxuLnNjb3JlLWNvbnRhaW5lciB7XG4gIG1hcmdpbjogMWVtIDA7IH1cblxuLnNjb3JlLWxhYmVsIHtcbiAgbWFyZ2luOiAwO1xuICBjb2xvcjogIzM0NDk1ZTsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzY3JpcHQ+XG4gIGltcG9ydCBGb3JtR3JvdXAgZnJvbSBcIi4uL2NvbXBvbmVudHMvRm9ybUdyb3VwLnN2ZWx0ZVwiO1xuICBpbXBvcnQgVmFsdWVSYW5nZSBmcm9tIFwiLi4vY29tcG9uZW50cy9WYWx1ZVJhbmdlLnN2ZWx0ZVwiO1xuICBpbXBvcnQge1xuICAgIEZsZXNjaEtpbmNhaWRTY29yZXIsXG4gICAgTUFYX0ZMRVNDX0tJTkNBSUQsXG4gICAgTUlOX0ZMRVNDX0tJTkNBSUQsXG4gIH0gZnJvbSBcIi4uL2NvbXBvbmVudHMvRmxlc2NoS2luY2FpZFNjb3Jlci5qc1wiO1xuICBpbXBvcnQge1xuICAgIEd1bm5pbmdGbG9nU2NvcmVyLFxuICAgIE1BWF9HVU5OSU5HX0ZMT0csXG4gICAgTUlOX0dVTk5JTkdfRkxPRyxcbiAgfSBmcm9tIFwiLi4vY29tcG9uZW50cy9HdW5uaW5nRmxvZ1Njb3Jlci5qc1wiO1xuXG4gIGxldCBzdWJqZWN0VGV4dCA9IFwiXCI7XG4gICQ6IGZsZXNjaEtpbmNhaWRTY29yZSA9IEZsZXNjaEtpbmNhaWRTY29yZXIuY2FsY3VsYXRlKHN1YmplY3RUZXh0KTtcbiAgJDogZ3VubmluZ0Zsb2dTY29yZSA9IEd1bm5pbmdGbG9nU2NvcmVyLmNhbGN1bGF0ZShzdWJqZWN0VGV4dCk7XG48L3NjcmlwdD5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+VGV4dCBTY29yZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gIDxoMT5Ib3cgcmVhZGFibGUgaXMgeW91ciB0ZXh0PzwvaDE+XG4gIDxzbWFsbD48L3NtYWxsPlxuICA8aHIvPlxuICA8Rm9ybUdyb3VwXG4gICAgaWQ9e1wic3ViamVjdFRleHRcIn1cbiAgICBiaW5kOnZhbHVlPXtzdWJqZWN0VGV4dH1cbiAgICBwbGFjZWhvbGRlcj1cIldyaXRlIHlvdXIgdGV4dCBoZXJlIGFuZCBzZWUgdGhlIHNjb3JlIGJlaW5nIGNhbGN1bGF0ZWRcIlxuICAvPlxuICA8ZGl2IGNsYXNzPVwic2NvcmUtY29udGFpbmVyXCI+XG4gICAgPHAgY2xhc3M9XCJzY29yZS1sYWJlbFwiPlxuICAgICAgPHNtYWxsPkZsZXNjaCBLaW5jYWlkIFJlYWRpbmcgRWFzZTo8L3NtYWxsPlxuICAgICAgPHNwYW4gY2xhc3M9XCJzY29yZS12YWx1ZVwiPntmbGVzY2hLaW5jYWlkU2NvcmUudG9GaXhlZCgyKX08L3NwYW4+XG4gICAgPC9wPlxuICAgIDxWYWx1ZVJhbmdlXG4gICAgICByZXZlcnNlPXt0cnVlfVxuICAgICAgcmlnaHRWYWx1ZT17TUlOX0ZMRVNDX0tJTkNBSUR9XG4gICAgICBsZWZ0VmFsdWU9e01BWF9GTEVTQ19LSU5DQUlEfVxuICAgICAgdmFsdWU9e2ZsZXNjaEtpbmNhaWRTY29yZX1cbiAgICAvPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cInNjb3JlLWNvbnRhaW5lclwiPlxuICAgIDxwIGNsYXNzPVwic2NvcmUtbGFiZWxcIj5cbiAgICAgIDxzbWFsbD5HdW5uaW5nIGZvZyBpbmRleDo8L3NtYWxsPlxuICAgICAgPHNwYW4gY2xhc3M9XCJzY29yZS12YWx1ZVwiPntndW5uaW5nRmxvZ1Njb3JlLnRvRml4ZWQoMil9PC9zcGFuPlxuICAgICAgPGJyLz5cbiAgICAgIDxzbWFsbCBjbGFzcz1cInNjb3JlLWxhYmVsXCI+e0d1bm5pbmdGbG9nU2NvcmVyLnNjb3JpbmdMZXZlbChndW5uaW5nRmxvZ1Njb3JlKX08L3NtYWxsPlxuICAgIDwvcD5cbiAgICA8VmFsdWVSYW5nZVxuICAgICAgbGVmdFZhbHVlPXtNSU5fR1VOTklOR19GTE9HfVxuICAgICAgcmlnaHRWYWx1ZT17TUFYX0dVTk5JTkdfRkxPR31cbiAgICAgIHZhbHVlPXtndW5uaW5nRmxvZ1Njb3JlfVxuICAgIC8+XG4gIDwvZGl2PlxuPC9kaXY+XG4iXSwic291cmNlUm9vdCI6IiJ9